### ISSUE TITLE
bundle: command not found

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [zammad/zammad-docker-compose#1]
- Rancher environment
- Docker image zammad/zammad-docker-compose:zammad

```
1/9/2017 9:13:05 PMcreating db & searchindex...
1/9/2017 9:13:05 PM/docker-entrypoint.sh: line 10: bundle: command not found
1/9/2017 9:13:05 PM/docker-entrypoint.sh: line 11: bundle: command not found
1/9/2017 9:13:05 PM/docker-entrypoint.sh: line 12: bundle: command not found
1/9/2017 9:13:05 PM/docker-entrypoint.sh: line 13: bundle: command not found
1/9/2017 9:13:05 PM/docker-entrypoint.sh: line 14: bundle: command not found
1/9/2017 9:13:05 PMrm: cannot remove '/home/zammad/log/*.log': No such file or directory
1/9/2017 9:13:05 PMrm: cannot remove '/home/zammad/tmp/pids/*.pid': No such file or directory
1/9/2017 9:13:05 PMstarting zammad...
1/9/2017 9:13:05 PMzammad will be accessable on http://localhost in some seconds
1/9/2017 9:13:05 PM/docker-entrypoint.sh: line 24: bundle: command not found
1/9/2017 9:13:05 PM/docker-entrypoint.sh: line 25: bundle: command not found
1/9/2017 9:13:05 PM/docker-entrypoint.sh: line 28: bundle: command not found
```

**Comment by monotek** [comment]
@hhoechtl
You're using rancher, right?
Can you help?

**Comment by hhoechtl** [comment]
Yes I do, but that issue has nothing to do with rancher. The log indicates that the container that is trying to run the entrypoint script doesn't have ruby installed and therefore must be an invalid image, because the zammad image is built on top of the ruby image.

@Ilya-Kuchaev Which image are you using? I just tried it with f27d5689cbcc and didn't give me a "bundle is not installed" message.

**Comment by Ilya-Kuchaev** [comment]
I'm using the latest `zammad/zammad-docker-compose:zammad` image.

**Comment by hhoechtl** [comment]
You are mounting /opt/zammad/data-ruby to /usr/local ... that overwrites all local software of the container including `ruby` and `bundle`. 
That's not how it is supposed to be, just use the entire `docker-compose.yml` from this repository or try my version of it: https://github.com/1drop/zammad-docker-compose/blob/master/docker-compose.yml
And btw., that has nothing to do with it, but you are missing the nginx container, which takes care of the websockets, the static assets (CSS, JS) and the thread connection handling => don't access puma directly.

Btw @monotek if have no idea what you're trying to achieve with the volume data-ruby. In my opinion it's totally unnecessary and just leads to mistakes like this one.

**Comment by Ilya-Kuchaev** [comment]
Hm... I'm able to start the services without volumes.
Have I mount any directory to host to persist the zammad data? Uploads, etc.

**Comment by hhoechtl** [comment]
For the zammad container itself you don't need to mount any directory. By default the uploads are stored inside the postgresql database (which is not optimal for huge amounts of data, but in my case sufficient).
The named volume of the zammad container is just so you can mount it into the nginx container to serve the static assets. But as they are generated during the container startup, they don't need to be persisted.
Same for elasticsearch, the index is always rebuild on container startup.
Therefore only the postgres container has a persistent mount for the data.

**Comment by monotek** [comment]
@hhoechtl 

Thanks fotr the hint. Its right, the volume is superfluous. Its left from the version where bundle update was done in the docker entrypoint. 

Removed it in https://github.com/zammad/zammad-docker-compose/commit/e08cc98c471b4248c9109434dde3fd6de8c2c5c3

If you have more suggestions... Pull requests are welcome :-)

P.S: The assets creation was moved to the container build. 
Its not created on every startup anymore.
