### ISSUE TITLE
Chat: Problem on custum port

### ISSUE THREAD

**Issue by omexXx** [zammad/zammad-docker-compose#10]
Hello,

When taking a custum port on docker there are problems with the chat:
http://support.local:2218/assets/chat/chat.min.js => 404 Not Found

**Comment by martini** [comment]
I can't follow. Please add informations about:

1) What Zammad version did you use.

2) What is you goal?

3) What is your discovered problem?

4) What did you expect?

5) Add more infos about the error message (what log console log or rails log)

By the way, if you want to use Zammad+Chat on public site, I recommend the following:
a) Use standard ports (proxy server will not work with port 2218)
b) Do not mix https and http content (most browser will block this).

In certain cases you need to define the host url via the widget like:

```
  var chat = new ZammadChat({
    chatId: 1,
    host: 'http://zammad.host/assets/chat/chat.css',
  })
```

**Comment by omexXx** [comment]
1. actual version
2. i have defined in the 'compose.yml' an other port for the host '2218' because i can't use the standart port , there are other services run on the host with this port (thats because i use docker to install it)
3. and if there is a port there are a 404 error on getting the file => http://support.local:2218/assets/chat/chat.min.js
4. to get this run with a port :D
5. how can i see the logs?

**Comment by martini** [comment]
Sorry, I can't help you with this description.

```
and if there is a port there are a 404 error on getting the file => http://support.local:2218/assets/chat/chat.min.js
```

From where did you call this? What is the content of http://support.local:2218 ?

```
how can i see the logs?
```

You wrote the error message, "http://support.local:2218/assets/chat/chat.min.js => 404 Not Found" I don't know where you got this from.

**Comment by omexXx** [comment]
Until now i have fixed some issue, but i receive that:
WebSocket connection to 'ws://support.local:2218/' failed: Error during WebSocket handshake: Unexpected response code: 200

**Comment by omexXx** [comment]
Hi @martini ,

I tested a lot in a virtual machine to get this installed, i have a ISP installed on the server (i-MSCP) that uses the standart port '80' allready, thats because i can't install it in the standart way.

So how can i install this on docker running on different port and get all running? :/

**Comment by monotek** [comment]
We don't know your i-MSCP environment and hence can't support it.
If you change the ports you have to know what your're doing.
I also doubt that this has anything to do with the docker container.

**Comment by omexXx** [comment]
Hello,

Imscp (https://i-mscp.net/) is a control panel for webhosting. Now because of that i want to use zammad on a docker-container), i get it to work with changed the ports in docker-compose.yml but there the chat doesn't work withs the errors described above.

I-MSCP use this ports + standart ports like ftp, ssh and so on:
By default and for HTTP, i-MSCP only use 80, 443 (for customers) and 8880, 8443 for the control panel.

Because of the port 80 already used in can not set it in standart style, i don't know how to handle that now exactly?

Thanks

**Comment by omexXx** [comment]
Hi,

Okay, on local test-system i have it run now:
1. do all like the documents says
2. edit docker-compose.yml => change nginx port as you want and not in use
3. For chat define like this:
```
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
      <script src="http://support.local/assets/chat/chat.min.js"></script>
<script>
$(function() {
  new ZammadChat({
    fontSize: '12px',
    chatId: 1,
    debug: true,
    host: 'ws://support.local:2218/ws',
    background: '#fd7c2c'
  });
});
</script>
```
And all is working like a charm, nothing to change where else in nginx.conf

**Comment by monotek** [comment]
So we can close this issue too?

**Comment by omexXx** [comment]
Yes i think so :)

But the approach is so correct and productive?

What if a update trought pull get maked, my settings get overwritten?
Thank you

**Comment by monotek** [comment]
As i said before. We don't know i-MSCP and hence don't support it. 
If you changed things its possible it will break at some point.
We can't guarantee that your changes will still work after an update.

**Comment by omexXx** [comment]
Nobody talks here about imscp in my previrious question...
