### ISSUE TITLE
Ability to overwrite the app config

### ISSUE THREAD

**Issue by zifeo** [zammad/zammad-docker-compose#100]
### Infos:

* Docker version: any
* Docker-compose version: any
* Operating system (Docker host): Debian

### Expected behavior:

* Be able to overwrite https://github.com/zammad/zammad/blob/develop/config/application.rb#L63 as mentioned in https://github.com/zammad/zammad/issues/1113

### Actual behavior:

* Cannot find an easy way

### Steps to reproduce the behavior:

* Launch or restart a docker compose stack

**Comment by monotek** [comment]
build your own docker container with changed files...

**Comment by zifeo** [comment]
Which docker should contain that file change in the stacks, only railsserver or init? Would a file mount/override also do the job?

**Comment by monotek** [comment]
it's the same container for all services.
