### ISSUE TITLE
Compose stuck in "waiting for init container to finish install or update" state

### ISSUE THREAD

**Issue by casalot** [zammad/zammad-docker-compose#101]
After working through the steps in the compose installation for Zammad, and running `docker-compose up`, most of the containers output "**waiting for init container to finish install or update**" in the console log.

I have looked at some of the suggestions in the docs, but it does not seems to work. Surely running `docker-compose up` should just start all containers, without an issue?

Mac OS: 10.14.2
Docker: 18.09.2
Docker-compose: 1.23.2

**Comment by monotek** [comment]
This can take a while. 
How long do you have waited?

**Comment by casalot** [comment]
After allocating more memory to the docker-engine, the compose containers started up.

**Comment by tobecwb** [comment]
Same here..
Waited for more than 2 hours...
