### ISSUE TITLE
Global Bcc for all outgoing emails for external archive options.

### ISSUE THREAD

**Issue by flemssound** [zammad/zammad-docker-compose#104]
### Infos:

* Docker version: 18.09.2
* Docker-compose version: 1.18.0
* Operating system (Docker host): ubuntu LTS 18.04

Is there a way to set a global bcc for archiving? 

Like this issue here:
https://github.com/zammad/zammad/issues/2228

**Comment by MrGeneration** [comment]
For the next time, please consult the community for technical questions.
If you look at this comment: https://github.com/zammad/zammad/issues/2228#issuecomment-433353656 where you can find the needed command.

Remove `zammad run` and run the rails command within your docker container.
