### ISSUE TITLE
Docker-compose for 3.1 no longer building

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad-docker-compose#106]
### Infos:

* Docker version: 3.1.x
* Docker-compose version: any
* Operating system (Docker host): any

### Expected behavior:

Docker-Compose should be so kind and built the Zamamd 3.1 container.

### Actual behavior:

Building docker-compose with ruby 2.4.4 doesn't work, as Zammad 3.1 requires ruby 2.5.5

### Steps to reproduce the behavior:

* try to build from 3.1 branch

**Comment by monotek** [comment]
fixed with: https://github.com/zammad/zammad-docker-compose/pull/108
