### ISSUE TITLE
Error running on ubuntu 16.04

### ISSUE THREAD

**Issue by Hendrik44** [zammad/zammad-docker-compose#11]
hi there,

i get the following message running docker image on ubuntu 16.04

`zammad-scheduler_1      | scheduler waiting for zammads railsserver to be ready...
zammad-scheduler_1      | scheduler waiting for zammads railsserver to be ready...
zammad-scheduler_1      | scheduler waiting for zammads railsserver to be ready...
zammad-websocket_1      | websocket server waiting for zammads railsserver to be ready...
zammad-scheduler_1      | scheduler waiting for zammads railsserver to be ready...
zammad-scheduler_1      | scheduler waiting for zammads railsserver to be ready...
zammad-railsserver_1    | * Listening on tcp://0.0.0.0:3000
zammad-railsserver_1    | Use Ctrl-C to stop
zammad-railsserver_1    | 2017-03-16 11:04:42 +0000: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
zammad-railsserver_1    | 2017-03-16 11:04:42 +0000: ENV: {"rack.version"=>[1, 3], "rack.errors"=>#<IO:<STDERR>>, "rack.multithread"=>true, "rack.multiprocess"=>false, "rack.run_once"=>false, "SCRIPT_NAME"=>"", "QUERY_STRING"=>"", "SERVER_PROTOCOL"=>"HTTP/1.1", "SERVER_SOFTWARE"=>"puma 3.6.0 Sleepy Sunday Serenity", "GATEWAY_INTERFACE"=>"CGI/1.2"}
zammad-railsserver_1    | ---
zammad-railsserver_1    | 2017-03-16 11:04:42 +0000: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
zammad-railsserver_1    | 2017-03-16 11:04:42 +0000: ENV: {"rack.version"=>[1, 3], "rack.errors"=>#<IO:<STDERR>>, "rack.multithread"=>true, "rack.multiprocess"=>false, "rack.run_once"=>false, "SCRIPT_NAME"=>"", "QUERY_STRING"=>"", "SERVER_PROTOCOL"=>"HTTP/1.1", "SERVER_SOFTWARE"=>"puma 3.6.0 Sleepy Sunday Serenity", "GATEWAY_INTERFACE"=>"CGI/1.2"}
zammad-railsserver_1    | ---`

How can i fix this issue? Any suggestions?

**Comment by Hendrik44** [comment]
Ok i have fix it ;-)

**Comment by thorsteneckel** [comment]
Would be great to share what has fixed it for you so others can use it.

**Comment by Hendrik44** [comment]
i removed the downloaded images and start with a clean docker system. After two tries it works
