### ISSUE TITLE
Backups are not created

### ISSUE THREAD

**Issue by JanHegemann** [zammad/zammad-docker-compose#111]
### Infos:

* Docker version: 1.13.1
* Docker-compose version: 1.18.0
* Operating system (Docker host): Linux CentOs 7

### Expected behavior:

* Backups should be created automatically at docker-compose up in the volumes/zammaddockercompose_zammad-backup folder
 

### Actual behavior:

* zammad-backup_1         | 20190811075811 - backuping zammad...
zammad-backup_1         | tar: can't open '/var/tmp/zammad/20190811075811_zammad_files.tar.gz': Permission denied

### Steps to reproduce the behavior:

* restart the container

**Comment by MrGeneration** [comment]
Could you please provide your docker-compose.yml / docker-compose.override.yml ?

I just tested this with the original vanilla repo files with the latest version (`-3.1.0-10`) and cannot reproduce this.

```
zammad-backup_1         | waiting for railsserver to be ready...
zammad-backup_1         | 20190816154241 - backuping zammad...
zammad-backup_1         | tar: removing leading '/' from member names
zammad-backup_1         | 20190816154607 - backuping zammad...
zammad-backup_1         | tar: removing leading '/' from member names
```

It just works.
If you're using custom directories ensure that your directory rights are correct. I'm afraid that this is rather a technical question that's not directly related to Zammad as application and thus out of scope. :-X

**Comment by JanHegemann** [comment]
Here are the two files(Could not upload the .yml files so both in the zip)

[docker-compose.zip](https://github.com/zammad/zammad-docker-compose/files/3524846/docker-compose.zip)

**Comment by monotek** [comment]
please, could you just post them via code tags?

**Comment by JanHegemann** [comment]
Fixed it. Here the changed Code:
` zammad-backup:
command: ["zammad-backup"]
depends_on:
      - zammad-railsserver
    entrypoint: /usr/local/bin/backup.sh
    image: ${IMAGE_REPO}:zammad-postgresql${VERSION}
    links:
      - zammad-postgresql
    restart: ${RESTART}
    volumes:
      - zammad-backup:/var/tmp/zammad:Z
      - zammad-data:/opt/zammad:Z`
Just added a :Z to the volume paths. That fixed the Problems with SELinux
