### ISSUE TITLE
SMTP OpenSSL Error with latest Version

### ISSUE THREAD

**Issue by svenschumacher** [zammad/zammad-docker-compose#112]
### Infos:

* Docker version: 18.09.7
* Operating system (Docker host): Ubuntu 19.04.

### Expected behavior:

* I can update via _docker-compose pull_ and everything works fine. 

### Actual behavior:

* I´ve updated via _docker-compose pull_, everything works fine, except the SMTP connection for sending E-Mails. 

### Steps to reproduce the behavior:

* Update to latest with docker-compose pull
* Send an E-Mail from a ticket
* Receive the error message "Zustellung fehlgeschlagen: "Unable to send email to 'XXXX@XXXX.de': Can't use Channel::Driver::Smtp: #<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: unsupported protocol>"

### Workaround
After lots of hours of exchange troubleshooting with the latest tag (3.1.0-7), I decided to switch back to image tag 3.1.0-6, but it didn´t work. First the step back to 3.0.0-15 did the trick. Now everything works fine. 

### Hints
While testing lots of configurations from exchange side, i got different error messages. For example: 

* "net::ReadTimeout" 
* "SSL_connect returned=1 errno=0 state=error: wrong". 

It feels like a problem between Ruby and Elasticsearch.

**Comment by koelle25** [comment]
I also got this error (`SSL_connect returned=1 errno=0 state=error: unsupported protocol`) while setting up outgoing SMTP settings on a completely new instance of Zammad with image tag 3.1.0-10.
With the image tag 3.0.0-15 it works like a charm.

**Comment by svenschumacher** [comment]
The issue still exists in 3.2.0-51 from yesterday.

**Comment by ppeinsold** [comment]
svenschumacher could you explain how you did go back to version 3.0.0-15 please?

**Comment by svenschumacher** [comment]
@ppeinsold I changed the label in .env. 

```
VERSION=-3.0.0-15
RESTART=always
```

**Comment by ppeinsold** [comment]
@svenschumacher thx for the quick response. Is the "-" sign before "3.0.0-15" inteded or a typo?

**Comment by waja** [comment]
@ppeinsold it is intended

**Comment by ppeinsold** [comment]
Sorry for my last question... still a bit of a docker noob:
Do I need to build once more in order to downgrade?
I would run:
docker-compose down
docker-compose up --build

Is this correct? Do I loose all data which I have in my current zammad when I do that?

**Comment by waja** [comment]
> I would run:
docker-compose down
docker-compose up --build

A `docker-compose down && docker-compose up` should do the trick.

**Comment by ppeinsold** [comment]
Downgrade worked, but still did not solve the smtp problem. We always get the error "Can't use Channel::Driver::Smtp: #<Net::OpenTimeout: execution expired>"
Do you know in which docker container and at which location the production.log is? Maybe it tells me a little bit more...

**Comment by koelle25** [comment]
The issue is **still** existing with the current `-3.2.0-6` image tag!
Can someone (of the maintainers) *please* look into this? I don't have enough knowledge of the underlying structure to analyse it on my own - but I would be happy to help!

**Comment by koelle25** [comment]
Okay, so I just tested with another SMTP server - and it worked. The culprit seems to be that the non-working SMTP server is using (deprecated) TLSv1/SSLv3.

This is the output from `docker-compose exec zammad-railsserver openssl s_client -connect smtp.example.com:587 --starttls smtp` for the working server:
```
CONNECTED(00000003)
[...]
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 4428 bytes and written 419 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
```

And this is the output for the non-working server:
```
CONNECTED(00000003)
139895585633408:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../ssl/statem/statem_lib.c:1929:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 303 bytes and written 355 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
```

The output for the non-working server from another machine (using `openssl s_client -connect smtp.example.com:587 --starttls smtp`):
```
CONNECTED(00000003)
[...]
---
No client certificate CA names sent
Peer signing digest: MD5-SHA1
Peer signature type: RSA
Server Temp Key: DH, 1024 bits
---
SSL handshake has read 7970 bytes and written 556 bytes
Verification: OK
---
New, SSLv3, Cipher is DHE-RSA-AES256-SHA
Server public key is 4096 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1
    Cipher    : DHE-RSA-AES256-SHA
    Session-ID: 52C69BFDB947A0218F898B1A618FF750E358D5A91CC234220FD60EC7638D3D2E
    Session-ID-ctx:
    Master-Key: 736629FBCF330C270E64C117D9626816D7AE3794F710C644130585F128B656E3DD7C3D34D9F161478F1136A73EFCC87C
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket:
    0000 - 26 9f 6f a1 1e 58 23 f3-48 8e cb c7 a4 bc 45 c7   &.o..X#.H.....E.
    0010 - 22 f9 75 a9 87 45 3b 77-36 1d 0c 17 0b 80 bc c9   ".u..E;w6.......
    0020 - c2 7f 56 14 b5 8a b3 dc-ce 65 e3 15 bb 12 43 99   ..V......e....C.
    0030 - 3b 52 89 03 c4 f3 d0 0b-80 2d 21 53 69 f4 53 63   ;R.......-!Si.Sc
    0040 - ba 42 41 9d 88 35 a0 3f-cf 67 2e 62 71 61 66 c0   .BA..5.?.g.bqaf.
    0050 - da b3 54 35 86 ce d5 d9-3a f1 fe af 95 92 ea bf   ..T5....:.......
    0060 - 7b 95 18 d8 f9 4e 28 6e-c3 a2 3e ae 3d 78 58 56   {....N(n..>.=xXV
    0070 - 07 26 a6 08 8b 20 c9 e9-82 3f e7 37 8a 8c ff 52   .&... ...?.7...R
    0080 - 0f ed a2 72 6d 8f ba 30-98 b4 dc 84 14 a4 0b c2   ...rm..0........
    0090 - 18 c2 7c ae a2 39 91 d0-80 42 19 a6 c7 2d 2c 5b   ..|..9...B...-,[
    00a0 - f3 88 94 ca 95 00 2a 18-e5 f7 a2 ee d2 98 d8 3a   ......*........:
    00b0 - a5 17 72 be dd e6 58 db-1c 24 9c 02 44 f8 85 71   ..r...X..$..D..q

    Start Time: 1575912416
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
```

**Comment by koelle25** [comment]
It seems to be the underlying Debian system, which is patched to only use TLSv1.2 or higher, unless explicitely specified otherwise (see e.g. https://bugs.python.org/issue31453).

After some extensive research this workaround seems to work:

Find the following block in `/usr/local/bundle/bundler/gems/mail-9265cf75bbe3/lib/mail/network/delivery_methods/smtp.rb`:
```ruby
def ssl_context
        openssl_verify_mode = settings[:openssl_verify_mode]

        if openssl_verify_mode.kind_of?(String)
          openssl_verify_mode = OpenSSL::SSL.const_get("VERIFY_#{openssl_verify_mode.upcase}")
        end

        context = Net::SMTP.default_ssl_context
        context.verify_mode = openssl_verify_mode if openssl_verify_mode
        context.ca_path = settings[:ca_path] if settings[:ca_path]
        context.ca_file = settings[:ca_file] if settings[:ca_file]
        context
      end
```

And add this line:
```ruby
context.min_version = OpenSSL::SSL::TLS1_VERSION
```

In my case I also had to add the following line because the mailserver is so much outdated ... :
```ruby
context.ciphers = "DEFAULT:!DH"
```

After that, restart the railsserver container:
```docker
docker-compose restart zammad-railsserver
```

**Comment by thorsteneckel** [comment]
Thanks for the investigation @koelle25 and kudos for finding this out! This will definitely help others finding their way to here.
I'll close this issue because TLSv1/SSLv3 is deprecated because of security issues. We can't and won't add exceptions for using insecure cryptographic protocols.
