### ISSUE TITLE
production.log location

### ISSUE THREAD

**Issue by ppeinsold** [zammad/zammad-docker-compose#115]
We still have issues with sending Mails via SMTP.
For further investigation we need the zammad production.log
Can anyone tell me in which container at which location the production.log is if we run zammad with zammad-docker-compose?

Thanks a lot!

**Comment by MrGeneration** [comment]
It should be living within the railscontainer

**Comment by ppeinsold** [comment]
@MrGeneration I thought so too, but I cant find it. Do you know the location?

**Comment by MrGeneration** [comment]
`/opt/zammad/log`

if not it's logging to STDOUT.

**Comment by ppeinsold** [comment]
The directory you mentioned is empty. But you were right with your second guess! It's logging to STDOUT. You can show the logs from outside of the container with command
`docker logs -f <container_id>`.

Here is my log when I try to send a Mail. It does not help me a lot, because it tells me the same error message like the UI does. Or do I oversee somethig?

Thx a lot!

> I, [2019-09-04T12:47:35.150681 #1-47212809184900]  INFO -- : Send notification to: testuser@gmail.com (from:Notification Master <test@herosphere.gg>/subject:Zurücksetzen Ihres herosphere.gg Support Passworts
)
I, [2019-09-04T12:47:54.176763 #1-47212809184220]  INFO -- : Started GET "/" for ::ffff:172.18.0.10 at 2019-09-04 12:47:54 +0000
I, [2019-09-04T12:47:54.184412 #1-47212809184220]  INFO -- : Processing by InitController#index as HTML
I, [2019-09-04T12:47:54.189782 #1-47212809184220]  INFO -- :   Rendering init/index.html.erb within layouts/application
I, [2019-09-04T12:47:54.189985 #1-47212809184220]  INFO -- :   Rendered init/index.html.erb within layouts/application (0.1ms)
I, [2019-09-04T12:47:54.192718 #1-47212809184220]  INFO -- : Completed 200 OK in 8ms (Views: 1.6ms | ActiveRecord: 2.3ms)
I, [2019-09-04T12:47:56.492254 #1-47212809183700]  INFO -- : Started GET "/" for ::ffff:172.18.0.10 at 2019-09-04 12:47:56 +0000
I, [2019-09-04T12:47:56.496682 #1-47212809183700]  INFO -- : Processing by InitController#index as HTML
I, [2019-09-04T12:47:56.502492 #1-47212809183700]  INFO -- :   Rendering init/index.html.erb within layouts/application
I, [2019-09-04T12:47:56.502687 #1-47212809183700]  INFO -- :   Rendered init/index.html.erb within layouts/application (0.1ms)
I, [2019-09-04T12:47:56.505571 #1-47212809183700]  INFO -- : Completed 200 OK in 9ms (Views: 1.6ms | ActiveRecord: 2.3ms)
I, [2019-09-04T12:47:58.711217 #1-47212809184180]  INFO -- : Started GET "/" for ::ffff:172.18.0.10 at 2019-09-04 12:47:58 +0000
I, [2019-09-04T12:47:58.714749 #1-47212809184180]  INFO -- : Processing by InitController#index as HTML
I, [2019-09-04T12:47:58.720752 #1-47212809184180]  INFO -- :   Rendering init/index.html.erb within layouts/application
I, [2019-09-04T12:47:58.721047 #1-47212809184180]  INFO -- :   Rendered init/index.html.erb within layouts/application (0.1ms)
I, [2019-09-04T12:47:58.723787 #1-47212809184180]  INFO -- : Completed 200 OK in 9ms (Views: 1.6ms | ActiveRecord: 2.5ms)
E, [2019-09-04T12:48:05.157428 #1-47212809184900] ERROR -- : Can't use Channel::Driver::Smtp: #<Net::OpenTimeout: execution expired>
E, [2019-09-04T12:48:05.157543 #1-47212809184900] ERROR -- : execution expired (Net::OpenTimeout)
/usr/local/lib/ruby/2.4.0/net/smtp.rb:539:in `initialize'
/usr/local/lib/ruby/2.4.0/net/smtp.rb:539:in `open'
/usr/local/lib/ruby/2.4.0/net/smtp.rb:539:in `tcp_socket'
/opt/zammad/lib/core_ext/net/smtp.rb:11:in `block in do_start'
/usr/local/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/opt/zammad/lib/core_ext/net/smtp.rb:10:in `do_start'
/usr/local/lib/ruby/2.4.0/net/smtp.rb:518:in `start'
/usr/local/bundle/bundler/gems/mail-9265cf75bbe3/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
/usr/local/bundle/bundler/gems/mail-9265cf75bbe3/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
/usr/local/bundle/bundler/gems/mail-9265cf75bbe3/lib/mail/message.rb:2159:in `do_delivery'
/usr/local/bundle/bundler/gems/mail-9265cf75bbe3/lib/mail/message.rb:262:in `deliver'
/opt/zammad/app/models/channel/driver/smtp.rb:85:in `send'
/opt/zammad/app/models/channel.rb:257:in `deliver'
/opt/zammad/lib/notification_factory/mailer.rb:136:in `send'
/opt/zammad/lib/notification_factory/mailer.rb:189:in `notification'
/opt/zammad/app/controllers/users_controller.rb:602:in `password_reset_send'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
/usr/local/bundle/gems/actionpack-5.1.7/lib/abstract_controller/base.rb:186:in `process_action'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_controller/metal/rendering.rb:30:in `process_action'
/usr/local/bundle/gems/actionpack-5.1.7/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:131:in `run_callbacks'
/usr/local/bundle/gems/actionpack-5.1.7/lib/abstract_controller/callbacks.rb:19:in `process_action'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_controller/metal/rescue.rb:20:in `process_action'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/notifications.rb:166:in `block in instrument'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
/usr/local/bundle/gems/actionpack-5.1.7/lib/abstract_controller/base.rb:124:in `process'
/usr/local/bundle/gems/actionview-5.1.7/lib/action_view/rendering.rb:30:in `process'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_controller/metal.rb:189:in `dispatch'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_controller/metal.rb:253:in `dispatch'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:31:in `serve'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:33:in `each'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:33:in `serve'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:844:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/builder.rb:64:in `call'
/usr/local/bundle/gems/rack-2.0.7/lib/rack/etag.rb:25:in `call'
/usr/local/bundle/gems/rack-2.0.7/lib/rack/conditional_get.rb:38:in `call'
/usr/local/bundle/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
/usr/local/bundle/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232:in `context'
/usr/local/bundle/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226:in `call'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/cookies.rb:613:in `call'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:97:in `run_callbacks'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:36:in `call_app'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:26:in `call'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
/usr/local/bundle/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
/usr/local/bundle/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
/usr/local/bundle/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
/usr/local/bundle/gems/puma-3.12.1/lib/puma/configuration.rb:227:in `call'
/usr/local/bundle/gems/puma-3.12.1/lib/puma/server.rb:660:in `handle_request'
/usr/local/bundle/gems/puma-3.12.1/lib/puma/server.rb:474:in `process_client'
/usr/local/bundle/gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'
/usr/local/bundle/gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
/usr/local/bundle/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
E, [2019-09-04T12:48:05.167419 #1-47212809184900] ERROR -- : Can't use Channel::Driver::Smtp: #<Net::OpenTimeout: execution expired> (RuntimeError)
/opt/zammad/app/models/channel.rb:268:in `rescue in deliver'
/opt/zammad/app/models/channel.rb:254:in `deliver'
/opt/zammad/lib/notification_factory/mailer.rb:136:in `send'
/opt/zammad/lib/notification_factory/mailer.rb:189:in `notification'
/opt/zammad/app/controllers/users_controller.rb:602:in `password_reset_send'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
/usr/local/bundle/gems/actionpack-5.1.7/lib/abstract_controller/base.rb:186:in `process_action'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_controller/metal/rendering.rb:30:in `process_action'
/usr/local/bundle/gems/actionpack-5.1.7/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:131:in `run_callbacks'
/usr/local/bundle/gems/actionpack-5.1.7/lib/abstract_controller/callbacks.rb:19:in `process_action'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_controller/metal/rescue.rb:20:in `process_action'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/notifications.rb:166:in `block in instrument'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
/usr/local/bundle/gems/actionpack-5.1.7/lib/abstract_controller/base.rb:124:in `process'
/usr/local/bundle/gems/actionview-5.1.7/lib/action_view/rendering.rb:30:in `process'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_controller/metal.rb:189:in `dispatch'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_controller/metal.rb:253:in `dispatch'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:31:in `serve'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:33:in `each'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:33:in `serve'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:844:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/builder.rb:64:in `call'
/usr/local/bundle/gems/rack-2.0.7/lib/rack/etag.rb:25:in `call'
/usr/local/bundle/gems/rack-2.0.7/lib/rack/conditional_get.rb:38:in `call'
/usr/local/bundle/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
/usr/local/bundle/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232:in `context'
/usr/local/bundle/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226:in `call'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/cookies.rb:613:in `call'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:97:in `run_callbacks'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:36:in `call_app'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:26:in `call'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
/usr/local/bundle/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
/usr/local/bundle/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
/usr/local/bundle/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
/usr/local/bundle/gems/puma-3.12.1/lib/puma/configuration.rb:227:in `call'
/usr/local/bundle/gems/puma-3.12.1/lib/puma/server.rb:660:in `handle_request'
/usr/local/bundle/gems/puma-3.12.1/lib/puma/server.rb:474:in `process_client'
/usr/local/bundle/gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'
/usr/local/bundle/gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
/usr/local/bundle/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
I, [2019-09-04T12:48:05.169274 #1-47212809184900]  INFO -- : Completed 500 Internal Server Error in 30035ms (Views: 0.3ms | ActiveRecord: 6.5ms)
I, [2019-09-04T12:48:24.184805 #1-47212809182980]  INFO -- : Started GET "/" for ::ffff:172.18.0.10 at 2019-09-04 12:48:24 +0000
I, [2019-09-04T12:48:24.192331 #1-47212809182980]  INFO -- : Processing by InitController#index as HTML
I, [2019-09-04T12:48:24.198706 #1-47212809182980]  INFO -- :   Rendering init/index.html.erb within layouts/application
I, [2019-09-04T12:48:24.198990 #1-47212809182980]  INFO -- :   Rendered init/index.html.erb within layouts/application (0.1ms)
I, [2019-09-04T12:48:24.201967 #1-47212809182980]  INFO -- : Completed 200 OK in 9ms (Views: 2.0ms | ActiveRecord: 3.5ms)
I, [2019-09-04T12:48:26.518367 #1-47212809184220]  INFO -- : Started GET "/" for ::ffff:172.18.0.10 at 2019-09-04 12:48:26 +0000
I, [2019-09-04T12:48:26.522144 #1-47212809184220]  INFO -- : Processing by InitController#index as HTML
I, [2019-09-04T12:48:26.527680 #1-47212809184220]  INFO -- :   Rendering init/index.html.erb within layouts/application
I, [2019-09-04T12:48:26.527934 #1-47212809184220]  INFO -- :   Rendered init/index.html.erb within layouts/application (0.1ms)
I, [2019-09-04T12:48:26.530743 #1-47212809184220]  INFO -- : Completed 200 OK in 8ms (Views: 1.6ms | ActiveRecord: 2.5ms)
I, [2019-09-04T12:48:28.211324 #1-47212809183700]  INFO -- : Started GET "/api/v1/tickets/94?all=true&_=1567581823480" for ::ffff:172.18.0.10 at 2019-09-04 12:48:28 +0000
I, [2019-09-04T12:48:28.212155 #1-47212809182980]  INFO -- : Started GET "/api/v1/tickets/50?all=true&_=1567581823482" for ::ffff:172.18.0.10 at 2019-09-04 12:48:28 +0000
I, [2019-09-04T12:48:28.212425 #1-47212809184180]  INFO -- : Started GET "/api/v1/cti/log?_=1567581823481" for ::ffff:172.18.0.10 at 2019-09-04 12:48:28 +0000
I, [2019-09-04T12:48:28.213219 #1-47212809184900]  INFO -- : Started GET "/api/v1/tickets/89?all=true&_=1567581823483" for ::ffff:172.18.0.10 at 2019-09-04 12:48:28 +0000
I, [2019-09-04T12:48:28.227585 #1-47212809183700]  INFO -- : Processing by TicketsController#show as JSON
I, [2019-09-04T12:48:28.233974 #1-47212809183700]  INFO -- :   Parameters: {"all"=>"true", "_"=>"1567581823480", "id"=>"94"}
I, [2019-09-04T12:48:28.233825 #1-47212809182980]  INFO -- : Processing by TicketsController#show as JSON
I, [2019-09-04T12:48:28.239541 #1-47212809182980]  INFO -- :   Parameters: {"all"=>"true", "_"=>"1567581823482", "id"=>"50"}
I, [2019-09-04T12:48:28.236456 #1-47212809184900]  INFO -- : Processing by TicketsController#show as JSON
I, [2019-09-04T12:48:28.241273 #1-47212809184900]  INFO -- :   Parameters: {"all"=>"true", "_"=>"1567581823483", "id"=>"89"}
I, [2019-09-04T12:48:28.230687 #1-47212809184180]  INFO -- : Processing by CtiController#index as JSON
I, [2019-09-04T12:48:28.245459 #1-47212809184180]  INFO -- :   Parameters: {"_"=>"1567581823481"}
I, [2019-09-04T12:48:28.271776 #1-47212809182980]  INFO -- : Enqueued UserDeviceLogJob (Job ID: 541f152b-e580-4900-b5ae-45bceb09e3a7) to DelayedJob(default) with arguments: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36", "172.31.4.130", 3, "86538853", "session"
I, [2019-09-04T12:48:28.280930 #1-47212809183700]  INFO -- : Enqueued UserDeviceLogJob (Job ID: c337d357-5410-4721-8e2c-125c0c6977a9) to DelayedJob(default) with arguments: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36", "172.31.4.130", 3, "86538853", "session"
I, [2019-09-04T12:48:28.284312 #1-47212809184900]  INFO -- : Enqueued UserDeviceLogJob (Job ID: 7d355c29-3

**Comment by MrGeneration** [comment]
Please don't recycle issues for different topics.
I'm missing context here and would be quite happy that if this is about technical assistance, that we'd switch to the community :)

**Comment by monotek** [comment]
There are no logfiles as it's logged to stdout. Check docker compose logs...
