### ISSUE TITLE
Postgre Password

### ISSUE THREAD

**Issue by wodka** [zammad/zammad-docker-compose#117]
Error in https://github.com/zammad/zammad-docker-compose/blob/master/containers/zammad/docker-entrypoint.sh#L47

`sed: -e expression #2, char 39: unknown option to `s'`

Ideally it should allow arbitrary passwords -> good note would be to inform what chars can be used so the sed command still works

### Infos:

* Docker version: ?
* Docker-compose version: ?
* Operating system (Docker host): ECS

(not related to docker, but the docker-entrypoint file)

### Expected behavior:

* Accept "#" as special char for passwords

### Actual behavior:

* `sed: -e expression #2, char 39: unknown option to `s'`

### Steps to reproduce the behavior:

* setup a different password for postgre and use "#" within it

**Comment by mr2chethan** [comment]
@wodka I am facing this same issue now. Was this resolved?
