### ISSUE TITLE
How to disable elasticsearch service?

### ISSUE THREAD

**Issue by xkvnn** [zammad/zammad-docker-compose#119]
I'd like to run without Elasticsearch service. How to disable it?

I tried manual remove zammad-elasticsearch service in docker-compose.yml but zammad-init still waiting for ES online.

**Comment by MrGeneration** [comment]
Sorry but this is rather a technical question, please consult the Zammad Community for this: https://community.zammad.org

Please also use the technical assistance template to provide further information, because the above will be not enough.

**Comment by monotek** [comment]
There is no way to disable it in docker compose installations.
