### ISSUE TITLE
CSRF Token error on login since upgrading to 3.2

### ISSUE THREAD

**Issue by Braintelligence** [zammad/zammad-docker-compose#120]
### Infos:

* Docker version: 18.09.6
* Docker-compose version: 1.24.0
* Operating system (Docker host): Ubuntu 

### Expected behavior:

* Login works

### Actual behavior:

* CSRF Token error on login

### Steps to reproduce the behavior:

* Upgrade 3.1 to 3.2 by docker-compose pull and try to login

Basically I need to change the nginx config like this: https://community.zammad.org/t/fresh-install-3-2-x-csrf-token-verification-failed/3080/22

But changes aren't persistent in the container and restarting nginx restarts the whole container.

Please give advice on how to change the nginx config to make login work again.

**Comment by thorsteneckel** [comment]
Hey there @Braintelligence - I talked to @monotek and we suggest having a custom container is the proper way to use docker-compose in a custom setup (behind other services that terminate SSL).

**Comment by Braintelligence** [comment]
This is unfortunate. Thanks for responding.

**Comment by waja** [comment]
Could we please implement something like mentioned in https://community.zammad.org/t/fresh-install-3-2-x-csrf-token-verification-failed/3080/32 in the stock nginx container?!?

**Comment by MrGeneration** [comment]
Please see thorstens statement above.
(This is a no :x)

**Comment by waja** [comment]
> Please see thorstens statement above.

@MrGeneration as I might understand to reject changes that might include any potential harm, applying the patch from https://github.com/zammad/zammad/pull/2863 doesn't look like it has any potential do harm anything. But it has the potential to make users happy.

Since it is in general supported to run an own proxy before the nginx system (see https://github.com/zammad/zammad-docker-compose/commit/334f605bdea98d5abaff1815414a8048ef20cab1#diff-f772bd5403017e9075de6e9455c26521) I don't understand why this should be dropped because of this issue.

**Comment by thorsteneckel** [comment]
At the time of writing I wasn't aware of a potential solution that covers this issue here as well. We still need to verify https://github.com/zammad/zammad/pull/2863. However, if it works as expected we can merge it and because [the config will be automatically included on the next build](https://github.com/zammad/zammad-docker-compose/blob/789eb2cc4bdb3fdcbcab1ecbe83e5b81977addbc/containers/zammad/docker-entrypoint.sh#L120) it should also cover this issue.

**Comment by waja** [comment]
Anyway ... looking into `/docker-entrypoint.sh`:
```
  # configure nginx
  if ! env | grep -q KUBERNETES; then
    sed -e "s#server .*:3000#server ${ZAMMAD_RAILSSERVER_HOST}:${ZAMMAD_RAILSSERVER_PORT}#g" -e "s#server .*:6042#server ${ZAMMAD_WEBSOCKET_HOST}:${ZAMMAD_WEBSOCKET_PORT}#g" -e "s#server_name .*#server_name ${NGINX_SERVER_NAME};#g" -e 's#/var/log/nginx/zammad.\(access\|error\).log#/dev/stdout#g' < contrib/nginx/zammad.conf > /etc/nginx/sites-enabled/default
  fi
```
It seems when https://github.com/zammad/zammad/pull/2863 gets merged we will see those changes integrated here.

So can anybody please open the ticket again and mark it as fixed when the hcange is integrated?

**Comment by waja** [comment]
@thorsteneckel thanks!

**Comment by Braintelligence** [comment]
@thorsteneckel so to sum things up: First it was "works as expected, do a custom container if you need to cater to custom setups" and now it's a U-turn into "I wasn't aware of a potential solution..." which means you finally recognize this as an actual issue that is not related to "custom setups" after all? (Because you certainly didn't do that here: https://community.zammad.org/t/fresh-install-3-2-x-csrf-token-verification-failed/3080/29 )

What does "...potential solution that covers this issue here as well..." even mean? It's a solution that covers *this very issue and nothing else*. Please be frank enough to use a wording that doesn't conceal how this actual issue was treated as a "technical webserver question" (https://github.com/zammad/zammad/issues/2829 ). I'm very, very thankful that @lr1980 didn't give up after being treated like that and instead created a PR fixing this. I'm 100% behind "this is a bug, not a technical question" - and I think @lr1980 deserves an apology.

I must say this is not the first time that actual issues were disposed of as a type of "custom config - not our issue" thing or maintainers even being condescending (either via wording or via incorrect categorizing and treatment of the issue) to issue creators. I sincerely hope this will change for the better in the future.

**Comment by waja** [comment]
@Braintelligence how about calming down a bit?

**Comment by monotek** [comment]
@Braintelligence maybe you should start using some of the stuff from your username, and fix it by yourself and provide an pr.

This is a community driven open source project. Stop acting like you paid for something and been pulled over the barrel. 

I've just lost interest in helping out here... 
Bye...

**Comment by Braintelligence** [comment]
Thanks for being condescending without actually touching any of my points. A PR was already introduced and looks like will take effect automatically due to https://github.com/zammad/zammad-docker-compose/issues/120#issuecomment-566558603 - there's no need for action other than reviewing and merging.

Being a community driven open source project doesn't justify treating people like you sometimes do; reporting issues is trying to help this community, not demand solutions on the spot. That's why I just backed off after you decided to brand this as a "custom setup" problem without any fuss. 
Seeing how others also realized that this can't be just a "technical question" and how it needed several persons and a working PR to make you even recognize this as an actual bug is just disrespectful towards the community, which made me come back to this with my comment. If you want to imply I'm stupid for calling you out on this: Sure, go ahead.

Since you don't seem to have read the issue history, implying that a PR in this repo would be absolute necessary, I'd in turn recommend to you to not flail the "you're not a paying customer" sign around when people are actually just trying to help. Help is not exclusively equal to a PR or measured by that.

And if you want or at least welcome help (or want to look like you do), you shouldn't go ad hominem on or dismiss those that try to do that like how it happened to people like @lr1980
Respect and seriousness (not a service level agreement, just a serious look at what's communicated) towards issues and community members isn't something where being a paid customer or not should be relevant.

It **does** have an effect on potential paying customers though, if they see such treatment.

Take this to heart or don't; I won't dwell on this topic anymore. Just don't be condescending on an open platform without any substance to it. This is just plain rude.

**Comment by monotek** [comment]
I don't see any PRs regarding to the docker compose repo linked to this issue. 

If you want to call it stupid to insinuate, that i'm waving the "not a paying customer sign", even though im just a community member without any financial connections to Zammad, i'm totally ok with that.

**Comment by pitah81** [comment]
Temporary solution is to replace the zammad.conf in the docker container, which I did by adding this to the docker nginx container:

`    volumes:
      - ./custom/zammad.conf:/opt/zammad/contrib/nginx/zammad.conf`

And then I put this in the ./custom/zammad.conf file

`#
# this is the nginx config for zammad
#

upstream zammad-railsserver {
    server zammad-railsserver:3000;
}

upstream zammad-websocket {
    server zammad-websocket:6042;
}

server {
    listen 80;

    # replace 'localhost' with your fqdn if you want to use zammad from remote
    server_name _;

    root /opt/zammad/public;

    access_log /dev/stdout;
    error_log  /dev/stdout;

    client_max_body_size 50M;

    location ~ ^/(assets/|robots.txt|humans.txt|favicon.ico) {
        expires max;
    }

    location /ws {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header CLIENT_IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 86400;
        proxy_pass http://zammad-websocket;
    }

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header CLIENT_IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 300;
        proxy_pass http://zammad-railsserver;

        gzip on;
        gzip_types text/plain text/xml text/css image/svg+xml application/javascript application/x-javascript application/json application/xml;
        gzip_proxied any;
    }
}
`
Login working fine after this, even Office 365 login and probably all the other types of authentications. Also my Zammad instance is behind a Traefik 2.0 proxy.

**Comment by waja** [comment]
I used the following as `./custom/zammad.conf` (copied the actual one with `docker cp`) and added changes from https://github.com/zammad/zammad/pull/2863, but slightly different, cause `map` is not allowed in `server` context:

```
#
# this is the nginx config for zammad
#

upstream zammad-railsserver {
    server zammad-railsserver:3000;
}

upstream zammad-websocket {
    server zammad-websocket:6042;
}

map $http_x_forwarded_proto $real_scheme {
    default $http_x_forwarded_proto;
    '' $scheme;
}

server {
    listen 80;

    # replace 'localhost' with your fqdn if you want to use zammad from remote
    server_name _;

    root /opt/zammad/public;

    access_log /dev/stdout;
    error_log  /dev/stdout;

    client_max_body_size 50M;

    location ~ ^/(assets/|robots.txt|humans.txt|favicon.ico) {
        expires max;
    }

    location /ws {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header CLIENT_IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $real_scheme;
        proxy_read_timeout 86400;
        proxy_pass http://zammad-websocket;
    }

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header CLIENT_IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $real_scheme;
        proxy_read_timeout 300;
        proxy_pass http://zammad-railsserver;

        gzip on;
        gzip_types text/plain text/xml text/css image/svg+xml application/javascript application/x-javascript application/json application/xml;
        gzip_proxied any;
    }
}
```

It works very well. :)

**Comment by benbucksch** [comment]
@pitah81 , thanks so much!

I've been tearing my hairs all day and all night long about this. All documentation that I found on community.zammad.org and elsewhere blamed the HTTP reverse proxy in front of Zammad. That's why I was trying all day long to fix it there. I tried all the recommended nginx reverse proxy config changes in my nginx. I even changed the reverse proxy completely from nginx to traefik, without success. These attempts took me all day and all night. It's days like these where I hate my job.

Lastly, with @pitah81 config file, it works. So, the bug is in fact in the nginx config of zammad-docker-compose nginx container here and not in the HTTP reverse proxies in front of it.

IP addresses are scarce, so having a HTTP router that terminates TLS connections and forwards them to another HTTP server in a docker container is the normal configuration these days. This bug appears to hit such users hard.

@monotek : Could you please merge the fix that was posted here by @pitah81 last year?

**Comment by monotek** [comment]
closed via: https://github.com/zammad/zammad-docker-compose/pull/166
