### ISSUE TITLE
Unable to recompile assets, yarn missing

### ISSUE THREAD

**Issue by pitah81** [zammad/zammad-docker-compose#122]
### Infos:

* Docker version: 19.03.4
* Docker-compose version: 1.25.0
* Operating system (Docker host): Ubuntu 18.04

### Expected behavior:

Run following command in the zammad-rails container to recompile assets after making changes to certain asset files, in my case adding a new language to the chat module

rake assets:precompile

### Actual behavior:

rake assets:precompile
I, [2019-12-18T11:08:00.046424 #128-47355370579380]  INFO -- : Setting.set('models_searchable', ["User", "Ticket", "Organization", "KnowledgeBase::Answer::Translation", "Chat::Session"])
Yarn executable was not detected in the system.
Download Yarn at https://yarnpkg.com/en/docs/install

### Steps to reproduce the behavior:

Simply run rake assets:precompile

**Comment by MrGeneration** [comment]
Does the precompile itself work?
Normally the Yarn message is just a warning that you can ignore.

I just want to make sure nothing broke when you run the command. :-)

**Comment by monotek** [comment]
This happens because we're using the the docker builder pattern in the dockerfile. 

See the 2 occurences of "From" in the dockerfile: https://github.com/zammad/zammad-docker-compose/blob/master/containers/zammad/Dockerfile

As docker containers should be imutable this is wanted behavior. Best practice would be to build a new dockerfile with the changes you want.

**Comment by thorsteneckel** [comment]
Hi @pitah81 - JFI: I'll merge your [Swedish chat translation PR](https://github.com/zammad/zammad/pull/2869) later today.

**Comment by pitah81** [comment]
Error on my side

**Comment by renatocron** [comment]
> This happens because we're using the the docker builder pattern in the dockerfile.
> 
> See the 2 occurences of "From" in the dockerfile: https://github.com/zammad/zammad-docker-compose/blob/master/containers/zammad/Dockerfile
> 
> As docker containers should be imutable this is wanted behavior. Best practice would be to build a new docker image with the changes you want.
> 
> If you want to try out or develop things you can use the single docker image. There are all build dependencies included. But be aware that this image is using the develop branch:
> 
> https://github.com/zammad/zammad-docker

Should we instead just fork and recompile the entire docker rails image each time to change just one custom css?

**Comment by monotek** [comment]
> As docker containers should be imutable this is wanted behavior. Best practice would be to build a new docker image with the changes you want.
