### ISSUE TITLE
Missing js and css files - unable to access zammad frontend

### ISSUE THREAD

**Issue by tr0tzki** [zammad/zammad-docker-compose#124]
Hi there, just deployed a clean set of the zammad docker compose images. Zammad starts, everything is fine, unfortunately some css and files re missing, so I cannot access the zammad frontend.

### Infos:

* Docker version: 19.03.5
* Docker-compose version: 1.24.1
* Operating system (Docker host): Debian Buster

### Expected behavior:

* Can access Zammad frontend

### Actual behavior:

* Get a nearly blank page (Loading... and Zammad icon appears).

### Steps to reproduce the behavior:

* cd .. zammad-docker-compose && docker-compose run -d

Log of Nginx Container:
`172.27.1.4 - - [13/Feb/2020:14:56:38 +0000] "GET / HTTP/1.1" 200 1107 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
2020/02/13 14:56:38 [error] 58#58: *9 open() "/opt/zammad/public/assets/application-59171ef0a16cd6e380401afe462bcf98ec981dd77ee00243ba6cbeae85580001.css" failed (2: No su
ch file or directory), client: 172.27.1.4, server: my.server.lan, request: "GET /assets/application-59171ef0a16cd6e380401afe462bcf98ec981dd77ee00243ba6cbeae85
580001.css HTTP/1.1", host: "my.server.lan", referrer: "https://my.server.lan/"
172.27.1.4 - - [13/Feb/2020:14:56:38 +0000] "GET /assets/application-59171ef0a16cd6e380401afe462bcf98ec981dd77ee00243ba6cbeae85580001.css HTTP/1.1" 404 143 "https://sv008
.extranet.sese-it.de/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
2020/02/13 14:56:38 [error] 58#58: *9 open() "/opt/zammad/public/assets/application-8687fb6639291d39f3759568043655d9118613dfd13366e0d41a92f30672112d.js" failed (2: No suc
h file or directory), client: 172.27.1.4, server: my.server.lan, request: "GET /assets/application-8687fb6639291d39f3759568043655d9118613dfd13366e0d41a92f3067
2112d.js HTTP/1.1", host: "my.server.lan", referrer: "https://my.server.lan/"
172.27.1.4 - - [13/Feb/2020:14:56:38 +0000] "GET /assets/application-8687fb6639291d39f3759568043655d9118613dfd13366e0d41a92f30672112d.js HTTP/1.1" 404 143 "https://sv008.
extranet.sese-it.de/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
2020/02/13 14:56:38 [error] 58#58: *9 open() "/opt/zammad/public/assets/application-print-db172409c8422225ac73dfd79ca9fe0994704e3813ebdd759e19cc0e3b0eff6a.css" failed (2:
 No such file or directory), client: 172.27.1.4, server: my.server.lan, request: "GET /assets/application-print-db172409c8422225ac73dfd79ca9fe0994704e3813ebdd
759e19cc0e3b0eff6a.css HTTP/1.1", host: "my.server.lan", referrer: "https://my.server.lan/"
172.27.1.4 - - [13/Feb/2020:14:56:38 +0000] "GET /assets/application-print-db172409c8422225ac73dfd79ca9fe0994704e3813ebdd759e19cc0e3b0eff6a.css HTTP/1.1" 404 143 "https:/
/my.server.lan/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
172.27.1.4 - - [13/Feb/2020:14:56:38 +0000] "GET /assets/images/icons.svg HTTP/1.1" 304 0 "https://my.server.lan/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64;
rv:71.0) Gecko/201`

**Comment by MrGeneration** [comment]
Did you pull the original docker-compose containers from us or did you fiddle your own?

**Comment by tr0tzki** [comment]
Yes, I pulled the original docker compose containers. It worked just fine for quite a long time till I pulled the current images. I started from the scratch but still the same issue. I checked my backups and also cannot find the missing css and js files. How can I create those files? I also ran `rake assets:precompile` in the railsserver container without any success.

docker-compose.yml:
`version: '3.7'
services:

  traefik:
    image: traefik:1.7-alpine
    command: --docker=true --docker.watch=true
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    labels:
      - "traefik.enable=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # So that Traefik can listen to the Docker events
      - /srv/docker/services/web-services/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /srv/docker/services/web-services/traefik/certs:/certs
    networks:
      - frontend
      - zammad-backend
      - nextcloud-backend

  zammad-backup:
    command: ["zammad-backup"]
    depends_on:
      - zammad-railsserver
    entrypoint: /usr/local/bin/backup.sh
    image: ${ZAMMAD_IMAGE_REPO}:zammad-postgresql${ZAMMAD_VERSION}
    links:
      - zammad-postgresql
    restart: ${RESTART}
    volumes:
      - zammad-backup:/var/tmp/zammad
      - zammad-data:/opt/zammad
    labels:
      - "traefik.enable=false"
    networks:
      - zammad-backend

  zammad-elasticsearch:
    image: ${ZAMMAD_IMAGE_REPO}:zammad-elasticsearch${ZAMMAD_VERSION}
    restart: ${RESTART}
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    labels:
      - "traefik.enable=false"
    networks:
      - zammad-backend

  zammad-init:
    command: ["zammad-init"]
    depends_on:
      - zammad-postgresql
    image: ${ZAMMAD_IMAGE_REPO}:zammad${ZAMMAD_VERSION}
    links:
      - zammad-elasticsearch
      - zammad-postgresql
    restart: on-failure
    volumes:
      - zammad-data:/opt/zammad
    labels:
      - "traefik.enable=false"
    networks:
      - zammad-backend

  zammad-memcached:
    command: ["zammad-memcached"]
    image: ${ZAMMAD_IMAGE_REPO}:zammad-memcached${ZAMMAD_VERSION}
    restart: ${RESTART}
    labels:
      - "traefik.enable=false"
    networks:
      - zammad-backend

  zammad-nginx:
    command: ["zammad-nginx"]
    depends_on:
      - zammad-railsserver
    image: ${ZAMMAD_IMAGE_REPO}:zammad${ZAMMAD_VERSION}
    links:
      - zammad-railsserver
      - zammad-websocket
    restart: ${RESTART}
    volumes:
      - zammad-data:/opt/zammad
    expose:
      - "80"
    environment:
      - NGINX_SERVER_NAME=my.server.aln
    labels:
      - "traefik.backend=manager.zammad"
      - "traefik.backend.loadbalancer.stickiness=true"
      - "traefik.frontend.rule=Host:my.server.lan"
      - "traefik.docker.network=zammad_frontend"
      - "traefik.port=80"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.enable=true"
    networks:
      - zammad-backend

  zammad-postgresql:
    image: ${ZAMMAD_IMAGE_REPO}:zammad-postgresql${ZAMMAD_VERSION}
    restart: ${RESTART}
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"
    networks:
      - zammad-backend

  zammad-railsserver:
    command: ["zammad-railsserver"]
    depends_on:
      - zammad-memcached
      - zammad-postgresql
    image: ${ZAMMAD_IMAGE_REPO}:zammad-railsserver${ZAMMAD_VERSION}
    links:
      - zammad-elasticsearch
      - zammad-memcached
      - zammad-postgresql
    restart: ${RESTART}
    volumes:
      - zammad-data:/opt/zammad
    labels:
      - "traefik.enable=false"
    networks:
      - zammad-backend

  zammad-scheduler:
    command: ["zammad-scheduler"]
    depends_on:
      - zammad-memcached
      - zammad-railsserver
    image: ${ZAMMAD_IMAGE_REPO}:zammad${ZAMMAD_VERSION}
    links:
      - zammad-elasticsearch
      - zammad-memcached
      - zammad-postgresql
    restart: ${RESTART}
    volumes:
      - zammad-data:/opt/zammad
    labels:
      - "traefik.enable=false"
    networks:
      - zammad-backend

  zammad-websocket:
    command: ["zammad-websocket"]
    depends_on:
      - zammad-memcached
      - zammad-railsserver
    image: ${ZAMMAD_IMAGE_REPO}:zammad${ZAMMAD_VERSION}
    links:
      - zammad-postgresql
      - zammad-memcached
    restart: ${RESTART}
    volumes:
      - zammad-data:/opt/zammad
    labels:
      - "traefik.enable=false"
    networks:
      - zammad-backend

 networks:
  frontend:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/24
  zammad-backend:
    ipam:
      driver: default
      config:
        - subnet: 172.27.1.0/24

volumes:
  elasticsearch-data:
    driver: local
  postgresql-data:
    driver: local
  zammad-backup:
    driver: local
  zammad-data:
    driver: local
`

.env:
`ZAMMAD_IMAGE_REPO=zammad/zammad-docker-compose
ZAMMAD_VERSION=

**Comment by tr0tzki** [comment]
I just found this in the railsserver logs:
`2020-02-13 20:00:58 +0000: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>`

**Comment by tr0tzki** [comment]
any idea? still got lost with rails

**Comment by abeluck** [comment]
Ensure you are not running into cache issues. Local caches such as your browser. Or perhaps remote caches such as a CDN or Cloudflare.

**Comment by tr0tzki** [comment]
No, I flushed any cahes, uses different browsers.
The thing is, something is reverting my changes to rails files e.g. producion.rb. I changed some settings but when I restart the containers everything is back to zero. That is strange as the volumes should persist...

**Comment by MrGeneration** [comment]
Changes to source code files are **not persistent** and that's totally fine by default.
More importantly your settings within the database and storage files (e.g. attachments) are still there after creating stuff.

Please don't fiddle around manually within the code. If you want to do that, the source code version might be the better way for you.

Also, this is a technical question - the better place for technical questions is the Zammad Community: https://community.zammad.org

Also, please keep in mind that this is a Open Source project - we can't always jump within minutes or hours. Please be patient...


Closing now.

**Comment by tr0tzki** [comment]
there must be either a huge misunderstanding here or u just got me totally wrong (hopefully)... u re using docker volumes as a temp directories but it's supposed to be persistent storage. I don't want to have my changes reverted on /opt/zammad/. Changes on ruby configuration were necessary(!) since the current railsserver configuration broke the railsserver container (and some dependencies that comes with it). IMHO the concept of Containerization and CD (as well as Docker) is misunderstood in this project. U re pulling all the rails sources (and dependancies) from the git straight after the railsserver container came up. Then u overwrite my configuration (just to remember, the fixes that fix the rails mess - see above) So, I cannot go back to any version of the railsserver container. Tags re useless as well as backups of volumes (needless to ask, what are image tags for?....). The only thing that is left is 'docker export' and prevent the container from getting to the internet...
Thanks for all the great work u re doing on Zammad but Containerization is not the right concept for this project (zammad-docker-compose) when u do it in this way...

**Comment by monotek** [comment]
We don't use docker volumes as temp directories. 

How do you expect an Zammad update to work? 
We have to overwrite the files, to do that.
To be specific we're doing this here: 
https://github.com/zammad/zammad-docker-compose/blob/master/containers/zammad/docker-entrypoint.sh#L36-L37

If you try to change something in a containerised apllication you're doing it wrong.
See: https://cloud.google.com/solutions/best-practices-for-operating-containers#ensure_that_your_containers_are_stateless_and_immutable

We're not pulling anything on container startup (see the link above, to understand why this would be wrong).
The container already contains all necessary files. See setup script of the image: 
https://github.com/zammad/zammad-docker-compose/blob/master/containers/zammad/setup.sh

Whatever your problem was in the first place, you made it worse with your changes.
