### ISSUE TITLE
Elasticsearch not upgradeable (5->7)

### ISSUE THREAD

**Issue by sscholl** [zammad/zammad-docker-compose#127]
Elasticsearch can not upgrade from 5->7 directly 

`org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: The index [[zammad_production/IEjkyU2BQQuuDPdnp3E_tg]] was created with version [5.6.5] but the minimum compatible version is [6.0.0-beta1]. It should be re-indexed in Elasticsearch 6.x before upgrading to 7.6.0.`

https://github.com/zammad/zammad-docker-compose/commit/a35b4fa29deb863e94f12f8a03abc8ab9ce83615#r37380256

### Expected behavior:
* elasticsearch upgrades automatically

### Actual behavior:
* elasticsearch is not upgrading from 5->7

### Steps to reproduce the behavior:
* use VERSION=-3.2.0-12
* start server
* use VERSION=
* restart server
* look in log

**Comment by MrGeneration** [comment]
Sorry but this is a technical question which Github -for us- is not the correct place.
Anyway - as stated on our documentation ( https://docs.zammad.org/en/latest/install/update.html#updating-elasticsearch ) you'll need to ensure to follow the upgrade path of elasticsearch.

This is a third party topic and no Zammad issue (neither a bug).

I'm therefore closing this issue.

**Comment by sscholl** [comment]
How do you think people use zammad-docker-compose?

**Comment by monotek** [comment]
Updates of ES major versions are hard and not in the scope of Zammad.

Deleting all Elasticserch indexes and rebuild the searchindex from within the rails container should fix the problem:

```
curl -XDELETE http://zammad-elasticsearch:9200/*
bundle exec rake searchindex:rebuild
```

**Comment by monotek** [comment]
I've added a possibility to purge the elasticsearch data so the reindexing mechanism will rebuild everything.

See: https://github.com/zammad/zammad-docker-compose/commit/3d2a73474f9f7cbcb7f045bf91be0f955115baf9

Just start docker-compose via:

```
docker-compose up -e ELASTICSEARCH_PURGE=true
```
