### ISSUE TITLE
zammad-docker-compose_zammad-postgresql_1 exited with code 1

### ISSUE THREAD

**Issue by techkid1995** [zammad/zammad-docker-compose#128]
### Infos:

* Docker version: 19.03.6
* Docker-compose version: 1.25.4 build 8d51620a
* Operating system (Docker host): Ubuntu

### Expected behavior:
postgresql container should start.

### Actual behavior:
zammad-backup_1         | waiting for railsserver to be ready...
zammad-elasticsearch_1  | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
zammad-init_1           | zammad railsserver waiting for postgresql server to be ready...
zammad-memcached_1      | starting memcached...
zammad-postgresql_1     | Error: Database is uninitialized and superuser password is not specified.
zammad-postgresql_1     |        You must specify POSTGRES_PASSWORD for the superuser. Use
zammad-postgresql_1     |        "-e POSTGRES_PASSWORD=password" to set it in "docker run".
zammad-postgresql_1     |
zammad-postgresql_1     |        You may also use POSTGRES_HOST_AUTH_METHOD=trust to allow all connections
zammad-postgresql_1     |        without a password. This is *not* recommended. See PostgreSQL
zammad-postgresql_1     |        documentation about "trust":
zammad-postgresql_1     |        https://www.postgresql.org/docs/current/auth-trust.html
zammad-railsserver_1    | waiting for init container to finish install or update...
zammad-init_1           | zammad railsserver waiting for postgresql server to be ready...
zammad-docker-compose_zammad-postgresql_1 exited with code 1

### Steps to reproduce the behavior:
run docker-compose up

**Comment by theweirdone** [comment]
Hi,

This issue is caused by an update to PostGres (as seen [here](https://github.com/docker-library/postgres/issues/681)). The fix is quite easy, add an environment variable to the docker-compose.yml file. 

zammad-postgresql:
    image: ${IMAGE_REPO}:zammad-postgresql${VERSION}
    **environment:
      - POSTGRES_HOST_AUTH_METHOD=trust**
    restart: ${RESTART}
    volumes:
      - postgresql-data:/var/lib/postgresql/data

**Comment by techkid1995** [comment]
Thanks! That fixed it.
