### ISSUE TITLE
zammad-init container won't start the init

### ISSUE THREAD

**Issue by alionar** [zammad/zammad-docker-compose#134]
### Infos:

* Docker version: 19.03.5, build 633a0ea
* Docker-compose version: 1.25.3, build d4d1b42b
* Operating system (Docker host): CentOS 8

### Expected behavior:

* Just want to run docker-compose from this repo, didn't edit anything.

### Actual behavior:

* zammad-init suddenly stopped
* can't access zammad from browser

### Steps to reproduce the behavior:

* Clone this repo
* Run `docker-compose up -d`
* zammad-init just stop

**Comment by alionar** [comment]
Log for each container when zammad-init stopped.

* Log lines in zammad-init container
```initialising / updating database...


changing settings...


I, [2020-02-26T03:23:17.800054 #20-47194198050240]  INFO -- : Setting.set('models_searchable', ["Chat::Session", "KnowledgeBase::Answer::Translation", "Ticket", "User", "Organization"])


I, [2020-02-26T03:23:18.931385 #20-47194198050240]  INFO -- : Setting.set('es_url', "http://zammad-elasticsearch:9200")```

* Log lines in zammad-elasticsearch container
```
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.


{"type": "server", "timestamp": "2020-02-26T03:22:50,898Z", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/sda1)]], net usable_space [20.3gb], net total_space [39.9gb], types [xfs]" }


{"type": "server", "timestamp": "2020-02-26T03:22:50,911Z", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "heap size [1007.3mb], compressed ordinary object pointers [true]" }


{"type": "server", "timestamp": "2020-02-26T03:22:51,348Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "node name [36c0ee3a9e58], node ID [rPjIfXAZT3ySsxPx9Cx0zQ], cluster name [docker-cluster]" }


{"type": "server", "timestamp": "2020-02-26T03:22:51,348Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "version[7.6.0], pid[1], build[default/docker/7f634e9f44834fbc12724506cc1da681b0c3b1e3/2020-02-06T00:09:00.449973Z], OS[Linux/4.18.0-80.11.2.el8_0.x86_64/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/13.0.2/13.0.2+8]" }


{"type": "server", "timestamp": "2020-02-26T03:22:51,349Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "JVM home [/usr/share/elasticsearch/jdk]" }


{"type": "server", "timestamp": "2020-02-26T03:22:51,350Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "JVM arguments [-Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=COMPAT, -Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Djava.io.tmpdir=/tmp/elasticsearch-157732018370830406, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Des.cgroups.hierarchy.override=/, -XX:MaxDirectMemorySize=536870912, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=docker, -Des.bundled_jdk=true]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,784Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [aggs-matrix-stats]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,784Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [analysis-common]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,785Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [flattened]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,785Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [frozen-indices]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,785Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [ingest-common]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,786Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [ingest-geoip]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,786Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [ingest-user-agent]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,786Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [lang-expression]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,786Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [lang-mustache]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,787Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [lang-painless]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,787Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [mapper-extras]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,787Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [parent-join]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,787Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [percolator]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,788Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [rank-eval]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,788Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [reindex]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,788Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [repository-url]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,788Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [search-business-rules]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,789Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [spatial]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,789Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [transform]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,789Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [transport-netty4]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,790Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [vectors]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,790Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [x-pack-analytics]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,790Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [x-pack-ccr]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,790Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [x-pack-core]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,791Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [x-pack-deprecation]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,791Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [x-pack-enrich]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,791Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [x-pack-graph]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,792Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [x-pack-ilm]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,792Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [x-pack-logstash]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,792Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [x-pack-ml]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,793Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [x-pack-monitoring]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,793Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [x-pack-rollup]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,794Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [x-pack-security]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,794Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [x-pack-sql]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,794Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [x-pack-voting-only-node]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,794Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded module [x-pack-watcher]" }


{"type": "server", "timestamp": "2020-02-26T03:22:56,795Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "loaded plugin [ingest-attachment]" }


{"type": "server", "timestamp": "2020-02-26T03:23:08,760Z", "level": "INFO", "component": "o.e.x.s.a.s.FileRolesStore", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "parsed [0] roles from file [/usr/share/elasticsearch/config/roles.yml]" }


{"type": "server", "timestamp": "2020-02-26T03:23:10,919Z", "level": "INFO", "component": "o.e.x.m.p.l.CppLogMessageHandler", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "[controller/110] [Main.cc@110] controller (64 bit): Version 7.6.0 (Build 1c8cca13fa9631) Copyright (c) 2020 Elasticsearch BV" }


{"type": "server", "timestamp": "2020-02-26T03:23:11,908Z", "level": "DEBUG", "component": "o.e.a.ActionModule", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "Using REST wrapper from plugin org.elasticsearch.xpack.security.Security" }


{"type": "server", "timestamp": "2020-02-26T03:23:12,127Z", "level": "INFO", "component": "o.e.d.DiscoveryModule", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "using discovery type [single-node] and seed hosts providers [settings]" }


{"type": "server", "timestamp": "2020-02-26T03:23:14,718Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "initialized" }


{"type": "server", "timestamp": "2020-02-26T03:23:14,718Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "starting ..." }


{"type": "server", "timestamp": "2020-02-26T03:23:15,204Z", "level": "INFO", "component": "o.e.t.TransportService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "publish_address {172.24.0.3:9300}, bound_addresses {0.0.0.0:9300}" }


{"type": "server", "timestamp": "2020-02-26T03:23:16,381Z", "level": "INFO", "component": "o.e.c.c.Coordinator", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "cluster UUID [1QkKUCFITNeBUzrJhlue4Q]" }


{"type": "server", "timestamp": "2020-02-26T03:23:16,622Z", "level": "INFO", "component": "o.e.c.s.MasterService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "elected-as-master ([1] nodes joined)[{36c0ee3a9e58}{rPjIfXAZT3ySsxPx9Cx0zQ}{63_somNXRcC4pASUtz6l1A}{172.24.0.3}{172.24.0.3:9300}{dilm}{ml.machine_memory=8192462848, xpack.installed=true, ml.max_open_jobs=20} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_], term: 3, version: 55, delta: master node changed {previous [], current [{36c0ee3a9e58}{rPjIfXAZT3ySsxPx9Cx0zQ}{63_somNXRcC4pASUtz6l1A}{172.24.0.3}{172.24.0.3:9300}{dilm}{ml.machine_memory=8192462848, xpack.installed=true, ml.max_open_jobs=20}]}" }


{"type": "server", "timestamp": "2020-02-26T03:23:16,907Z", "level": "INFO", "component": "o.e.c.s.ClusterApplierService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "master node changed {previous [], current [{36c0ee3a9e58}{rPjIfXAZT3ySsxPx9Cx0zQ}{63_somNXRcC4pASUtz6l1A}{172.24.0.3}{172.24.0.3:9300}{dilm}{ml.machine_memory=8192462848, xpack.installed=true, ml.max_open_jobs=20}]}, term: 3, version: 55, reason: Publication{term=3, version=55}" }


{"type": "server", "timestamp": "2020-02-26T03:23:17,130Z", "level": "INFO", "component": "o.e.h.AbstractHttpServerTransport", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "publish_address {172.24.0.3:9200}, bound_addresses {0.0.0.0:9200}", "cluster.uuid": "1QkKUCFITNeBUzrJhlue4Q", "node.id": "rPjIfXAZT3ySsxPx9Cx0zQ"  }


{"type": "server", "timestamp": "2020-02-26T03:23:17,130Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "started", "cluster.uuid": "1QkKUCFITNeBUzrJhlue4Q", "node.id": "rPjIfXAZT3ySsxPx9Cx0zQ"  }


{"type": "server", "timestamp": "2020-02-26T03:23:17,913Z", "level": "INFO", "component": "o.e.l.LicenseService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "license [193ab3b8-3ca4-47f8-b4b2-6af7f76db7a7] mode [basic] - valid", "cluster.uuid": "1QkKUCFITNeBUzrJhlue4Q", "node.id": "rPjIfXAZT3ySsxPx9Cx0zQ"  }


{"type": "server", "timestamp": "2020-02-26T03:23:17,915Z", "level": "INFO", "component": "o.e.x.s.s.SecurityStatusChangeListener", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "Active license is now [BASIC]; Security is disabled", "cluster.uuid": "1QkKUCFITNeBUzrJhlue4Q", "node.id": "rPjIfXAZT3ySsxPx9Cx0zQ"  }


{"type": "server", "timestamp": "2020-02-26T03:23:17,949Z", "level": "INFO", "component": "o.e.g.GatewayService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "recovered [9] indices into cluster_state", "cluster.uuid": "1QkKUCFITNeBUzrJhlue4Q", "node.id": "rPjIfXAZT3ySsxPx9Cx0zQ"  }


{"type": "server", "timestamp": "2020-02-26T03:23:26,842Z", "level": "INFO", "component": "o.e.m.j.JvmGcMonitorService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "[gc][12] overhead, spent [274ms] collecting in the last [1s]", "cluster.uuid": "1QkKUCFITNeBUzrJhlue4Q", "node.id": "rPjIfXAZT3ySsxPx9Cx0zQ"  }


{"type": "server", "timestamp": "2020-02-26T03:23:30,262Z", "level": "INFO", "component": "o.e.c.r.a.AllocationService", "cluster.name": "docker-cluster", "node.name": "36c0ee3a9e58", "message": "Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[zammad_production_chat_session][0]]]).", "cluster.uuid": "1QkKUCFITNeBUzrJhlue4Q", "node.id": "rPjIfXAZT3ySsxPx9Cx0zQ"  }
```

* Log lines in  zammad-railsserver
```
waiting for init container to finish install or update...


waiting for init container to finish install or update...


starting railsserver...


=> Booting Puma


=> Rails 5.2.4.1 application starting in production 


=> Run `rails server -h` for more startup options


2020-02-26 03:23:48 +0000: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>


---
```

**Comment by monotek** [comment]
zammad-init is a init container and is supposed to stop when its finished.

**Comment by alionar** [comment]
> seeing the railsserver come up is a very good indicator that everything works.

Oh i see, i thought that because `init` is initial step for zammad so it will run as long as zammad webserver still on going.

Thanks for your response.

**Comment by monotek** [comment]
what happens, when you access http://localhost ?

**Comment by alionar** [comment]
```
This site can’t be reached
xx.xx.xx.xx refused to connect.
```

**Comment by monotek** [comment]
and you're using localhost or the external ip of your system?

the container is not reachable from the outside. 
if you want this you have to use some kind of proxy...

**Comment by alionar** [comment]
external ip

**Comment by monotek** [comment]
So it can work. The container listens on localhost only.
