### ISSUE TITLE
Rancher Catalog Stack deploy failing: Expected state running but got error: Error response from daemon: manifest for zammad/zammad-docker-compose:postgresql not found

### ISSUE THREAD

**Issue by diegodorgam** [zammad/zammad-docker-compose#14]
### Infos:

* Docker version: 17.03.1-ce, build c6d412e
* Docker-compose version: using Rancher 1.4
* Operating system (Docker host): Debian 8

### Expected behavior:

* Trying to deploy Zammad from Rancher Catalog, using only version avaiable in catalog, 1.2, and expected to deploy smoothly, just like weeks ago. 

### Actual behavior:

* The Postgres, Nginx and ElasticSearch services containers give the same error: 

- Expected state running but got error: Error response from daemon: manifest for zammad/zammad-docker-compose:postgresql not found
- Expected state running but got error: Error response from daemon: manifest for zammad/zammad-docker-compose:nginx not found
- Expected state running but got error: Error response from daemon: manifest for zammad/zammad-docker-compose:elasticsearch not found

<img width="1265" alt="captura de tela 2017-04-04 as 19 46 31" src="https://cloud.githubusercontent.com/assets/12052193/24682554/aff9237a-1970-11e7-8cb6-4368b9d88507.png">
<img width="920" alt="captura de tela 2017-04-04 as 19 46 47" src="https://cloud.githubusercontent.com/assets/12052193/24682579/b96e52f4-1970-11e7-8597-6faab511f7be.png">

I've tried to insert my dockerhub user in Rancher registries, but got the same error.

Have anyone experienced this? I've tested the docker-compose in my local machine and worked fine.
Don't understand why it can't pull images. I've tried doing in it in command line:
```
root@rancher:/home/user# docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (user): 
Password: 
Login Succeeded
root@rancher:/home/user# docker pull zammad/zammad-docker-compose:elasticsearch
Error response from daemon: manifest for zammad/zammad-docker-compose:elasticsearch not found
```

any help i'd appreciate.
thks in advance.

**Comment by monotek** [comment]
The names of the image changed.
Update the git repo via git pull and it should work.

**Comment by diegodorgam** [comment]
Thks @monotek !

it worked, would never saw this...

images name changed from:
- `zammad/zammad-docker-compose:elasticsearch` to `zammad/zammad-docker-compose:zammad-elasticsearch`

- `zammad/zammad-docker-compose:nginx` to `zammad/zammad-docker-compose:zammad-nginx`

- `zammad/zammad-docker-compose:postgresql` to `zammad/zammad-docker-compose:zammad-postgresql`

just upgraded the image names in the rancher services and everything worked.

thanks for your help @monotek.

**Comment by diegodorgam** [comment]
btw: I've just sent a pull request to rancher's catalog repository to fix this...
https://github.com/rancher/community-catalog/pull/479
