### ISSUE TITLE
Zammad 3.2.1 release update on Dockerhub

### ISSUE THREAD

**Issue by NickMos** [zammad/zammad-docker-compose#140]
The question is about [Zammad 3.2.1 release ](https://zammad.com/news/release-3-3). Will it be uploaded to the [Dockerhub](https://hub.docker.com/r/zammad/zammad-docker-compose)?

https://hub.docker.com/r/zammad/zammad-docker-compose

I see that there is a 3.3.0 release, but what is about 3.2.1? We've just finished moving from 2.9 to 3.1 and it took much time for us to deal with all new issues and we are really waiting for 3.2.1 because of the fixes inside that release.

**Comment by monotek** [comment]
we have to change our tagging mechanism to get this work.
currently we would directly jump from 3.2.0 to 3.3.0.
we'll have a look.

**Comment by monotek** [comment]
minor version updates will be posted for future releases.
for now you can update to 3.3.0-11 directly. 
no special changes needed to upgrade.

**Comment by NickMos** [comment]
hm, ok.
3.1 -> 3.2 require to rebuild the ES index as I remember. I should take a closer look at what 3.3 is required.

**Comment by MrGeneration** [comment]
upgrading to 3.3 requires it as well.

**Comment by monotek** [comment]
This should be done automatically on any start anyway...
