### ISSUE TITLE
Changing postgres user + password in .env results in broken setup

### ISSUE THREAD

**Issue by drbw** [zammad/zammad-docker-compose#153]
### Infos:

* Docker version: All
* Docker-compose version: All
* Operating system (Docker host): All

### Expected behavior:

* Modifying environment variables shown in the .env file results in a working Zammad setup
* The `docker-compose.yml` can serve as a modifiable template that demonstrates common configurable options

### Actual behavior:

* The included `docker-compose.yml` only sets the user and password for Postgresql in the environments for `zammad-backup` and `zammad-postgres`
* Changing these variables results in a broken installation as `zammad-init` is unable to initialize the database:

```
Tasks: TOP => db:create => db:load_config => environment
(See full trace by running task with --trace)
initialising / updating database...
rake aborted!
PG::ConnectionBad: FATAL:  password authentication failed for user "zammad"
/usr/local/bundle/gems/pg-0.21.0/lib/pg.rb:56:in `initialize'
/usr/local/bundle/gems/pg-0.21.0/lib/pg.rb:56:in `new'
[...]
```
* The `docker-compose.yml` contains very few of the available environment variables.

### Steps to reproduce the behavior:

* Change Postgres password in .env
* `docker-compose up`
* `docker logs zammad-init`

### Notes

* Other projects commonly use the docker-compose.yml as described under "expected" and demonstrate what can be modified about the environment. `zammad-docker-compose` doesn't do this and instead requires the user to look at the `Dockerfile` / `entrypoint.sh` of the containers. This makes Zammad appear very inflexible and could be implemented in a much more user-friendly way by making `docker-compose.yml` more verbose.

**Comment by monotek** [comment]
Will be fixed in: https://github.com/zammad/zammad-docker-compose/pull/154

If you'd like to improve the compose file and documentation further feel free to create a pull request :)

**Comment by drbw** [comment]
Are you sure that `zammad-init` is the only container that needs the Postgres login? I had assumed that other containers would as well, e. g. `zammad-railsserver` but only specified what I could say for sure in the report. (Still working on getting Zammad up again.) Also, the environment variable for the container is `POSTGRESQL_PASS`, not `POSTGRESQL_PASSWORD`.

https://github.com/zammad/zammad-docker-compose/blob/master/containers/zammad/docker-entrypoint.sh#L15

**Comment by monotek** [comment]
Yes, as it edits the config file the other containers are using.
> Are you sure that `zammad-init` is the only container that needs the Postgres login?
Yes, as it edits the config file the other containers are using.

> Also, the environment variable for the container is `POSTGRESQL_PASS`, not `POSTGRESQL_PASSWORD`.

True. Copy paste error. 
Wondering why it worked anyway....

**Comment by reddighamburg** [comment]
This is due to a naming mismatch and easy to fix.

The Postgres Container is expecting environment variables for the user and accesses to be CREATED like so:
POSTGRES_DB
POSTGRES_USER
POSTGRES_PASSWORD
See: https://hub.docker.com/_/postgres

On the other hand, the zammad-init container is expecting environment variables to USE like so:
POSTGRESQL_DB
POSTGRESQL_USER
POSTGRESQL_PASS
See: https://docs.zammad.org/en/latest/install/docker-compose/environment.html

And again provided in the env file we see again a slightly different flavour for the password like so:
POSTGRES_PASS

To get it running with changed values, in the docker-compose file all of these should be assigned like so:

in the zammad postgres contrainer:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      
in the zammad init container:
- POSTGRESQL_HOST=${POSTGRES_HOST}
      - POSTGRESQL_PORT=${POSTGRES_PORT}
      - POSTGRESQL_USER=${POSTGRES_USER}
      - POSTGRESQL_PASS=${POSTGRES_PASS}
      - POSTGRESQL_DB=${POSTGRES_DB}

This will be mapping all the included values from the env file to the correct expected environment variables for both services and allow you to maintain yous stuff again at a single point in the env file

**Comment by reddighamburg** [comment]
Solved:
The configuration used for the init container indeed must be included in the other containers as well to transport any custom database settings correctly.
A little bit of reading zammad docs (link above) also tells, that this is also the expected bahviour.
"This variable is specific to the init container" in fact is only applicable to the last mentioned variable "POSTGRESQL_DB_CREATE" and not to the whole section.
The layout of the documentation may lead to a confusion in the first place, but actually it's all said.

Using the unchanged defaults previous did work, as all containers are also falling back to these, if completely unset (which is the case here).
Changing the value caused trouble, as the current docker compose file would only transport the change into some container but not into all of them.
