### ISSUE TITLE
Conflicting Elasticsearch indices when using external ES cluster

### ISSUE THREAD

**Issue by drbw** [zammad/zammad-docker-compose#155]
### Infos:

* Docker version: All
* Docker-compose version: All
* Operating system (Docker host): All

### Expected behavior:

* The use case described in https://docs.zammad.org/en/latest/install/elasticsearch.html under "Index Namespacing" is implemented:

```
# Useful when connecting multiple services or Zammad instances
# to a single Elasticsearch server (to prevent name collisions during indexing).
$ zammad run rails r "Setting.set('es_index', Socket.gethostname.downcase + '_zammad')"

```

### Actual behavior:

* The use case is not implemented and Zammad deletes the existing index if a second instance is deployed

### Workaround

* Specifying an invalid ES host results in `zammad-init` not finishing, thus blocking other containers from startup:

`zammad railsserver waiting for elasticsearch server to be ready...`

* While the containers are stalling, the setting can be changed as described if Socket.gethostname.downcase is replaced with a static name:

`docker exec zammad-railsserver bundle exec rails r "Setting.set('es_index', 'hostname_zammad')"`

* The containers can then be recreated with the correct ES hostname
* `zammad-init` now finishes correctly and the index `hostname_zammad_production` is initialized.

### Steps to reproduce the behavior:

* Clone the repository on two different systems
* Specify the same `ELASTICSEARCH_HOST` in the environment of `zammad-init` on both of them
* `docker-compose up`

**Comment by MrGeneration** [comment]
Just a side note from my end: The index is a sore example on how you can configure it.
That's also the reason why this lifes within "optional settings".

That's why I don't see this as an error or bug directly, André however might see this differently.

**Comment by monotek** [comment]
We could make this configurable.
As always PRs welcome...

**Comment by drbw** [comment]
Sorry, can only do pull requests off work.

Should be simple enough: https://github.com/zammad/zammad-docker-compose/pull/156

But @MrGeneration, I'm not sure what you mean with "The index is a sore example on how you can configure it.". I did notice that the (single) index got created as an ES 5 index at first and was only switched to ES 7 compatible naming (`zammad_production/Ticket` -> `zammad_production_ticket`) at first - was that a side effect you allude to?

(And lastly, I don't really see it as a bug, either, it's just IMHO worthy of improvement.)

**Comment by MrGeneration** [comment]
@drbw oh boy, I really f*cked up my wording there. Sorry... :D

What I really wanted to say: The index naming in the documentation is a sore example on how you *can* configure it - it's optional.

By default we're using `zammad_production` - as far as I'm aware.

I totally agree that there's room for improvement and as I've seen you've been working on that. Thank you very much for that!

**Comment by drbw** [comment]
That setting is `zammad` by default - at least thet's the case on our first instance where we haven't touched it yet. The `production` comes from `Rails.env`:

https://github.com/zammad/zammad/blob/develop/lib/search_index_backend.rb#L668

**Comment by monotek** [comment]
This it how it looks after fresh install so we should keep zammad_production or users will likely get a hard time after update.

```
curl zammad-docker-compose_zammad-elasticsearch_1:9200/_aliases?pretty=true
{
  "zammad_production_knowledge_base_translation" : {
    "aliases" : { }
  },
  "zammad_production_knowledge_base_category_translation" : {
    "aliases" : { }
  },
  "zammad_production_stats_store" : {
    "aliases" : { }
  },
  "zammad_production_user" : {
    "aliases" : { }
  },
  "zammad_production_cti_log" : {
    "aliases" : { }
  },
  "zammad_production_ticket" : {
    "aliases" : { }
  },
  "zammad_production_organization" : {
    "aliases" : { }
  },
  "zammad_production_chat_session" : {
    "aliases" : { }
  },
  "zammad_production_knowledge_base_answer_translation" : {
    "aliases" : { }
  }
}

```

**Comment by drbw** [comment]
Sorry if the above was unclear, but setting `es_index` to `zammad` results in the creation of indices in the namespace `zammad_production`. This is because the linked method `build_index_name` concatenates  `#{es_index}` with `_` and `#{Rails.env}`, where `Rails.env` is `production`.

Setting `es_index` to `zammad_production` results in this upon rebuilding the search index:

```
create indexes...I, [2020-03-27T11:38:26.447581 #117-47225149474260]  INFO -- : Setting.set('es_multi_index', true)
I, [2020-03-27T11:38:26.455125 #117-47225149474260]  INFO -- : # curl -X put "https://elastic1.example.com:9200/zammad_production_production_user"
I, [2020-03-27T11:38:27.453885 #117-47225149474260]  INFO -- : # 200
I, [2020-03-27T11:38:27.454763 #117-47225149474260]  INFO -- : # curl -X put "https://elastic1.example.com:9200/zammad_production_production_ticket"
I, [2020-03-27T11:38:29.079385 #117-47225149474260]  INFO -- : # 200
I, [2020-03-27T11:38:29.080134 #117-47225149474260]  INFO -- : # curl -X put "https://elastic1.example.com:9200/zammad_production_production_knowledge_base_category_translation"
I, [2020-03-27T11:38:31.533264 #117-47225149474260]  INFO -- : # 200
I, [2020-03-27T11:38:31.534011 #117-47225149474260]  INFO -- : # curl -X put "https://elastic1.example.com:9200/zammad_production_production_knowledge_base_translation"
I, [2020-03-27T11:38:34.194416 #117-47225149474260]  INFO -- : # 200
I, [2020-03-27T11:38:34.195241 #117-47225149474260]  INFO -- : # curl -X put "https://elastic1.example.com:9200/zammad_production_production_knowledge_base_answer_translation"
I, [2020-03-27T11:38:35.945892 #117-47225149474260]  INFO -- : # 200
I, [2020-03-27T11:38:35.946626 #117-47225149474260]  INFO -- : # curl -X put "https://elastic1.example.com:9200/zammad_production_production_cti_log"
I, [2020-03-27T11:38:38.032175 #117-47225149474260]  INFO -- : # 200
I, [2020-03-27T11:38:38.032928 #117-47225149474260]  INFO -- : # curl -X put "https://elastic1.example.com:9200/zammad_production_production_stats_store"
I, [2020-03-27T11:38:39.894889 #117-47225149474260]  INFO -- : # 200
I, [2020-03-27T11:38:39.895386 #117-47225149474260]  INFO -- : # curl -X put "https://elastic1.example.com:9200/zammad_production_production_organization"
I, [2020-03-27T11:38:41.601032 #117-47225149474260]  INFO -- : # 200
I, [2020-03-27T11:38:41.602470 #117-47225149474260]  INFO -- : # curl -X put "https://elastic1.example.com:9200/zammad_production_production_chat_session"
I, [2020-03-27T11:38:43.353619 #117-47225149474260]  INFO -- : # 200
```

I. e. the indices get created as `zammad_production_production_*`.

**Comment by monotek** [comment]
thanks! merged the pr :)
https://github.com/zammad/zammad-docker-compose/pull/156
