### ISSUE TITLE
Enable override/passthrough of X-Forwarded-Proto

### ISSUE THREAD

**Issue by h3kker** [zammad/zammad-docker-compose#157]
### Infos:

* Docker version: Docker version 19.03.8, build afacb8b7f0
* Docker-compose version: docker-compose version 1.25.4, build unknown
* Operating system (Docker host): Ubuntu 18.04

We are running Zammad on a backend server behind a reverse proxy (caddy). Caddy terminates SSL and forwards http to the backend, but the container nginx overwrites the `X-Fowarded-Proto` header with http.

When setting `http_mode` to https, login does not work with the error message: `XSRF token validation failed`. It works when setting it to http, but then outgoing links are created with http:// (which would be fine, since we've got a redirect, but it's not beautiful).

I've found a workaround: I can bind a modified zammad.conf to `/tmp/zammad-stable/contrib/nginx/zammad.conf` in the zammad-init service, but now I have to take care to keep this file in sync with any upstream changes.

It would be nice if one could override the X-Forwarded-Proto setting, either setting it to a fixed value via ENV or enable passthrough.

Thanks & ciao,
Heinz

**Comment by h3kker** [comment]
Sorry, I just saw that this is duplicate of #120. I also saw that the discussion got rather heated. Would a ENV override for the X-Fowarded-Proto be an option that does not have the security implications of just passing through what comes in?

**Comment by Hendrik44** [comment]
My workaround for now is to use a different image for nginx in my docker-compose-file and then mount a custom nginx config

`
zammad-nginx:
    expose:
      - "80"
    depends_on:
      - zammad-railsserver
    image: nginx:stable-alpine
    links:
      - zammad-railsserver
      - zammad-websocket
    restart: ${RESTART}
    volumes:
      - zammad-data:/opt/zammad
      - ./nginx_zammad.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"`
