### ISSUE TITLE
Non-default postgresql password documentation

### ISSUE THREAD

**Issue by h3kker** [zammad/zammad-docker-compose#158]
I think this is more of a documentation issue. I've set a custom password for the postgresql db and used the POSTGRES_PASS environment variable for that. 

This works fine for the postgresql service (initdb creates the database with the correct password), but then startup fails. I had to add

```
    environment:
      - POSTGRESQL_USER=${POSTGRES_USER}
      - POSTGRESQL_PASS=${POSTGRES_PASS}
```

to the zammad-init service so that the config is generated correctly. Sorry if I missed it, but I did not find this in the documentation.

Also the naming of variables is a bit confusing (`POSTGRESQL_PASSWORD` in zammad-backup, `POSTGRESQL_PASS` in zammad-init and `POSTGRES_PASS` as the expected env variable for backup + postgresql

Thanks & ciao,
Heinz

**Comment by MrGeneration** [comment]
I'm confused, that should work with the default compose-file?

https://github.com/zammad/zammad-docker-compose/blob/master/docker-compose.yml#L37

**Comment by h3kker** [comment]
Oops, sorry. Now I'm confused, too. It was a while ago, I just thought about filing it now because of another issue.

**Comment by h3kker** [comment]
Ah, I see: https://github.com/zammad/zammad-docker-compose/commit/f48fca238ed0216ec65417a6bd41d9b985201909

**Comment by MrGeneration** [comment]
Yes correc,t looks like your docker-compose is of the state from before that fix. :x
A pull of the current repo should fix your issue! :)
