### ISSUE TITLE
Instructions for clearing elastic search data are dangerous

### ISSUE THREAD

**Issue by Berdir** [zammad/zammad-docker-compose#159]
I copied and executed the rm -r line on the readme as I had the startup error from the index, without reading it carefully. Stupid, I know.

Problem is that the docker container has a different name in my setup, so I ended up executing rm /*, which deleted half my system before I could stop it.

I'd recommend putting a manual and less fancy option that runs that docker command then delete the folder that it outputs in the readme.

**Comment by monotek** [comment]
fixed in: https://github.com/zammad/zammad-docker-compose/commit/cdbb3dce14f65eca4febd9436e8059b38a73baad
