### ISSUE TITLE
Upgrade error from 3.3.0-19 to 3.4.0-2

### ISSUE THREAD

**Issue by GuidoDr** [zammad/zammad-docker-compose#163]
https://community.zammad.org/t/upgrade-error-from-3-3-0-19-to-3-4-0-2/4791

**Comment by monotek** [comment]
The unit container is supposed to exit when finished.

"exit 0" means "successfully". Any other exitcode would be an error.

**Comment by GuidoDr** [comment]
well that was what I also had thought when I had seen exit 0. 
But the problem was that even though it was 0 Zammad was not accessable even after a couple of minutes. But after a few docker-compose down and up it is now accessable again. Sorry, perhaps I should have waited longer before opening the issue.
