### ISSUE TITLE
websocket server waiting for zammads railsserver to be ready

### ISSUE THREAD

**Issue by hamzehmohammadnia** [zammad/zammad-docker-compose#17]
Greetings,

I'm running Dock Container Zammad on my local host. Unfortunately cant reach Zammad webportal on my local host. I just removed all my previous zammad dock containers with "rm -R" and cleaned up unused images and containers of docker. Then cloned latest version of Zammad into new directory.

When execute "Docker-compose up":
zammad-websocket_1 | websocket server waiting for zammads railsserver to be ready...
zammad-websocket_1 | websocket server waiting for zammads railsserver to be ready...
zammad-websocket_1 | websocket server waiting for zammads railsserver to be ready...
zammad-websocket_1 | websocket server waiting for zammads railsserver to be ready...
zammad-websocket_1 | websocket server waiting for zammads railsserver to be ready...
zammad-websocket_1 | websocket server waiting for zammads railsserver to be ready...
zammad-websocket_1 | websocket server waiting for zammads railsserver to be ready...
zammad-websocket_1 | websocket server waiting for zammads railsserver to be ready...
zammad-websocket_1 | websocket server waiting for zammads railsserver to be ready...
zammad-websocket_1 | websocket server waiting for zammads railsserver to be ready...
zammad-websocket_1 | websocket server waiting for zammads railsserver to be ready...
zammad-postgresql_1 | LOG: incomplete startup packet
zammad-websocket_1 | websocket server waiting for zammads railsserver to be ready...
zammad-railsserver_1 | creating db & searchindex...
zammad-railsserver_1 | bundler: failed to load command: rake (/usr/local/bundle/bin/rake)
zammad-railsserver_1 | Bundler::GemNotFound: Your bundle is locked to i18n (0.7.0), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of i18n (0.7.0) has removed it. You'll need to update your bundle to a different version of i18n (0.7.0) that hasn't been removed in order to install.
.
.
.
zammad-railsserver_1 | /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in require' zammad-railsserver_1 | /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:inrequire'
zammad-scheduler_1 | scheduler waiting for zammads railsserver to be ready...
zammad-websocket_1 | websocket server waiting for zammads railsserver to be ready...
zammad-scheduler_1 | scheduler waiting for zammads railsserver to be ready...
zammad-scheduler_1 | scheduler waiting for zammads railsserver to be ready...
zammad-websocket_1 | websocket server waiting for zammads railsserver to be ready...
zammad-scheduler_1 | scheduler waiting for zammads railsserver to be ready...
zammad-scheduler_1 | scheduler waiting for zammads railsserver to be ready...
zammad-scheduler_1 | scheduler waiting for zammads railsserver to be ready...
zammad-websocket_1 | websocket server waiting for zammads railsserver to be ready...
zammad-scheduler_1 | scheduler waiting for zammads railsserver to be ready...
zammad-scheduler_1 | scheduler waiting for zammads railsserver to be ready...
zammad-websocket_1 | websocket server waiting for zammads railsserver to be ready...
zammad-scheduler_1 | scheduler waiting for zammads railsserver to be ready...
zammad-scheduler_1 | scheduler waiting for zammads railsserver to be ready...
zammad-scheduler_1 | scheduler waiting for zammads railsserver to be ready...
zammad-websocket_1 | websocket server waiting for zammads railsserver to be ready...
running "docker-compose ps":
zammad-docker-compose(master)> docker-compose ps
Name Command State Ports

zammaddockercompose_za /docker-entrypoint.sh Up 9200/tcp, 9300/tcp
mmad-elasticsearch_1 elas ...
zammaddockercompose_za nginx -g daemon off; Up 443/tcp, 80/tcp,
mmad-nginx_1 0.0.0.0:8881->88/tcp
zammaddockercompose_za docker-entrypoint.sh Up 5432/tcp
mmad-postgresql_1 postgres
zammaddockercompose_za /docker-entrypoint.sh Restarting
mmad-railsserver_1 zamm ...
zammaddockercompose_za /docker-entrypoint.sh Up
mmad-scheduler_1 zamm ...
zammaddockercompose_za /docker-entrypoint.sh Up 6042/tcp
mmad-websocket_1 zamm ...
zammaddockercompose_za irb Exit 0

My docker ps status is as:
docker ps
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
db7d99e129d8 zammad/zammad-docker-compose:zammad-nginx "nginx -g 'daemon ..." 13 minutes ago Up 13 minutes 80/tcp, 443/tcp, 0.0.0.0:8881->88/tcp zammaddockercompose_zammad-nginx_1
33f31c5a49ff zammad/zammad-docker-compose:zammad-scheduler "/docker-entrypoin..." 31 minutes ago Up 14 minutes zammaddockercompose_zammad-scheduler_1
a8ba9c34a1e6 zammad/zammad-docker-compose:zammad-websocket "/docker-entrypoin..." 31 minutes ago Up 14 minutes 6042/tcp zammaddockercompose_zammad-websocket_1
4a6c81e4418f zammad/zammad-docker-compose:zammad-railsserver "/docker-entrypoin..." 31 minutes ago Restarting (1) 6 minutes ago zammaddockercompose_zammad-railsserver_1
b31aa471fea1 zammad/zammad-docker-compose:zammad-elasticsearch "/docker-entrypoin..." About an hour ago Up 14 minutes 9200/tcp, 9300/tcp zammaddockercompose_zammad-elasticsearch_1
ca64ade67f43 zammad/zammad-docker-compose:zammad-postgresql "docker-entrypoint..." About an hour ago Up 14 minutes 5432/tcp zammaddockercompose_zammad-postgresql_1

my inner docker-config of zammad as:
zammad-docker-compose(master)> cat docker-compose.yml
version: '3'

services:

zammad:
depends_on:
- zammad-elasticsearch
- zammad-postgresql
image: zammad/zammad-docker-compose:zammad
labels:
io.rancher.container.pull_image: always
io.rancher.container.start_once: 'true'
restart: on-failure
volumes:
- data-zammad:/home/zammad

zammad-elasticsearch:
image: zammad/zammad-docker-compose:zammad-elasticsearch
labels:
io.rancher.container.pull_image: always
restart: always

zammad-nginx:
depends_on:
- zammad
image: zammad/zammad-docker-compose:zammad-nginx
labels:
io.rancher.container.pull_image: always
links:
- zammad-railsserver
- zammad-websocket
ports:
- "8881:88" //since I was facing with error of already listening to port 0.0.0.0:80 I changed it like this
restart: always
volumes:
- data-zammad:/home/zammad

zammad-postgresql:
image: zammad/zammad-docker-compose:zammad-postgresql
labels:
io.rancher.container.pull_image: always
restart: always

zammad-railsserver:
depends_on:
- zammad
image: zammad/zammad-docker-compose:zammad-railsserver
labels:
io.rancher.container.pull_image: always
links:
- zammad-elasticsearch
- zammad-postgresql
depends_on:
- zammad
restart: always
volumes:
- data-zammad:/home/zammad

zammad-scheduler:
depends_on:
- zammad
image: zammad/zammad-docker-compose:zammad-scheduler
labels:
io.rancher.container.pull_image: always
links:
- zammad-elasticsearch
- zammad-postgresql
restart: always
volumes:
- data-zammad:/home/zammad

zammad-websocket:
depends_on:
- zammad
image: zammad/zammad-docker-compose:zammad-websocket
labels:
io.rancher.container.pull_image: always
links:
- zammad-postgresql
- zammad
restart: always
volumes:
- data-zammad:/home/zammad
volumes:
data-zammad:
driver: local

Im using Centos 7, Docker version 17.03.1-ce, and ruby 2.0.0.
Thank you in advance,

**Comment by monotek** [comment]
Cant reproduce:
* sysctl -w vm.max_map_count=262144
* cd zammad-docker-compose
* git pull
* docker-compose pull
* docker-compose up

After some time:

`zammad-scheduler_1      | scheduler waiting for zammads railsserver to be ready...
zammad-scheduler_1      | scheduler waiting for zammads railsserver to be ready...
zammad-websocket_1      | websocket server waiting for zammads railsserver to be ready...
zammad-scheduler_1      | scheduler waiting for zammads railsserver to be ready...
zammad-elasticsearch_1  | [2017-04-22T10:49:57,785][INFO ][o.e.c.m.MetaDataCreateIndexService] [K8ZCzNH] [zammad_production] creating index, cause [api], templates [], shards [5]/[1], mappings [Ticket]
zammad-scheduler_1      | scheduler waiting for zammads railsserver to be ready...
zammad-elasticsearch_1  | [2017-04-22T10:49:58,586][INFO ][o.e.c.m.MetaDataMappingService] [K8ZCzNH] [zammad_production/8l8-hIFNSbao1QdVFEZOZQ] create_mapping [User]
zammad-elasticsearch_1  | [2017-04-22T10:49:59,083][INFO ][o.e.c.m.MetaDataMappingService] [K8ZCzNH] [zammad_production/8l8-hIFNSbao1QdVFEZOZQ] update_mapping [Ticket]
zammad-elasticsearch_1  | [2017-04-22T10:49:59,359][INFO ][o.e.c.m.MetaDataMappingService] [K8ZCzNH] [zammad_production/8l8-hIFNSbao1QdVFEZOZQ] create_mapping [Organization]
zammad-railsserver_1    | drop indexes...
zammad-railsserver_1    | create indexes...
zammad-railsserver_1    | reload data...
zammad-railsserver_1    |  reload User
zammad-railsserver_1    |   - started at 2017-04-22 10:49:58 UTC
zammad-railsserver_1    |   - took 0 seconds
zammad-railsserver_1    |  reload Ticket
zammad-railsserver_1    |   - started at 2017-04-22 10:49:58 UTC
zammad-railsserver_1    |   - took 0 seconds
zammad-railsserver_1    |  reload Organization
zammad-railsserver_1    |   - started at 2017-04-22 10:49:59 UTC
zammad-railsserver_1    |   - took 0 seconds
zammad-railsserver_1    | starting zammad...
zammad-railsserver_1    | zammad will be accessable on http://localhost in some seconds
zammad-railsserver_1    | Puma starting in single mode...
zammad-railsserver_1    | * Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
zammad-railsserver_1    | * Min threads: 5, max threads: 30
zammad-railsserver_1    | * Environment: production
zammad-scheduler_1      | scheduler waiting for zammads railsserver to be ready...
zammad-websocket_1      | websocket server waiting for zammads railsserver to be ready...
zammad-scheduler_1      | scheduler waiting for zammads railsserver to be ready...
zammad-scheduler_1      | scheduler waiting for zammads railsserver to be ready...
zammad-websocket_1      | websocket server waiting for zammads railsserver to be ready...
zammad-scheduler_1      | scheduler waiting for zammads railsserver to be ready...
zammad-railsserver_1    | * Listening on tcp://0.0.0.0:3000
zammad-railsserver_1    | Use Ctrl-C to stop
zammad-railsserver_1    | 2017-04-22 10:50:08 +0000: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
zammad-railsserver_1    | 2017-04-22 10:50:08 +0000: ENV: {"rack.version"=>[1, 3], "rack.errors"=>#<IO:<STDERR>>, "rack.multithread"=>true, "rack.multiprocess"=>false, "rack.run_once"=>false, "SCRIPT_NAME"=>"", "QUERY_STRING"=>"", "SERVER_PROTOCOL"=>"HTTP/1.1", "SERVER_SOFTWARE"=>"puma 3.6.0 Sleepy Sunday Serenity", "GATEWAY_INTERFACE"=>"CGI/1.2"}
zammad-railsserver_1    | ---
zammad-railsserver_1    | 2017-04-22 10:50:10 +0000: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
zammad-railsserver_1    | 2017-04-22 10:50:10 +0000: ENV: {"rack.version"=>[1, 3], "rack.errors"=>#<IO:<STDERR>>, "rack.multithread"=>true, "rack.multiprocess"=>false, "rack.run_once"=>false, "SCRIPT_NAME"=>"", "QUERY_STRING"=>"", "SERVER_PROTOCOL"=>"HTTP/1.1", "SERVER_SOFTWARE"=>"puma 3.6.0 Sleepy Sunday Serenity", "GATEWAY_INTERFACE"=>"CGI/1.2"}
zammad-railsserver_1    | ---
`
So everything is working without problems.

**Comment by philku79** [comment]
I have the exact same issue.
ubuntu 16.04 lts

completly the same message.

**Comment by ubivent-seuffert** [comment]
same thing happend to me. after i deleted the (already existing old) "zammaddockercompose_data-zammad" volume, everything worked fine.
