### ISSUE TITLE
[Security] Upgrade memcached to 1.6

### ISSUE THREAD

**Issue by tvarsis** [zammad/zammad-docker-compose#174]
The docker-compose file relies on memcached 1.5 which docker container is no longer updated and have not been updated in 7 months. This becomes a security issue since those images are unpatched and no longer get security updates. Please upgrade to memcached 1.6 which is the currently maintained version.

**Comment by monotek** [comment]
done in https://github.com/zammad/zammad-docker-compose/commit/297c3f8004be6a5657ff74d49c439d6aa3820a1d
