### ISSUE TITLE
Run Zammad Stack without NGinx?

### ISSUE THREAD

**Issue by tilllt** [zammad/zammad-docker-compose#176]
Hello, 

I have an existing HAProxy server doing SSL offloading and I am trying to figure out if I can safely omit the nginx part from the docker-compose stack and just point HAProxy directly to the railsserver. Is there are reason why this is not a good idea or should this work? Any pointers what to do, other then exposing port 3000 of the railsserver container?

**Comment by monotek** [comment]
You can't. Nginx also serves assets like css, js and so on.
