### ISSUE TITLE
make zammad nginx work with proxy contaienr

### ISSUE THREAD

**Issue by sandrodz** [zammad/zammad-docker-compose#18]
### Infos:

* Docker version: 17.04.0-ce
* Docker-compose version: 1.11.2
* Operating system (Docker host): centOS

### Expected behavior:

* I publish port only on localhost to allow https://github.com/jwilder/nginx-proxy to reverse proxy to it based on environment variables.

![screen shot 2017-04-24 at 12 41 32 am](https://cloud.githubusercontent.com/assets/8479569/25317297/3c1a5f84-2887-11e7-8037-85e89201a697.png)

### Actual behavior:

I get 503 error, nginx-proxy doesn't understand what to do with it.

### Steps to reproduce the behavior:

run zammad with jwilder/nginx-proxy in front.

I've also created issue at jwilder/nginx-proxy repo, but we cannot get to the bottom: https://github.com/jwilder/nginx-proxy/issues/793 without your help.

**Comment by monotek** [comment]
I don't see what we should do? 
Everything works as expected.
jwilder/nginx-proxy is not part of this and therefore we don't support it.
