### ISSUE TITLE
not able to create docker image by using Dockerfile present in master branch

### ISSUE THREAD

**Issue by abhishek-tyagi87** [zammad/zammad-docker-compose#188]
# Infos

* Docker version: 20.10.3
* Docker-compose version:
* Operating system (Docker host): Centos Linux 7

# Expected behavior
image should be build

*

# Actual behavior

it is giving  below error during image build

Yarn executable was not detected in the system.
Download Yarn at https://yarnpkg.com/en/docs/install
I, [2021-03-01T08:37:24.967651 #3614-47270504585580]  INFO -- : Writing /tmp/zammad-stable/public/assets/application-print-25adf1ad928517e8672a95590d5449b40243c7ae6749c73d532f8fcc068c2612.css
I, [2021-03-01T08:37:24.968006 #3614-47270504585580]  INFO -- : Writing /tmp/zammad-stable/public/assets/application-print-25adf1ad928517e8672a95590d5449b40243c7ae6749c73d532f8fcc068c2612.css.gz
I, [2021-03-01T08:37:24.970944 #3614-47270504585580]  INFO -- : Writing /tmp/zammad-stable/public/assets/print-25adf1ad928517e8672a95590d5449b40243c7ae6749c73d532f8fcc068c2612.css
I, [2021-03-01T08:37:24.971040 #3614-47270504585580]  INFO -- : Writing /tmp/zammad-stable/public/assets/print-25adf1ad928517e8672a95590d5449b40243c7ae6749c73d532f8fcc068c2612.css.gz
I, [2021-03-01T08:37:25.090033 #3614-47270504585580]  INFO -- : Writing /tmp/zammad-stable/public/assets/knowledge_base-06e35830f5230d92957e79cb37b27d0cb29d3921a01cd1101a0d79d45b0681a1.css
I, [2021-03-01T08:37:25.090545 #3614-47270504585580]  INFO -- : Writing /tmp/zammad-stable/public/assets/knowledge_base-06e35830f5230d92957e79cb37b27d0cb29d3921a01cd1101a0d79d45b0681a1.css.gz
I, [2021-03-01T08:37:25.238303 #3614-47270504585580]  INFO -- : Writing /tmp/zammad-stable/public/assets/knowledge_base_public-8cabc0d60133581b53207c94bd1db9596279589580c0581616aa14849c0803d6.js
I, [2021-03-01T08:37:25.238810 #3614-47270504585580]  INFO -- : Writing /tmp/zammad-stable/public/assets/knowledge_base_public-8cabc0d60133581b53207c94bd1db9596279589580c0581616aa14849c0803d6.js.gz
I, [2021-03-01T08:37:25.575874 #3614-47270504585580]  INFO -- : Writing /tmp/zammad-stable/public/assets/knowledge_base_public_polyfills-90b07a6b9678d0b6c05e6d0fa10d500d3fc0368bfb2725770629d5d4b0691c9c.js
I, [2021-03-01T08:37:25.575992 #3614-47270504585580]  INFO -- : Writing /tmp/zammad-stable/public/assets/knowledge_base_public_polyfills-90b07a6b9678d0b6c05e6d0fa10d500d3fc0368bfb2725770629d5d4b0691c9c.js.gz
I, [2021-03-01T08:37:25.660016 #3614-47270504585580]  INFO -- : Writing /tmp/zammad-stable/public/assets/app/models/application-7670eaba1c43fb379af5a7df8e2261bf55136087f80a1f39030fc0cf5900c8ee.js
I, [2021-03-01T08:37:25.660150 #3614-47270504585580]  INFO -- : Writing /tmp/zammad-stable/public/assets/app/models/application-7670eaba1c43fb379af5a7df8e2261bf55136087f80a1f39030fc0cf5900c8ee.js.gz
/tmp/setup.sh: line 44:  3614 Killed                  bundle exec rake assets:precompile
The command '/bin/bash -e -o pipefail -c chmod +x /tmp/setup.sh;     /tmp/setup.sh install' returned a non-zero code: 137
[root@kworker1 zammad-docker-compose]#
*

# Steps to reproduce the behavior

clone zammad-docker-compose  repo master branch
and by using "docker build  -t <image-name:tag> -f /containers/zammad/Dockerfile .

**Comment by MrGeneration** [comment]
Please complete the missing information within the template of your first article of this issue.
Also provide the tag version you're using.

**Comment by monotek** [comment]
As the output startas with an "I" these are only infos. 
The container is build.

**Comment by abhishek-tyagi87** [comment]
hi ,
 container image is not building , after lot of time it stuck in   bundle exec rake assets:precompile steps  and "killed" error is coming,please find complete logs  .

I, [2021-03-01T12:24:06.292804 #3622-47382853548400]  INFO -- : Writing /tmp/zammad-stable/public/assets/application-print-25adf1ad928517e8672a95590d5449b40243c7ae6749c73d532f8fcc068c2612.css
I, [2021-03-01T12:24:06.293246 #3622-47382853548400]  INFO -- : Writing /tmp/zammad-stable/public/assets/application-print-25adf1ad928517e8672a95590d5449b40243c7ae6749c73d532f8fcc068c2612.css.gz
I, [2021-03-01T12:24:06.297340 #3622-47382853548400]  INFO -- : Writing /tmp/zammad-stable/public/assets/print-25adf1ad928517e8672a95590d5449b40243c7ae6749c73d532f8fcc068c2612.css
I, [2021-03-01T12:24:06.297494 #3622-47382853548400]  INFO -- : Writing /tmp/zammad-stable/public/assets/print-25adf1ad928517e8672a95590d5449b40243c7ae6749c73d532f8fcc068c2612.css.gz
I, [2021-03-01T12:24:06.572787 #3622-47382853548400]  INFO -- : Writing /tmp/zammad-stable/public/assets/knowledge_base-06e35830f5230d92957e79cb37b27d0cb29d3921a01cd1101a0d79d45b0681a1.css
I, [2021-03-01T12:24:06.572916 #3622-47382853548400]  INFO -- : Writing /tmp/zammad-stable/public/assets/knowledge_base-06e35830f5230d92957e79cb37b27d0cb29d3921a01cd1101a0d79d45b0681a1.css.gz
I, [2021-03-01T12:24:06.910077 #3622-47382853548400]  INFO -- : Writing /tmp/zammad-stable/public/assets/knowledge_base_public-8cabc0d60133581b53207c94bd1db9596279589580c0581616aa14849c0803d6.js
I, [2021-03-01T12:24:06.910242 #3622-47382853548400]  INFO -- : Writing /tmp/zammad-stable/public/assets/knowledge_base_public-8cabc0d60133581b53207c94bd1db9596279589580c0581616aa14849c0803d6.js.gz
I, [2021-03-01T12:24:07.585099 #3622-47382853548400]  INFO -- : Writing /tmp/zammad-stable/public/assets/knowledge_base_public_polyfills-90b07a6b9678d0b6c05e6d0fa10d500d3fc0368bfb2725770629d5d4b0691c9c.js
I, [2021-03-01T12:24:07.585257 #3622-47382853548400]  INFO -- : Writing /tmp/zammad-stable/public/assets/knowledge_base_public_polyfills-90b07a6b9678d0b6c05e6d0fa10d500d3fc0368bfb2725770629d5d4b0691c9c.js.gz
I, [2021-03-01T12:24:08.264711 #3622-47382853548400]  INFO -- : Writing /tmp/zammad-s### **table/public/assets/app/models/application-7670eaba1c43fb379af5a7df8e2261bf55136087f80a1f39030fc0cf5900c8ee.js
I, [2021-03-01T12:24:08.264878 #3622-47382853548400]  INFO -- : Writing /tmp/zammad-stable/public/assets/app/models/application-7670eaba1c43fb379af5a7df8e2261bf55136087f80a1f39030fc0cf5900c8ee.js.gz
Killed
The command '/bin/bash -e -o pipefail -c chmod +x /tmp/setup.sh;   sh -x  /tmp/setup.sh install' returned a non-zero code: 137**

**Comment by abhishek-tyagi87** [comment]
> Please complete the missing information within the template of your first article of this issue.
> Also provide the tag version you're using.



> Please complete the missing information within the template of your first article of this issue.
> Also provide the tag version you're using.

Hi @MrGeneration  i have provided required info. please do needful.

**Comment by MrGeneration** [comment]
Sorry but this is a technical question.
Even if you're creating a docker based image from a custom source installation, we can't support you.

Even if we would / could, this is the wrong please.
Please consult the community instead.

**Comment by monotek** [comment]
I tried it yesterday. Worked without problems. 
Don't know why your build is exiting.
