### ISSUE TITLE
Nginx container stops after starting every container

### ISSUE THREAD

**Issue by thelfensdrfer** [zammad/zammad-docker-compose#192]
# Infos

* Docker version: 20.10.3, build 48d30b5
* Docker-compose version: 1.26.2, build eefe0d31
* Operating system (Docker host): CentOS Linux release 7.9.2009 (Core)

# Expected behavior

* Clone repository
* Start container without errors

# Actual behavior

`docker-compose up`

After a few seconds:

```
zammad-nginx_1          | starting nginx...
zammad-nginx_1          | nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
```

# Steps to reproduce the behavior

* Clone repository
* Do not edit any files or settings
* `docker-compose up`

**Comment by MrGeneration** [comment]
> nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)

The user you're using doesn't seem to be allowed to bind to port 80.
As this is a technical question, in case you can't solve it with above hint, you may want to post on the community instead.

**Comment by thelfensdrfer** [comment]
As you can see from the log, the error was from inside the docker container.

**Comment by nutsflag** [comment]
Hello @thiagoalcav  and @MrGeneration 
I have the same error in my test environment  : 
zammad-nginx_1          | starting nginx...
zammad-nginx_1          | nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
zammad-docker-compose_zammad-nginx_1 exited with code 1

I have tried with the user ROOT. 

Docker version 20.10.5, build 55c4c88
Docker-compose version 1.28.5, build c4eb3a1f
Operating system : CentOS Linux release 7.9.2009

**Comment by MrGeneration** [comment]
And I'm telling you that this is a host specific issue *not* the docker-compose stack itself.

Left side is a CentOS 7 - right side Debian 10

![image](https://user-images.githubusercontent.com/6549061/110361315-1e53c200-8040-11eb-843b-0ce287e2c615.png)


In my opinion CentOS is the worst OS you can choose for the docker-compose stack in general. Have had too many issues with it. If you want to stick with it and still need help, please post your issue on the community.

This is the wrong place.

**Comment by thelfensdrfer** [comment]
This issue may be connected to centos, but definitely is a problem exclusive to zammad. I am running centos 7 on multiple servers and every one of the runs multiple nginx instances in docker containers. Never had any issues with it:

![image](https://user-images.githubusercontent.com/699106/110362148-3710a780-8041-11eb-9010-db6ff116d479.png)

> In my opinion CentOS is the worst OS you can choose for the docker-compose stack in general. Have had too many issues with it.

:roll_eyes: Ok.

**Comment by Juvenv** [comment]
This is not exactly an error in the build, its just a consequence of the commit 288b91a (remove gosu and run nginx as zammad user). One time that nginx is not executed as user `root`, is not possible to listen to port 80, there is need choose a port number  greater than 1000 (see more in this thread of [docker nginx](https://github.com/bitnami/bitnami-docker-nginx/issues/96#issuecomment-372183389)).

This can be solved just by adding another environment variable in the file `zammad-docker-compose/containers/zammad/docker-entrypoint.sh`, something like `NGINX_SERVER_PORT` that can be overridden from docker environment (like `.env` file) for that a user choose a properly value. Of course the file `zammad/contrib/nginx/zammad.conf` need to be edited with the content of this variable.

A hard coded solution may be edit zammad source code (file `zammad/contrib/nginx/zammad.conf`), changing line `listen 80;` to something like `listen 8080;`

**Comment by thelfensdrfer** [comment]
I completely agree with the cause of the error. What bothers me is, since when is only centos restricting ports < 1024 for root users and not debian?

**Comment by Juvenv** [comment]
> I completely agree with the cause of the error. What bothers me is, since when is only centos restricting ports < 1024 for root users and not debian?

This is not related to host (or operating system) where docker is running, is an issue on the docker container (derivative from base image `FROM ruby:2.6.6-slim AS builder`, that is based on debian, i think). So if you use stack docker compose image after `zammad/zammad-*-3.6.0-64` is not plug and play, nginx container will fail on start listen to port 80.

**Comment by thelfensdrfer** [comment]
Yeah, that kind of was my point. I set the user in `docker-compose.override.yml` to root, which works fine while testing zammad:

```yml
version: '3'

services:
  zammad-nginx:
    user: root
    ports:
      - "8090:80"
```

**Comment by monotek** [comment]
Woops. Sorry, i've missed that :/

Might be selinux that prevents usage of port 80 by unpriveleged users on Centos.

I tend to change the docker-compose file and nginx config to use port 8080 by default too.

**Comment by MrGeneration** [comment]
SeLinux doesn‘t seem to be the case. 
During my test earlier I tested it disabled too. 

However, I did not reboot at any step so my test may not be good enough.

**Comment by gustavobnmx** [comment]
+1: this commit causes nginx container to throw an error upon startup: https://github.com/zammad/zammad-docker-compose/commit/288b91a0cdff98712cef906dc94ed11ef31dca66

Reverting to: https://github.com/zammad/zammad-docker-compose/commit/7ef7084e485e8e64416eed0823047192b56056c9 until it is fixed

**Comment by monotek** [comment]
@gustavobnmx 
Are you on centos too?

**Comment by asqdmin** [comment]
> +1: this commit causes nginx container to throw an error upon startup: [288b91a](https://github.com/zammad/zammad-docker-compose/commit/288b91a0cdff98712cef906dc94ed11ef31dca66)
> 
> Reverting to: [7ef7084](https://github.com/zammad/zammad-docker-compose/commit/7ef7084e485e8e64416eed0823047192b56056c9) until it is fixed

We did the same. Our host is a Debian 9 and Docker Engine - Community Version 19.03.11

**Comment by siddjellali** [comment]
I have the same issue here with zammad-3.6.0-65;
My host runs on RancherOS and restrict access to lower ports.
I didn't have the issue with zammad-3.6.0-20

**Comment by siddjellali** [comment]
When do you release the hotfix on dockerhub ?

**Comment by monotek** [comment]
It's done automatically when a new commit to the stable branch of zammad/zammad arrives.

**Comment by monotek** [comment]
We've triggered a build.
It's already changed in the repo.
See: https://github.com/zammad/zammad-docker-compose/pull/194
