### ISSUE TITLE
"Loading..." on latest build.

### ISSUE THREAD

**Issue by deviousgeek** [zammad/zammad-docker-compose#20]
I am no longer able to start a clean installation of Zammad (using docker compose) after the very latest built images on docker hub. It may work the first time everything is booted up, but fails on subsequent restarts with the web interface returning error 404's for CSS and JS files used to render the web frontend.

### Infos:

* Docker version: 17.05.0-ce
* Docker-compose version: 1.11.2
* Operating system (Docker host): Ubuntu 16.04 LTS

### Expected behavior:

* The application web interface is accessible.

### Actual behavior:

* A blank screen with the text "Loading..." appears. The browser console has JS and CSS errors indicating that the bundled / build CSS and JS files are missing (404).

### Steps to reproduce the behavior:

* Start the application via docker-compose. Restart the containers.

**Comment by monotek** [comment]
Update and new install works for me without problems:
Please post output of:
* docker-compose logs

**Comment by monotek** [comment]
No feedback.... Closing... 
Feel free to reopen, if you have more infos.
