### ISSUE TITLE
Stuck at 'starting nginx...'

### ISSUE THREAD

**Issue by matt-cylanda** [zammad/zammad-docker-compose#200]
# Infos

* Docker version:
* Docker-compose version:
* Operating system (Docker host): Unraid CentOS

# Expected behavior

* Expecting the docker to start and the webgui to come up. Version 3.x came up without issue

# Actual behavior

* Everything 4.x seems to get through the init fine, but the Nginx container seems stuck at 'starting nginx...'

# Steps to reproduce the behavior

* Use the compose file as written.

**Comment by MrGeneration** [comment]
The same question was posted on the community by now as well.
I'm locking and closing this issue to reduce duplicate workload for any one that's going to reply to this.

See: https://community.zammad.org/t/stuck-at-starting-nginx/6599

**Comment by monotek** [comment]
Fore reference: 

The change of the nginx port from 80 to 8080 has been the problem.

See: https://github.com/zammad/zammad-docker-compose#from--360-65

Closing...
