### ISSUE TITLE
Upgrade to v4

### ISSUE THREAD

**Issue by ahoiroman** [zammad/zammad-docker-compose#203]
Hello dear zammad and zammad-docker-compose-team,

I just wondered what the "correct" way to upgrade zammad from 3.6 to 4 is. The docs are outdated and I hope to get more information here.

Any information is highly welcome.

Thanks in advance!

**Comment by waja** [comment]
https://docs.zammad.org/en/latest/install/update.html has the latest documentation and is also referring tohttps://github.com/zammad/zammad-docker-compose#upgrading. Which part is outdated?

**Comment by ahoiroman** [comment]
The upgrade-notes do not contain any information about the target-version so I only can assume it's 3.x -> 4.0

The docs are telling me that the docs are outdated (https://docs.zammad.org/en/latest/install/update.html)

![Bildschirmfoto 2021-04-23 um 10 25 02](https://user-images.githubusercontent.com/23051150/115842578-4182d700-a41e-11eb-804b-b4644810498a.png)

**Comment by ahoiroman** [comment]
Alright, I guess it's just a misunderstanding on my site. I assumed the docs are saying that the complete update-docs are outdated.

In fact, coming from 3.6, changing the NGINX port and telling traefik to use 8080 worked fine.

**Comment by olafbuitelaar** [comment]
i do believe it was advised to run a `rake searchindex:rebuild` see: https://support.zammad.com/help/en-us/38-technische-hinweise/189-inkompatibilitats-anderungen-breaking-changes-fur-zammad-4-0. I've not done the update myself yet, so i cannot confirm this
