### ISSUE TITLE
New Zammad NGINX config (#3371) breaks zammad-docker-compose: nginx: [emerg] a duplicate listen 0.0.0.0:8080

### ISSUE THREAD

**Issue by martinvonwittich** [zammad/zammad-docker-compose#205]
# Infos

* Docker version: Docker version 18.09.5, build e8ff056
* Docker-compose version: docker-compose version 1.21.0, build unknown
* Operating system (Docker host): Debian GNU/Linux 10 (buster)

# Expected behavior

* Upgrading/installing a `zammad-docker-compose` setup should not cause the following NGINX error:

```
zammad-nginx_1          | nginx: [emerg] a duplicate listen 0.0.0.0:8080 in /etc/nginx/sites-enabled/default:15                                                                                        
```

# Actual behavior

* Upgrading/installing a `zammad-docker-compose` setup breaks NGINX.

# Steps to reproduce the behavior

* Upgrade/install `zammad-docker-compose`.

**Comment by MrGeneration** [comment]
JFI: This is caused by this PR: https://github.com/zammad/zammad/pull/3511 
André mentioned it there as well, I currently have no time resources to find a working solution I'm afraid.

**Comment by martinvonwittich** [comment]
https://github.com/zammad/zammad/issues/3371 introduced IPv6 support into the `nginx.conf` provided by Zammad:

https://github.com/zammad/zammad/commit/dcf95d3bb92b8c456ddca789eb4522a019c8772c#diff-10ba153965e2826c59f9c5f953166894d12d633d5d6c874f7ad54431d8c4c4ec

This breaks `containers/zammad/docker-entrypoint.sh` which replaces both `listen` directives:

https://github.com/zammad/zammad-docker-compose/blob/master/containers/zammad/docker-entrypoint.sh#L123-L129

```
zammad@9825354b6161:~$ grep listen /etc/nginx/sites-enabled/default 
    listen 8080;
    listen 8080;
```

**Comment by MrGeneration** [comment]
Thanks for pointing out the files. I sometimes really struggle with docker...

So in theory, the dirty way to fix this would be the following, **untested** code?

```
 # configure nginx
  sed -e "/\[..\]:80/d" \
      -e "s#listen .*#listen ${NGINX_PORT};#g" \
      -e "s#proxy_set_header X-Forwarded-Proto .*;#proxy_set_header X-Forwarded-Proto ${NGINX_SERVER_SCHEME};#g" \
      -e "s#server .*:3000#server ${ZAMMAD_RAILSSERVER_HOST}:${ZAMMAD_RAILSSERVER_PORT}#g" \
      -e "s#server .*:6042#server ${ZAMMAD_WEBSOCKET_HOST}:${ZAMMAD_WEBSOCKET_PORT}#g" \
      -e "s#server_name .*#server_name ${NGINX_SERVER_NAME};#g" \
      -e 's#/var/log/nginx/zammad.\(access\|error\).log#/dev/stdout#g' < contrib/nginx/zammad.conf > /etc/nginx/sites-enabled/default
```

**Comment by martinvonwittich** [comment]
This change _might_ fix the issue inside the image:

``` diff
zammad-test.iserv.eu /root/zammaddockercompose # git diff containers/zammad/docker-entrypoint.sh 
diff --git a/containers/zammad/docker-entrypoint.sh b/containers/zammad/docker-entrypoint.sh
index 9cc0c6c..4795926 100755
--- a/containers/zammad/docker-entrypoint.sh
+++ b/containers/zammad/docker-entrypoint.sh
@@ -121,7 +121,7 @@ if [ "$1" = 'zammad-nginx' ]; then
   check_zammad_ready
 
   # configure nginx
-  sed -e "s#listen .*#listen ${NGINX_PORT};#g" \
+  sed -e "s#\\(listen\\( \|.*:\\)\\)[0-9]\\+;\$#\\1${NGINX_PORT};#g" \
       -e "s#proxy_set_header X-Forwarded-Proto .*;#proxy_set_header X-Forwarded-Proto ${NGINX_SERVER_SCHEME};#g" \
       -e "s#server .*:3000#server ${ZAMMAD_RAILSSERVER_HOST}:${ZAMMAD_RAILSSERVER_PORT}#g" \
       -e "s#server .*:6042#server ${ZAMMAD_WEBSOCKET_HOST}:${ZAMMAD_WEBSOCKET_PORT}#g" \
```

It should patch both `listen` lines correctly. Upstream config:

```
zammad-test.iserv.eu ~ # docker exec zammaddockercompose_zammad-nginx_1 cat contrib/nginx/zammad.conf | grep listen                                                                     
    listen 80;
    listen [::]:80;
```

Old `docker-entrypoint.sh`:

```
zammad-test.iserv.eu ~ # docker exec zammaddockercompose_zammad-nginx_1 cat contrib/nginx/zammad.conf | grep listen | sed -e "s#listen .*#listen ${NGINX_PORT};#g"
    listen 8080;
    listen 8080;
```

New `containers/zammad/docker-entrypoint.sh`:

```
zammad-test.iserv.eu ~ # docker exec zammaddockercompose_zammad-nginx_1 cat contrib/nginx/zammad.conf | grep listen | sed -e "s#\\(listen\\( \|.*:\\)\\)[0-9]\\+;\$#\\1${NGINX_PORT};#g"               
    listen 8080;
    listen [::]:8080;
```

Unfortunately I have no idea how to rebuild the image, so patching this inside of `/root/zammaddockercompose` doesn't actually do anything, because the image uses its internal `docker-entrypoint.sh` instead.

It's also highly likely that NGINX will still abort because the Docker container doens't actually have a IPv6, so maybe the IPv6 `listen` line needs to be removed altogether?

```
zammad-test.iserv.eu ~ # docker exec zammaddockercompose_zammad-nginx_1 cat contrib/nginx/zammad.conf | grep listen | sed -e "s#listen [0-9]\\+;\$#listen ${NGINX_PORT};#g" -e "s#\\(listen [^0-9].\\+;\\)#\#\\1#g"
    listen 8080;
    #listen [::]:80;
```

**Comment by martinvonwittich** [comment]
> -e "s#listen .*#listen ${NGINX_PORT};#g"
