### ISSUE TITLE
Example for Grafana service

### ISSUE THREAD

**Issue by t3easy** [zammad/zammad-docker-compose#208]
# Expected behavior

* An optional docker-compose file with a Grafana service and all necessary settings to access the Elasticsearch service

# Actual behavior

* No example present

**Comment by monotek** [comment]
i think this is realy out of scope...

**Comment by monotek** [comment]
For Grafana examples have a look here: 

https://github.com/zammad/grafana-dashboards

**Comment by t3easy** [comment]
Was just an idea, because the Grafana integration was shown yesterday at the free Webinar by Zammad.
If the docker-compose project would have an example how to add Grafana as an optional service this would help.

**Comment by MrGeneration** [comment]
I mean, adjust your docker-compose stack in theory right?

**Comment by t3easy** [comment]
A separate file with the Grafana Service which can be loaded by `docker-compose -f` or  `COMPOSE_FILE` environment variable.
