### ISSUE TITLE
Docker compose Change Port

### ISSUE THREAD

**Issue by thephilluk** [zammad/zammad-docker-compose#209]
Hi there,
unfortunately i cant seem to change the port used by the container...

# Infos

* Docker version: Docker version 20.10.6, build 370c289
* Docker-compose version: docker-compose version 1.29.1, build c34c88b2
* Operating system (Docker host): Ubuntu 18.04.5 LTS

# Expected behavior

* Zammad visible on changed Port

# Actual behavior

* Zammad not visible at all

# Steps to reproduce the behavior

* Pull git
* in docker-compose.yml change the "expose" under zammad-nginx
* docker-compose.override.yml change the "ports"
* docker-compose up
* try to open the setup (both 8080 & new port) not working.

**Comment by monotek** [comment]
https://github.com/zammad/zammad-docker-compose/blob/master/containers/zammad/docker-entrypoint.sh#L15

**Comment by thephilluk** [comment]
Hi,
changed the port in the entrypoint, docker-compose.yml & docker-compose.override.yml, started them, not working.
recloned the git, did the same as above, still not working.
ports are allowed through ufw, other webservices are running & accessible

thanks,
Philip

**Comment by thephilluk** [comment]
Attached a docker-compose up log, if that helps
[zammad-log.txt](https://github.com/zammad/zammad-docker-compose/files/6416997/zammad-log.txt)

**Comment by monotek** [comment]
docker-compose.override.yml
```
version: '2'
services:

  zammad-nginx:
    ports:
      - "8081:8081"
    environment:
    - NGINX_PORT=8081
```

**Comment by thephilluk** [comment]
> docker-compose.override.yml
> 
> ```
> version: '2'
> services:
> 
>   zammad-nginx:
>     ports:
>       - "8081:8081"
>     environment:
>     - NGINX_PORT=8081
> ```

Thank you, that worked...
for anyone else trying this: 

in docker-compose.yml change:
Line 54: `- "8080"` TO `- "NEWPORT"`

in docker-compose.override.yml change, so it looks like this:
`version: '2'
services:

  zammad-nginx:
    ports:
      - "NEWPORT:NEWPORT"
    environment:
    - NGINX_PORT=NEWPORT`

and last change ./containers/zammad/docker-entrypoint.sh as follows:
Line 15: : ` ${NGINX_PORT:=NEWPORT}"`

thank you Devs for helping on such a short notice.
Thanks,
Philip

**Comment by monotek** [comment]
you dont need to change the ./containers/zammad/docker-entrypoint.sh
