### ISSUE TITLE
Websocket tmp files

### ISSUE THREAD

**Issue by gpkvt** [zammad/zammad-docker-compose#21]
### Infos:

* Docker version: 17.0.3.1-ce
* Docker-compose version: 1.11.2
* Operating system (Docker host): Debian Jessie

### Expected behavior:

* Zammad should clean up tmp files in /home/zammad/tmp/websocket_production/

### Actual behavior:

* Zammad was running for a couple of weeks without problems, then the system was running out of inodes, and I discovered a lot (1,5 million) of tmp files in /volume/container/location/home/zammad/tmp/websocket_production/

**Comment by martini** [comment]
Hi @gpkvt 

thanks for feedback. Normally the deamon script/websocket-server.rb is cleaning up the tmp/websocket_production/ directory. It this daemon running?

@monotek maybe an docker issue?

 -Martin

**Comment by gpkvt** [comment]
Hi @martini 

thanks for your quick reply. websocket-server.rb seems to be up and running:

```
# docker top zammaddockercompose_zammad-websocket_1 
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
redacted+            312                 32283               0                   11:22               ?                   00:00:11            script/websocket-server.rb -b 0.0.0.0 start
```

I can't say if it was running before as I stopped all zammad containers before I deleted the tmp files. Now the containers are up for about 45 minutes and so far it looks good.

Is there a way to force the creation of those tmp files to see if they will be deleted now? In which interval should the files be cleaned up?

**Comment by martini** [comment]
> Is there a way to force the creation of those tmp files to see if they will be deleted now? In which interval should the files be cleaned up?

Just start Zammad Web App, login and click around. Then web socket messages will sent/received.

Normal web socket messages will get deleted after it is sent. The directory structure is:

`tmp/websocket_production/$WebSocket_Connection_ID`

This directory should get delete after 4 minutes session idle time. Just close the Zammad Web Abb browser and wail 5 minutes.

There is one directory `tmp/websocket_production/spool` which is not deleted (at least the content after several hours).

Good luck! :)

**Comment by gpkvt** [comment]
So far the Folders are deleted immediately after closing the browser tab.

I'll close the issue for now. Thanks for your help.
