### ISSUE TITLE
incorrectly tagged docker images 3.6.1-2 and 3.6.1-3

### ISSUE THREAD

**Issue by TheFirstGoodmaN** [zammad/zammad-docker-compose#211]
# Infos

* Docker version: `20.10.6`
* Docker-compose version: `1.21.0`
* Operating system (Docker host): `Debian 10.9`

# Expected behavior

* If in the `.env` file the version is set to `-3.6.1-2`, also the corresponding version is available

# Actual behavior

* Version `4.0.x` is used

# Steps to reproduce the behavior
preparation
```
git clone https://github.com/zammad/zammad-docker-compose.git
cd zammad-docker-compose
git checkout b39454dc36b0171813d2b78cd37a9bea11c787ba
sed -i 's/3.6.0-67/3.6.1-3/' .env
docker-compose up -d
```

checking version
```
$ cat .env | grep VERSION
VERSION=-3.6.1-3

$ docker ps | grep zammad-docker-compose_zammad-railsserver_1 | awk '{ print $2 }'
zammad/zammad-docker-compose:zammad-3.6.1-3

$ docker exec -it zammad-docker-compose_zammad-railsserver_1 cat /opt/zammad/VERSION
4.0.x
```

The same is true for the version `3.6.1-2`

## Other
I may have missed something, maybe you can set me on the right track.

Thanks for the great work you have done with Zammad and the docker-composer files!

With best regards
Marco

**Comment by monotek** [comment]
I can confirm that this is already wron in the container image:

```
docker run -it --rm --entrypoint=/bin/cat zammad/zammad-docker-compose:zammad-3.6.1-3 /tmp/zammad-stable/VERSION
4.0.x
```

```
docker run -it --rm --entrypoint=/bin/cat zammad/zammad-docker-compose:zammad-3.6.0-67 /tmp/zammad-stable/VERSION
3.6.x
```

I currently don't know how this happened.

Not sure if we want to fix this for an outdated version...

**Comment by TheFirstGoodmaN** [comment]
Thanks for the feedback. That already helps me, first thought it was a mistake on my part. If you will not correct it I would suggest to remove the images from docker hub to prevent unnecessary confusion.

**Comment by monotek** [comment]
Done :)

**Comment by TheFirstGoodmaN** [comment]
Thank you for your quick reply and clarification
