### ISSUE TITLE
kubernetes kompose rails console returns nil

### ISSUE THREAD

**Issue by drabui** [zammad/zammad-docker-compose#212]
# Infos

* Docker version: 20.10.5
* Docker-compose version: 1.29.2
* Operating system (Docker host): Ubuntu 18.04
* Kubectl v1.20.5
* Kompose 1.22.0

# Expected behavior

* Rails console should contain rails commands (e.g. Setting.get('fqdn')) 

# Actual behavior

* Rails console returns nil
* zammad_'production database' is missing in postgres container(?)

# Steps to reproduce the behavior

* using kompose to translate docker-compose to kubernetes manifests
* creating PersistentVolume for PersistentVolumeClaims
* giving some pods permissions to access certain directories
* adding subpath to postgres deployment (/var/lib/postgresql/data isn't emty)

The pods are running fine and I can access Zammad and do stuff but the rails console does return nil on every command.
Since I'm super new to Kubernetes and Docker Compose I'm somewhat lost why and what is happening (bear with me if this isn't an issue but me messing up the configuration).
As mentioned above the zammad_production database is missing which is somewhat of a hint that I found but beside that I'm kinda lost.
Maybe someone did run into something similiar or managed to get zammad working?

**Comment by monotek** [comment]
Please use our helm chart if you want to run on kubernetes.

https://github.com/zammad/zammad-helm

**Comment by drabui** [comment]
For my thesis work I have to try to get it work via Kompose,  but if this isn't resolvable then ye I'll have to use Helm

**Comment by monotek** [comment]
It was never tested this way and we can't support you with that.

**Comment by drabui** [comment]
Alright I'll try the helm chart then, thank you for your help 

Btw I'm running in some permission denied issues with the helm chart, should I create a new issue @ the chart repo or is it possible do move and edit this issue?
