### ISSUE TITLE
zammad-backup env HOLD_DAYS is ignored

### ISSUE THREAD

**Issue by nh-matti** [zammad/zammad-docker-compose#213]
# Infos

* Docker version:  20.10.7, build f0df350
* Docker-compose version: 1.27.4, build 40524192
* Operating system (Docker host): Ubuntu 20.04.2 LTS

# Expected behavior

* The Environment of zammad-backup "HOLD_DAYS=10" should working

# Actual behavior

* Ennvironment settings of Retention ist ignored and stays at the default value of 10

# Steps to reproduce the behavior

* changed the setting inside the container manually, after an docker-compose up -d the value is on 10

**Comment by monotek** [comment]
change it in https://github.com/zammad/zammad-docker-compose/blob/master/docker-compose.yml#L12 or the override file.

```
docker-compose up
docker exec -it zammad-docker-compose_zammad-backup_1 env|sort
```

Will output:
```
BACKUP_SLEEP=86400
HOLD_DAYS=1
HOME=/root
HOSTNAME=fff6b508dae2
LANG=en_US.utf8
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PGDATA=/var/lib/postgresql/data
PG_MAJOR=9.6
PG_SHA256=3d08cba409d45ab62d42b24431a0d55e7537bcd1db2d979f5f2eefe34d487bb6
PG_VERSION=9.6.20
POSTGRESQL_PASSWORD=zammad
POSTGRESQL_USER=zammad
TERM=xterm
```

**Comment by nh-matti** [comment]
Hi monotek,
This is exactly what it did.
```
docker exec -it zammad-docker-compose_zammad-backup_1 env|sort
```

My Output:
```
BACKUP_SLEEP=86400
HOLD_DAYS=1
HOME=/root
HOSTNAME=e7437d3e7203
[...]
```
My Backup location at `/var/lib/docker/volumes/zammad-docker-compose_zammad-backup/` holds right now 2 Backups:
```
20210606081332_zammad_db.psql.gz
20210606081332_zammad_files.tar.gz
20210607082816_zammad_db.psql.gz
20210607082816_zammad_files.tar.gz
```

Inside of the backup-container the file "/opt/zammad/contrib/backup/config.dist" still contains the wrong number of retention:
```
#!/usr/bin/env bash
#
# zammad backup script config
#

BACKUP_DIR='/var/tmp/zammad_backup'
HOLD_DAYS='10'
DEBUG='no'
```
Do you have any hints on that, where to dig?

**Comment by MrGeneration** [comment]
The `.dist` file is not being used, the file is called `config`. 
You're probably affected by the topic that's going to be addressed by this PR:
https://github.com/zammad/zammad/pull/3570

**Comment by nh-matti** [comment]
Yes Sir, this is what i'm looking for. I've checked it with:
```
find -type f -mmin +1440 -exec stat -c "name: %n -- mtime: %y" {} \; | sort
```
This [zammad/zammad#3570](https://github.com/zammad/zammad/pull/3570) PR  would solve my problem.

**Comment by monotek** [comment]
The docker container does not use the dist or config file at all.
There is an own backup container, which uses an own backup script.
See: https://github.com/zammad/zammad-docker-compose/blob/master/containers/zammad-postgresql/backup.sh
