### ISSUE TITLE
Changes for Zammad 5

### ISSUE THREAD

**Issue by mgruner** [zammad/zammad-docker-compose#220]
Running Zammad in a clustered environment will be much easier [with Zammad 5](https://github.com/zammad/zammad-documentation/pull/190):

- Redis is [now supported](https://github.com/zammad/zammad/commit/1eef2a0e0f5a32b7769590749aa14b512de25d00) as web socket session store
- Memcached [can now be configured](https://github.com/zammad/zammad/commit/f05f8e2d3cc1b4a91bede6c0d1452dd21f765247) as Rails cache back end

Please consider updating the Memcached integration after the Zammad 5 switch. Applying a patch should no longer be needed.
Adding Redis might also be worth considering.

**Comment by waja** [comment]
Ping

**Comment by MrGeneration** [comment]
I believe that this is solved by https://github.com/zammad/zammad-docker-compose/pull/219 which is why I'm closing this issue manually.
