### ISSUE TITLE
postgresql password not protected when using `sed`

### ISSUE THREAD

**Issue by klando** [zammad/zammad-docker-compose#224]
### Infos:

* Docker version: Docker version 20.10.6, build 370c289
* Operating system (Docker host): debian 10.9
 
### Expected behavior:

* PostgreSQL connection successfull

### Actual behavior:

* `PostgreSQL connection refused: bad password`

### Steps to reproduce the behavior:

* define a `POSTGRESQL_PASS = "password with an & is expected to work"`

# Suggested fix

protect the environment variables when doing the sed stage in docker-entrypoint.sh line 56 (and probably in other places  too...)

**Comment by mgruner** [comment]
I just transferred it from `zammad-docker` to `zammad-docker-compose`.

**Comment by klando** [comment]
> @klando this is actually about [zammad-docker-compose](https://github.com/zammad/zammad-docker-compose), isn't it?

it is, I shuffled both projects.

**Comment by mgruner** [comment]
Fixed via db7ca4b92d2cd3ee23d250c7dcbabbfd408dbf2f.
