### ISSUE TITLE
Add version on docker hub

### ISSUE THREAD

**Issue by xf-** [zammad/zammad-docker-compose#23]
### Expected behavior:

* Add versions for simple down/upgrades

### Actual behavior:

* Only a main version and no simple way to checkout older version (non-broken version).

**Comment by monotek** [comment]
Not possible as we use automated builds.

**Comment by monotek** [comment]
Maybe there is another way to do it but we have to move everything to https://docs.travis-ci.com to do it...
I'll give it a try when having time to test it.

**Comment by monotek** [comment]
I already have it working in a private repo. So it's coming soon :-)

**Comment by monotek** [comment]
First images with a tagged version are online: https://hub.docker.com/r/zammad/zammad-docker-compose/tags/
