### ISSUE TITLE
Init failed  : File name too long (36)

### ISSUE THREAD

**Issue by JonathanBlary** [zammad/zammad-docker-compose#244]
# Infos

* Docker version: 20.10.9
* Docker-compose version: Using Portainer 2.9.0 - API Docker
* Operating system (Docker host): Alpine Linux 3.14.2

# Expected behavior
After installation of Zammad using docker-compose via portainer, i expect normal initialisation of Zammad.

# Actual behavior
Initialisation of Zammad in the _zammad-init_ container failed : _File name too long (36)_ . See logs.
So, the others containers are still _waiting for init container to finish install or update..._
[zammad-init_1_logs.txt](https://github.com/zammad/zammad-docker-compose/files/7330585/zammad-init_1_logs.txt)

# Steps to reproduce the behavior
I mapped the docker volumes on a shared folder on a Synology DS1621+ DSM 7.0 using NFS v4. The volume is btrfs and encrypted.
The path where is mapped the volume _/opt/zammad/_ on the Synology is  _/volume1/docker/Zammad/zammad-data/..._

Thank you for developing Zammad and making it open source.
If you need any further information, please let me know

**Comment by MrGeneration** [comment]
I can't verify this on a normal docker-compose environment.
I've tried to test this on my DSM 6 - however, the docker-compose process is such a pain in the ass that I've given up.

This might be tool specific, sorry.

**Comment by JonathanBlary** [comment]
Ok. Thanks.
