### ISSUE TITLE
Zammad image layers are not optimal

### ISSUE THREAD

**Issue by t3easy** [zammad/zammad-docker-compose#26]
### Infos:

* Docker version: 17.06
* Docker-compose version: 0.12.1
* Operating system (Docker host): Ubuntu 16.04

### Expected behavior:

* Small image size

### Actual behavior:

* Install and uninstall in different steps generates larger image because of the layers

**Comment by t3easy** [comment]
Here an idea:

- Add an env ZAMMAD_UPDATE default 1
- Move BUILD_DEPENDENCIES to env
- remove BUILD_DEPENDENCIES after initial build
- Add a zammad-update script that installs BUILD_DEPENDENCIES, updates zammad and removes BUILD_DEPENDENCIES
- Trigger the zammad-update script from docker-entrypoint if ZAMMAD_UPDATE is 1

If you like that idea, I would prepare a PR within the next few days.

I also thought of using docker multi stage build to prevent the install/uninstall trouble and just COPY over the build result to final intermediate container. But because of COPY results in files owned by root and chown them would generate an additional large layer this is not a good idea atm.

**Comment by monotek** [comment]
I also don't like to keep the build dependencies but installing/uninstalling dependencies from entrypoint script could slow down the startup process a lot.

**Comment by t3easy** [comment]
What about this update procedure: https://github.com/zammad/zammad-docker-compose/issues/22#issuecomment-316956454
This way no build dependencies are required for the update after the build.

**Comment by monotek** [comment]
I'd prefer to have an automatic update path without the need to doing something by hand.
I'll close this bug for now.
If you have another idea feel free to reopen it.
