### ISSUE TITLE
Set log level for production to higher value, e.g. WARN, not INFO

### ISSUE THREAD

**Issue by vasyugan** [zammad/zammad-docker-compose#269]
# Infos

* Docker version: 5:20.10.12~3-0~ubuntu-focal
* Docker-compose version: 1.25.0,
* Operating system (Docker host): Ubuntu 20.04

# Expected behavior

* Zammad should not flood the systemd journal with INFO messages. Log level in production should be set to WARN

# Actual behavior

* Zammad floods systemd journal with INFO messages

# Steps to reproduce the behavior

* This is the standard behaviour of Zammad in docker-compose. So just run it and inspect the journal with journalctl -f

**Comment by MrGeneration** [comment]
This is out of docker-compose context.
Beside there is no different log levels apart from the default you're seeing and debug.

So this would be a feature request that should be created on the community if not created already: https://community.zammad.org

**Comment by vasyugan** [comment]
> This is out of docker-compose context. Beside there is no different log levels apart from the default you're seeing and debug.
> 
> So this would be a feature request that should be created on the community if not created already: https://community.zammad.org

When zammad is installed natively, you can just edit production.rb, but on docker this is not feasible as the change is lost as docker containers are transient. Thus there should be a way to set the log level via docker-compose.yml

**Comment by MrGeneration** [comment]
> When zammad is installed natively, you can just edit production.rb, but on docker this is not feasible as the change is lost as docker containers are transient. Thus there should be a way to set the log level via docker-compose.yml

I'm not in the mood to start a discussion on a sunday sorry.
I did provide all relevant information, there is no native `WARN` log level in Zammad.

**Comment by vasyugan** [comment]
> > When zammad is installed natively, you can just edit production.rb, but on docker this is not feasible as the change is lost as docker containers are transient. Thus there should be a way to set the log level via docker-compose.yml
> 
> I'm not in the mood to start a discussion on a sunday sorry. I did provide all relevant information, there is no native `WARN` log level in Zammad.

Please see /opt/zammad/config/environments/production.rb

Look for these lines:

```
  # Use the lowest log level to ensure availability of diagnostic information
  # when problems arise.
  config.log_level = :info

```
I have just replace ":info" by ":warn" and restarted the container and now the system journal is no longer being spammed by INFO messages.

I would suggest that this should be the default config for the docker images.

**Comment by MrGeneration** [comment]
Which part of "Zammad has no such log level warn" in it's core did you not understand?
If you wanna break your installation sure, go for it, but I will defend the main application with my dead body from it.

**Comment by MrGeneration** [comment]
> please try not to overreact.

I'll be solving the issue for you. I'm out.
