### ISSUE TITLE
Compose Setup without elastic 

### ISSUE THREAD

**Issue by Syntax3rror404** [zammad/zammad-docker-compose#271]
Hello, is there a way  to use zammad without elastic. We use it for a small environment and the ram usage is to high. What can we do to disable elastic with the compose setup?

**Comment by Syntax3rror404** [comment]
Done by setting ELASTICSEARCH_ENABLED=false inside the zammad-init env

**Comment by slajar** [comment]
This option does not work anymore. I have a 40GB machine and elastic search takes 60% of this RAM, so I would like to deactivate elastic search. Using ELASTICSEARCH_ENABLED=false inside .env has no behavior change. Then I tried to disable the elastic in the docker-compose, but it seems railsserver waits for elastic for an eternity.

**Comment by waja** [comment]
@slajar please read what @Syntax3rror404 wrote:

> Done by setting ELASTICSEARCH_ENABLED=false inside the zammad-init env

You have to set ELASTICSEARCH_ENABLED=false for the zammad-init container. This is not the same as setting it in the `.env`file!
