### ISSUE TITLE
Elasticsearch configuration is not configured automatically and not documented

### ISSUE THREAD

**Issue by t3easy** [zammad/zammad-docker-compose#28]
### Infos:

* Docker version: 17.06
* Docker-compose version: 0.12.1
* Operating system (Docker host): Ubunto 16.04

### Expected behavior:

* Elasticsearch up and running after initial up

### Actual behavior:

* Elasticsearch has to be configured manually and there is no hint in the docker-compose documentation part

### Steps to reproduce the behavior:

* docker-compose up -d
* configure new system
* open stats
* get error message elasticsearch not configured

**Comment by t3easy** [comment]
I saw a line in the docker-entrypoint that should take care of this. Seems it didn't work.

**Comment by monotek** [comment]
It is. 
Elasticsearch is configured when you see this in the logs:

zammad-railsserver_1    | drop indexes...
zammad-railsserver_1    | create indexes...
zammad-railsserver_1    | reload data...
zammad-railsserver_1    |  reload User
zammad-railsserver_1    |   - started at 2017-07-22 12:58:56 UTC
zammad-railsserver_1    |   - took 0 seconds
zammad-railsserver_1    |  reload Ticket
zammad-railsserver_1    |   - started at 2017-07-22 12:58:56 UTC
zammad-railsserver_1    |   - took 0 seconds
zammad-railsserver_1    |  reload Organization
zammad-railsserver_1    |   - started at 2017-07-22 12:58:57 UTC
zammad-railsserver_1    |   - took 0 seconds
