### ISSUE TITLE
Wrong CSRF workflow

### ISSUE THREAD

**Issue by Kavernes** [zammad/zammad-docker-compose#280]
Dear,

I recently deployed this project in my environment. The deployment is successful, I could send and receive tickets from the smtp email I configured.
I didn't do any customization on the configuration yet (no HTTPS and I used the nginx proxy provided in the docker-compose.yml).

My problem is that when I try to login I get a "CSRF Verification Failed". After going through the many post on that matters, I realized that it is not my issue.

After looking in details in the workflow (using burpsuite), I mange to see this behavior:

1 => GET /
  <= Response containing header "CSRF-TOKEN: <**CSRF1**>"
2 => POST /api/v1/signhow
  <= Response containing header "CSRF-TOKEN: <**CSRF2**>"
3 => POST /api/v1/signin
   => Request header "X-CSRF-Token: <**CSRF2**>"
  <= Response "CSRF validation failed"

I tried to intercept the request (3) and change the X-CSRF-Token to <CSRF1> and it works fine...
I attached some burp screenshot. 

Thanks for your help.
![Req1](https://user-images.githubusercontent.com/94579240/168945826-f89da4fe-7049-4612-92ce-c4302af06e64.PNG)
![Req2](https://user-images.githubusercontent.com/94579240/168945833-42f3e5a3-4189-4388-a48d-a598fd18812b.PNG)
![Req3_Orig](https://user-images.githubusercontent.com/94579240/168945836-b559a6d8-b609-45b7-a19a-da26c1b55c0c.PNG)
![Req3_Modif](https://user-images.githubusercontent.com/94579240/168945838-8f74f535-1346-46cb-834c-dd59953713c0.PNG)

**Comment by ggruening** [comment]
Hey everybody,

very similar here. I migrated the system to another server. The "First Steps" run works, but after importing the database I can't log in ("CSRF token verification failed!").

Is there a way to temporarily deactivate CSRF verfication?

Best regards
Gregor

**Comment by ggruening** [comment]
> very similar here. I migrated the system to another server. The "First Steps" run works, but after importing the database I can't log in ("CSRF token verification failed!").

At the end I could solve it by adding the lines mentioned [here](https://github.com/zammad/zammad/issues/2829#issuecomment-784577292) to the compose stack. 

Best regards Gregor
