### ISSUE TITLE
Always safe to use master of this repo as-is?

### ISSUE THREAD

**Issue by estan** [zammad/zammad-docker-compose#284]
Hi @MrGeneration,

We are tracking this repo for our Zammad instance.

When pulling in upstream recently I noticed that commits like e.g. https://github.com/zammad/zammad-docker-compose/commit/cc6207c3544460458272d65e7759375cb128941c were pulled in.

These seem to be related to Zammad 5.2, but the version in .env has not been bumped yet.

Just want to confirm that it's safe to run with these changes while still being on 5.1.

If not, could you consider always doing changes related to a version bump in one go (as one commit), so we don't have to worry :)

Thanks.

**Comment by MrGeneration** [comment]
The env is not as regularly updated version wise like possible improvements might.
You can find the latest versions on docker hub - the changes on this repository that are not compose file and env file related are within the next built stable version. You can't avoid those changes.

**Comment by estan** [comment]
Aha, yes my bad. Those changes I saw were to the Dockerfiles of course, so would not affect us since we do use the images from Docker Hub. Makes sense, thanks!
