### ISSUE TITLE
Zammad 5.2.1 released

### ISSUE THREAD

**Issue by waja** [zammad/zammad-docker-compose#286]
Hi,

there dropped a release ... https://zammad.com/en/releases/5-2-1

Cheers Jan

**Comment by ubivent-seuffert** [comment]
@MrGeneration isn't a change to the .env file needed as well to close this issue?

**Comment by MrGeneration** [comment]
> @MrGeneration isn't a change to the .env file needed as well to close this issue?


See https://github.com/zammad/zammad-docker-compose/pull/288#issuecomment-1179528592 for more insight.

TL;DR: No.
