### ISSUE TITLE
Commands are executed in / instead of /home/zammad

### ISSUE THREAD

**Issue by t3easy** [zammad/zammad-docker-compose#29]
### Infos:

* Docker version: 17.06
* Docker-compose version: 0.12.1
* Operating system (Docker host): Ubuntu 16.04

### Expected behavior:

* Commands should be executed in the application folder /home/zammad

### Actual behavior:

* Commands are executed in /

### Steps to reproduce the behavior:

* docker-compose exec zammad-railsserver rails c

The WORKDIR should be set to /home/zammad

**Comment by monotek** [comment]
Pull requests are very welcome :-)

**Comment by t3easy** [comment]
I'll send a PR tomorrow :)
