### ISSUE TITLE
Docker-compose Release is outdated

### ISSUE THREAD

**Issue by MacLemon** [zammad/zammad-docker-compose#301]
The zammad-docker-compose repo still deploys Zammad 5.2.1-7, while it *should* deploy [Zammad 5.2.2](https://zammad.com/en/releases/5-2-2).

Docker deployments are therefor missing important security fixes as per release notes of the [Zammad 5.2.2 Security Release](https://zammad.com/en/releases/5-2-2) which even link to this older 5.2.1 release.

Thanks for bringing the docker-compose repo up to par with other Zammad releases.

**Comment by MrGeneration** [comment]
You do know that you can always update your override or env file accordingly? ^^

**Comment by MacLemon** [comment]
That is missing the point. I may or not know this, as much as any other person cloning this repo to install Zammad-Docker-Compose may or not be familiar with override files. Also this would require me to know what string *exactly* to put there. `5.2.2-??`?l

It was probably just an oversight that this was missed during the 5.2.2 release. It would have been an easy fix to bump up the `env` file in this repo with the correct version number to help out everyone.

**Comment by MrGeneration** [comment]
PRs are always welcome.
The tag numbers are also no secret.

https://hub.docker.com/r/zammad/zammad-docker-compose/tags

The documentation also clearly states it.
