### ISSUE TITLE
Change zammad user UID and GID from 1000 to 1111

### ISSUE THREAD

**Issue by guywillett** [zammad/zammad-docker-compose#305]
# Infos

* Docker version:
* Docker-compose version:
* Operating system (Docker host): Amazon Linux 2 (on AWS ECS)

# Expected behavior

* zammad user UID and GID are not the same as a host user

# Actual behavior

* zammad user UID/GID are 1000 which is the same as ec2-user on the host. If the zammad user manages to escape the container, it will have the same privileges as ec2-user on the host (including "sudo").
* output of `id ec2-user` is `uid=1000(ec2-user) gid=1000(ec2-user) groups=1000(ec2-user),4(adm),10(wheel),190(systemd-journal),994(docker)`

# Steps to reproduce the behavior

* Access an EC2 running Amazon Linux 2 and run `id ec2-user` or something like `cut -d: -f1 /etc/passwd` to list all users with their UIDs

**Comment by MrGeneration** [comment]
That's a host specific issue in specific environments.

**Comment by guywillett** [comment]
Well, yes. But since it is likely/common that the host will be a linux distribution, it is likely/common there will be a host user with 1000 UID (if a non-root user has been created on the host).

It just seems strange to use a UID for `zammad` that is *likely* to be the same as a host user, rather than *unlikely*.

**Comment by MrGeneration** [comment]
The compose doesn't use a specific `uid` or `gid`. This is simply how `createuser` works.

**Comment by guywillett** [comment]
The zammad-docker-compose images on DockerHub use UID 1000, and the`setup.sh` script does too [https://github.com/zammad/zammad-docker-compose/blob/master/containers/zammad/setup.sh#L35](https://github.com/zammad/zammad-docker-compose/blob/master/containers/zammad/setup.sh#L35)

**Comment by waja** [comment]
anyhow ... changing the uid/gid might break existing installations

**Comment by monotek** [comment]
I also would not like to change the zammad user id.

To use user id 1000 in docker containers is quite common and i also doubt all the other containers will change because of the ec2 setup.

Also: What @waja says.

Closed.
