### ISSUE TITLE
Enhance postgresql migration documentation

### ISSUE THREAD

**Issue by waja** [zammad/zammad-docker-compose#308]
#307 introduces a migration to a new postgresql version and so it is also necessary to migrate data into the new cluster. Actually there is a way documented by running a backup and restoring the data. Maybe this can be a bit more automated/semi scripted.

**Comment by waja** [comment]
Just for the beginning, the following worked to create a new volume with data ready for postgresql 15:

```
PSQL_BACKUP_VOL="zammad_postgresql-backup-data"; PSQL_NEW_VOL="zammad_postgresql-new-data"; \ 
docker volume create ${PSQL_BACKUP_VOL} && \
docker volume create ${PSQL_NEW_VOL} && \
docker container stop zammad_zammad-postgresql_1 && \
docker run --rm --volumes-from zammad_zammad-postgresql_1 -v ${PSQL_BACKUP_VOL}:/backup ubuntu sh -c "cp -a /var/lib/postgresql/data/* /backup/" && \
docker container start zammad_zammad-postgresql_1 && \
docker run --rm -v ${PSQL_BACKUP_VOL}:/var/lib/postgresql/9.6/data -v ${PSQL_NEW_VOL}:/var/lib/postgresql/15/data tianon/postgres-upgrade:9.6-to-15
```

It just needs to be changed to do the final steps.

**Comment by WWoodpecker** [comment]
Hi,

thanks for this input, but I became the error:
**connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  role "postgres" does not exist**


I needed to cahnge the last line to:
`docker run --rm -v ${PSQL_BACKUP_VOL}:/var/lib/postgresql/9.6/data -v ${PSQL_NEW_VOL}:/var/lib/postgresql/15/data tianon/postgres-upgrade:9.6-to-15 --username zammad`

Then it works!

**Comment by monotek** [comment]
Added a link to this ticket to the relase notes: https://github.com/zammad/zammad-docker-compose/releases/tag/v6.0.0

**Comment by Keridos** [comment]
> Hi,
> 
> thanks for this input, but I became the error: **connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL: role "postgres" does not exist**
> 
> I needed to cahnge the last line to: `docker run --rm -v ${PSQL_BACKUP_VOL}:/var/lib/postgresql/9.6/data -v ${PSQL_NEW_VOL}:/var/lib/postgresql/15/data tianon/postgres-upgrade:9.6-to-15 --username zammad`
> 
> Then it works!

It crashes later for me because the 15 server then crashes with the same error. Just with the following error message: 
`connection to server on socket "/var/lib/postgresql/.s.PGSQL.50432" failed: FATAL:  role "zammad" does not exist `

**Comment by WWoodpecker** [comment]
My installation was still very fresh, I had only been running zammad for a few weeks, it is currently not yet running productively... I am still working on the connection of Check_MK and i-doIT... Maybe the user "zammad" was the install user in the version I created? In my case there was no user "postgres" (I didn't know that was possible, I thought it was always there...) in the table, I created it and then I got the error that `postgres` is not the install user... With `--username zammad` it worked then.

**Comment by Keridos** [comment]
> My installation was still very fresh, I had only been running zammad for a few weeks, it is currently not yet running productively... I am still working on the connection of Check_MK and i-doIT... Maybe the user "zammad" was the install user in the version I created? In my case there was no user "postgres" (I didn't know that was possible, I thought it was always there...) in the table, I created it and then I got the error that `postgres` is not the install user... With `--username zammad` it worked then.

Oh it manages to connect to the postgresql 9.6 server. But then later it crashes when trying to connect to the 15 server even on a fresh try (removed temporary volumes) because the 15 server is initiated with the default user postgres, not zammad

**Comment by WWoodpecker** [comment]
OK, I understand... What I don't understand is that it doesn't work for you... It's been over a week now, but I don't know that I did anything else... Sorry.

**Comment by Keridos** [comment]
You need to add -`e "POSTGRES_INITDB_ARGS=-U zammad"` to the last docker run line. This creates the Postgresql cluster with a user/role named `zammad`.

**Comment by WWoodpecker** [comment]
That means your line is like this:

`docker run --rm -e "POSTGRES_INITDB_ARGS=-U zammad" -v ${PSQL_BACKUP_VOL}:/var/lib/postgresql/9.6/data -v ${PSQL_NEW_VOL}:/var/lib/postgresql/15/data tianon/postgres-upgrade:9.6-to-15 --username zammad`

**Comment by WWoodpecker** [comment]
If the community works together, we can solve all the problems. Let's hope that it runs smoothly for everyone else now.

**Comment by Keridos** [comment]
> That means your line is like this:
> 
> `docker run --rm -e "POSTGRES_INITDB_ARGS=-U zammad" -v ${PSQL_BACKUP_VOL}:/var/lib/postgresql/9.6/data -v ${PSQL_NEW_VOL}:/var/lib/postgresql/15/data tianon/postgres-upgrade:9.6-to-15 --username zammad`

Yes, that is the line now.

**Comment by waja** [comment]
> > That means your line is like this:
> > `docker run --rm -e "POSTGRES_INITDB_ARGS=-U zammad" -v ${PSQL_BACKUP_VOL}:/var/lib/postgresql/9.6/data -v ${PSQL_NEW_VOL}:/var/lib/postgresql/15/data tianon/postgres-upgrade:9.6-to-15 --username zammad`
> 
> Yes, that is the line now.

Okay ... I adjusted https://github.com/zammad/zammad-docker-compose/issues/308#issuecomment-1304302817 accordingly ...

**Comment by shagr4th** [comment]
Hi, I still have the 'FATAL: role "zammad" does not exist' message, even with all hints written here... not sure the tianon image is a working solution

**Comment by slajar** [comment]
Thanks for your script, but it does not work for me :/

Do you have an idea?

I created a small shell script from your command:
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/1584274/206153866-15b7b68d-2b1d-4e3a-8576-229d6310fb8c.png">

The only thing I had to change was the container name. That was for some reason: zammaddockercompose_zammad-postgresql_1 instead of zammad_zammad-postgresql_1


```
root@XXXXX:~/zammad-docker-compose# ./upgrade_postgres.sh
zammad_postgresql-backup-data
zammad_postgresql-new-data
zammaddockercompose_zammad-postgresql_1
zammaddockercompose_zammad-postgresql_1
Performing Consistency Checks
-----------------------------
Checking cluster versions                                   ok

connection to server on socket "/var/lib/postgresql/.s.PGSQL.50432" failed: FATAL:  role "zammad" does not exist

could not connect to source postmaster started with the command:
"/usr/lib/postgresql/9.6/bin/pg_ctl" -w -l "/var/lib/postgresql/15/data/pg_upgrade_output.d/20221207T102339.232/log/pg_upgrade_server.log" -D "/var/lib/postgresql/9.6/data" -o "-p 50432 -b  -c listen_addresses='' -c unix_socket_permissions=0700 -c unix_socket_directories='/var/lib/postgresql'" start
Failure, exiting

```

**Comment by slajar** [comment]
I even cannot login into the docker container for postgres. It seems it does not start the container because it find this incompatible data base.

`root@XXXXX:~/zammad-docker-compose# docker exec -it zammaddockercompose_zammad-postgresql_1 /bin/bash
OCI runtime exec failed: exec failed: unable to start container process: read init-p: connection reset by peer: unknown`

**Comment by rotanid** [comment]
@slajar i had the same issue today and after i while i fixed it by running the following:
`docker run --rm -e POSTGRES_USER=zammad -e POSTGRES_PASSWORD=zammad -e POSTGRES_DB=zammad -v zammad_postgresql-backup-data:/var/lib/postgresql/9.6/data -v zammad_postgresql-new-data:/var/lib/postgresql/15/data tianon/postgres-upgrade:9.6-to-15`

before running this, i needed to delete the content of the NEW data folder again.
afterwards, i also needed to adjust the new pg_hba.conf file.
then, i moved the new data folder to the place of the actual postgres container volume (after making a backup of the old data)

the postgresql container and the whole zammad docker compose stack works again for me now.

**Comment by slajar** [comment]
@rotanid thank you very much. Unfortunately, i broke my entire system by my latest trys. Now I am back on testing and I get this error:

<img width="502" alt="image" src="https://user-images.githubusercontent.com/1584274/206680166-5d38ac88-9788-4a94-a267-b2e945b2a41b.png">

any idea?

**Comment by waja** [comment]
@slajar I think you problem is not directly related to this topic. So please don't hijack this issue.

**Comment by slajar** [comment]
@waja well, it is not hijacking the issue. I went back to the latest commit of the docker_compose that is using postgres 9 from september and hence it worked. So there *must* be an issue with the postgres migration or the documentation.

**Comment by waja** [comment]
Or maybe just your environment.

**Comment by waja** [comment]
Keep open for now

**Comment by rotanid** [comment]
stalebot, reopen pls
