### ISSUE TITLE
Typo in v6.0.0 release migration guide

### ISSUE THREAD

**Issue by tribal2** [zammad/zammad-docker-compose#311]
There is a typo in the command to restore the database:
`docker exec -it postgres-restore bash -c "gunzip -kc /var/tmp/zammad/!!!ENTER_PSQL_FILE_NAME_FROM_COMMAND_ABOVE!!!_zammad_db.psql.gz | psql -U zammad" -d zammad_production`

```sh
psql -U zammad" -d zammad_production
              ^
              This quotation mark should be at the end
```

It should be:
`docker exec -it postgres-restore bash -c "gunzip -kc /var/tmp/zammad/!!!ENTER_PSQL_FILE_NAME_FROM_COMMAND_ABOVE!!!_zammad_db.psql.gz | psql -U zammad -d zammad_production"`

**Comment by migasQ** [comment]
Excellent obervation! I was wondering the whole time why the restored database was still empty...

**Comment by monotek** [comment]
Thanks! The release notes have been updated :)

https://github.com/zammad/zammad-docker-compose/releases/tag/v6.0.0
