### ISSUE TITLE
webhooks between docker stacks

### ISSUE THREAD

**Issue by stefangweichinger** [zammad/zammad-docker-compose#312]
# Infos

* Docker version: 18.06.1-ce
* Docker-compose version: 1.13.0, build 1719ceb
* Operating system (Docker host): Photon OS

I have a stack running zammad and a stack running an instance of 

https://github.com/webhooksite/webhook.site

Both run on the same docker host 192.168.97.160

Zammad is run behind HAproxy on a pfsense and reachable worldwide with a working https:// URL (using LetsEncrypt).

Configured a webhook plus a trigger in Zammad, the logs in Zammad show that the webhook is triggered, but I don't see the request in the "webhook.site" GUI. Testing from my browser or local PC (curl) works fine.

So the question is: do I have to do anything special to the Zammad Docker stack to allow these outgoing requests maybe?

# Expected behavior

* webhooks created and triggered in Zammad show up in the webhook test site

# Actual behavior

* no requests get to the test "receiver"

# Steps to reproduce the behavior

* set up zammad docker-compose stack
* set up webhook.site as in https://github.com/webhooksite/webhook.site/blob/master/docker-compose.yml
* set up matching webhook in zammad, example: http://192.168.97.160:8084/0ad520c0-be1e-4f23-b488-bee8f3db1933
* set up trigger to trigger that webhook (everytime a ticket is edited, for first test)
* edit ticket
* wait for request to show up in "webhook.site" container

Sorry if I ask something obvious, I am new to webhooks ...

**Comment by MrGeneration** [comment]
One side note from my end, the scheduler container log will not be useful put the railsservers.

**Comment by MrGeneration** [comment]
Oh I see you've chosen duplicate locations for your question.
I'll be closing this issue for the favor of the community post at https://community.zammad.org/t/docker-compose-environment-webhooks/10396
