### ISSUE TITLE
postgresql database files are incompatible with server

### ISSUE THREAD

**Issue by Massimo-B** [zammad/zammad-docker-compose#315]
On OpenSuse LEAP 15.4 I try to install a recent Zammad by docker-compose.

I currently have
commit ae716aed3d9af86508abe9b9d10ba701ce46e288 (HEAD -> master, origin/master, origin/HEAD)
Author: André Bauer <monotek@users.noreply.github.com>
Date:   Wed Nov 23 00:39:57 2022 +0100

I did `docker-compose up -d` and got this postgres container:
`f057b68bdcfd   postgres:15.1-alpine                   "docker-entrypoint.s…"   24 hours ago   Restarting (1) 39 seconds ago                                               zammad-docker-compose_zammad-postgresql_1`
Why it's always restarting?
Logs say
```
2022-11-29 12:18:32.832 UTC [1] FATAL:  database files are incompatible with server
2022-11-29 12:18:32.832 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 9.6, which is not compatible with this version 15.1
```

**Comment by Mercer612** [comment]
Perform postgres update via this guide.
https://github.com/zammad/zammad-docker-compose/releases/tag/v6.0.0

Worked like a charm (I had to make some cruthces [as I storing my pgdata in a folder on host, not in a volume] but I've updated successfully from 5.2.x to 5.3.0-2

**Comment by MrGeneration** [comment]
Please don#t open your technical questions on several places.
This originally appeared on the community https://community.zammad.org/t/docker-compose-postgresql-database-files-are-incompatible-with-server/10471

I'm closing this as you've received your answer.
