### ISSUE TITLE
Invalid format of target version: `VERSION=5.3.0-9`

### ISSUE THREAD

**Issue by eugenewere** [zammad/zammad-docker-compose#319]
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
initialising / updating database...
I, [2022-12-06T10:16:15.712251 #22-8280]  INFO -- : Using memcached as Rails cache store.
I, [2022-12-06T10:16:15.712567 #22-8280]  INFO -- : Using Redis as web socket session store.
Database 'zammad_production' already exists
I, [2022-12-06T10:16:17.916980 #23-8280]  INFO -- : Using memcached as Rails cache store.
I, [2022-12-06T10:16:17.917128 #23-8280]  INFO -- : Using Redis as web socket session store.
rake aborted!
Invalid format of target version: `VERSION=5.3.0-9`
/usr/local/bundle/gems/activerecord-6.1.7/lib/active_record/tasks/database_tasks.rb:263:in `check_target_version'
/usr/local/bundle/gems/activerecord-6.1.7/lib/active_record/tasks/database_tasks.rb:232:in `migrate'
/usr/local/bundle/gems/activerecord-6.1.7/lib/active_record/railties/databases.rake:92:in `block (3 levels) in <main>'
/usr/local/bundle/gems/activerecord-6.1.7/lib/active_record/railties/databases.rake:90:in `each'
/usr/local/bundle/gems/activerecord-6.1.7/lib/active_record/railties/databases.rake:90:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
initialising / updating database...
I, [2022-12-06T10:16:32.196905 #21-8280]  INFO -- : Using memcached as Rails cache store.
I, [2022-12-06T10:16:32.197127 #21-8280]  INFO -- : Using Redis as web socket session store.
Database 'zammad_production' already exists
I, [2022-12-06T10:16:34.441905 #22-8280]  INFO -- : Using memcached as Rails cache store.
I, [2022-12-06T10:16:34.442040 #22-8280]  INFO -- : Using Redis as web socket session store.
rake aborted!
Invalid format of target version: `VERSION=5.3.0-9`
/usr/local/bundle/gems/activerecord-6.1.7/lib/active_record/tasks/database_tasks.rb:263:in `check_target_version'
/usr/local/bundle/gems/activerecord-6.1.7/lib/active_record/tasks/database_tasks.rb:232:in `migrate'
/usr/local/bundle/gems/activerecord-6.1.7/lib/active_record/railties/databases.rake:92:in `block (3 levels) in <main>'
/usr/local/bundle/gems/activerecord-6.1.7/lib/active_record/railties/databases.rake:90:in `each'
/usr/local/bundle/gems/activerecord-6.1.7/lib/active_record/railties/databases.rake:90:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
initialising / updating database...

**Comment by MrGeneration** [comment]
Sorry but please use the provided template.

**Comment by eugenewere** [comment]
ENV FILE

`IMAGE_REPO=zammad/zammad-docker-compose
MEMCACHE_SERVERS=zammad-memcached:11211
POSTGRES_PASS=zammad
POSTGRES_USER=zammad
REDIS_URL=redis://zammad-redis:6734
RESTART=unless-stopped
VERSION=5.3.0-9
#VERSION=latest

ELASTICSEARCH_ENABLED=true
ELASTICSEARCH_HOST=elasticsearch
ELASTICSEARCH_PORT=9200
ELASTICSEARCH_SCHEMA=http
ELASTICSEARCH_NAMESPACE=zammad
ELASTICSEARCH_REINDEX=true
ELASTICSEARCH_SSL_VERIFY=true

POSTGRESQL_HOST=zammad-postgresql
POSTGRESQL_PORT=5432
POSTGRESQL_USER=zammad
POSTGRESQL_PASS=zammad
POSTGRESQL_DB=zammad_production
POSTGRESQL_DB_CREATE=true`

**Comment by eugenewere** [comment]
The error is on zammad-init container
even with latest image or 5.3.0-11
