### ISSUE TITLE
Avoid duplicate configuration in docker-compose.yml and docker-compose-build.yml

### ISSUE THREAD

**Issue by t3easy** [zammad/zammad-docker-compose#32]
docker-compose is able to override/concatenate multiple configurations.
https://docs.docker.com/compose/extends/#example-use-case
ATM. moste of the configuration of docker-compose.yml and docker-compose-build.yml are the same.
This could be avoided by build with
docker-compose -f docker-compose.yml -f docker-compose-build.yml

Configuration that must not be set for build could be moved to docker-compose.override.yml as it is loaded by default if no docker-compose file is specified to load.

**Comment by monotek** [comment]
Not sure how this works for vars you need only in the one or in the other container (image & build).

Not sure when I have time to try it out. So pullrequest is welcome ;-)

**Comment by monotek** [comment]
removed docker-compose-build.yml. closing.
