### ISSUE TITLE
 Upgrade failed with docker compose: “/usr/local/bin/backup.sh”: permission denied: unknown 

### ISSUE THREAD

**Issue by undee123** [zammad/zammad-docker-compose#324]
# Infos

* Docker version: 20.10.22
* Docker-compose version: 1.21.0
* Operating system (Docker host): Debian 10 Buster

# Expected behavior

* upgrading Zammad from 5.2.3.18 to 5.3.1-6 with docker compose (portainer stack)

# Actual behavior

* When stopping the stack in portainer and using newest docker-composer.yml and .env file deployment fails with the following error:
* `failed to deploy a stack: Container zammad-zammad-redis-1 Recreate Container zammad-zammad-memcached-1 Recreate Container zammad-zammad-elasticsearch-1 Recreate Container zammad-zammad-postgresql-1 Recreate Container zammad-zammad-redis-1 Recreated Container zammad-zammad-postgresql-1 Recreated Container zammad-zammad-init-1 Recreate Container zammad-zammad-init-1 Recreated Container zammad-zammad-elasticsearch-1 Recreated Container zammad-zammad-memcached-1 Recreated Container zammad-zammad-railsserver-1 Recreate Container zammad-zammad-railsserver-1 Recreated Container zammad-zammad-nginx-1 Recreate Container zammad-zammad-scheduler-1 Recreate Container zammad-zammad-websocket-1 Recreate Container zammad-zammad-backup-1 Recreate Container zammad-zammad-scheduler-1 Recreated Container zammad-zammad-websocket-1 Recreated Container zammad-zammad-nginx-1 Recreated Container zammad-zammad-backup-1 Recreated Container zammad-zammad-redis-1 Starting Container zammad-zammad-postgresql-1 Starting Container zammad-zammad-memcached-1 Starting Container zammad-zammad-elasticsearch-1 Starting Container zammad-zammad-memcached-1 Started Container zammad-zammad-postgresql-1 Started Container zammad-zammad-init-1 Starting Container zammad-zammad-redis-1 Started Container zammad-zammad-railsserver-1 Starting Container zammad-zammad-elasticsearch-1 Started Container zammad-zammad-init-1 Started Container zammad-zammad-railsserver-1 Started Container zammad-zammad-websocket-1 Starting Container zammad-zammad-backup-1 Starting Container zammad-zammad-scheduler-1 Starting Container zammad-zammad-nginx-1 Starting Container zammad-zammad-websocket-1 Started Container zammad-zammad-nginx-1 Started Container zammad-zammad-scheduler-1 Started Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/local/bin/backup.sh": permission denied: unknown`

Don’t know if the missing backup.sh file will be the cause of this error, anyway that file should exist as I make an update of zammad and not a new instalation.

Any hint? Thanks in advance!!!

**Comment by MrGeneration** [comment]
Also posted on https://community.zammad.org/t/upgrade-failed-with-docker-compose-usr-local-bin-backup-sh-permission-denied-unknown/10651 to keep people busy.

**Comment by undee123** [comment]
Nope, deleted because it's not a Zammad issue

**Comment by MrGeneration** [comment]
If it's not a Zammad issue, why post in a Zammad repository? :)

**Comment by t3easy** [comment]
The backup.sh file is mountet to the container and not content of the image anymore.
https://github.com/zammad/zammad-docker-compose/blob/master/docker-compose.yml#L22

Previously the postgres image was build in this repo.

You have to build an image with the file by yourself and delploy this image.

**Comment by t3easy** [comment]
> > The backup.sh file is mountet to the container and not content of the image anymore.
> 
> Sorry for my lack of knowledge, but how do we get that file? Simply delete the line in the "docker-compose.yml"-file doesn't work; after running "docker compose up -d", the Shell says:
> 
> > Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/local/bin/backup.sh": stat /usr/local/bin/backup.sh: no such file or directory: unknown
> 
> What are we supposed to do about that "backup.sh"-file?

Hi @Astorek86,
the file is https://github.com/zammad/zammad-docker-compose/blob/master/scripts/backup.sh.
Before the changes (https://github.com/zammad/zammad-docker-compose/releases/tag/v6.0.0), the file was part of the custom PostgeSQL image. After the change, you have to build own postgres image or store the file on the hosts.

I'm not happy with the decision to remove the zammad postgres image either, but that's the current situation.

**Comment by t3easy** [comment]
> > The backup.sh file is mountet to the container and not content of the image anymore.
> 
> Sorry for my lack of knowledge, but how do we get that file? Simply delete the line in the "docker-compose.yml"-file doesn't work; after running "docker compose up -d", the Shell says:
> 
> > Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/local/bin/backup.sh": stat /usr/local/bin/backup.sh: no such file or directory: unknown
> 
> What are we supposed to do about that "backup.sh"-file?

Hi @Astorek86,
the file is https://github.com/zammad/zammad-docker-compose/blob/master/scripts/backup.sh.
Before the changes (https://github.com/zammad/zammad-docker-compose/releases/tag/v6.0.0), the file was part of the custom postgesql image. After the change, you have to build own postgres image or store the image on the hosts.

I'm not happy with the decision to remove the zammad postgres image either, but that's the current situation.
