### ISSUE TITLE
New elasticsearch container reboots after update

### ISSUE THREAD

**Issue by t3easy** [zammad/zammad-docker-compose#33]
### Infos:

* Docker version: 17.06
* Docker-compose version: 1.14.0
* Operating system (Docker host): Ubuntu 16.04

### Expected behavior:

* Changed elasticsearch container starts w/o problems

### Actual behavior:

* The container reboots with org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [[/usr/share/elasticsearch/data/docker-cluster]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?

### Steps to reproduce the behavior:

* Update from previous docker-compose with elasticsearch image to docker.elastic.co/elasticsearch/elasticsearch:5.5.0  

I think it's an permission issue inside the volume. Will check that.

**Comment by t3easy** [comment]
I got this run but it's a little tricky:

1. Define a named volume for elasticsearch (see https://github.com/zammad/zammad-docker-compose/pull/35/commits/0bbf8bc53c00c56d88840251d0008da22b9e524c)
1. Override the command of elasticsearch, e.g. add `command: sleep 10m` to the service
1. `docker-compose up -d zammad-elasticsearch`
1. Search for the volume that holds your es db `docker volume ls` it's one of the unnamed with long id.
1. Search for the new named volume that fits your docker-compose dir name + service, e.g. `zammaddockercompose_data-elasticsearch`
1. run a container with both volumes:
`docker run -it --rm -v zammaddockercompose_data-elasticsearch:/target -v b5e86a91e71bc438b09e22572ff73c3a91f7d3d8436fd66dccd0cb77b2bc2111:/source alpine /bin/sh`
1. Copy the content of the source to the target, you should have a folder /target/nodes/ after that.
1. `exit` the container
1. run a shell in the es container `docker-compose exec -u root zammad-elasticsearch /bin/bash`
1. change to the es data dir `cd /usr/share/elasticsearch/data/`
1. chmod the folder `chown -R elasticsearch:elasticsearch .`
1. `exit` the container
1. remove the `command: sleep 10m` from your docker-compose
1. recreate the es container `docker-compose up -d zammad-elasticsearch`

**Comment by monotek** [comment]
Should not be a problem anymore...
