### ISSUE TITLE
Zammad 6.0 will introduce a new `var/` folder that should be shared in clusters

### ISSUE THREAD

**Issue by mgruner** [zammad/zammad-docker-compose#331]
[This commit](https://github.com/zammad/zammad/commit/9f94aff088932138e6cfba216c28f3769915240c) changes the storage location for unprocessable / oversized emails. The location of such emails changed from `tmp/unprocessable_mail` and `tmp/oversized_mail` to `var/spool/unprocessable_mail` and `var/spool/oversized_mail` within the `/opt/zammad` directory. Existing emails are automatically moved to the new location.

This new `var/` folder [is supposed to be shared in cluster instances](https://github.com/zammad/zammad/blob/develop/var/README.md) and should hold all relevant, non-volatile data in future. Our idea is that the rest of the file system should not need to be shared for better scalability, but `var/` must.

The intention of this issue is to inform about the upcoming change. Is there anything we can provide for zammad-docker-compose or zammad-helm for that? I'm not sure if anything needs to be changed right now because `/opt/zammad` is already completely shared, but in future it might become relevant if that sharing is no longer done. 

Please let us know. Thank you!

**Comment by monotek** [comment]
Sounds good to me.
We could use this opportunity to change the dockerfile in a way where we can skip the whole rsync part and have /opt/zammad read only.

Only thing which needs to be sure is that not other data is written withing /opt/zammad. 
What about Gravatar / user profiel pictures?
Is such stuff already put in the db?
If not, can this be enforced by some setting?
Is there such data in the filesystem left, is it migrated automatically when the setting is changed?

Whats the timeframe for this / zammad 6.0?

**Comment by mgruner** [comment]
Sounds like a great plan. What about `zammad-docker`, can we drop that as well then?

I am not currently aware of any data that Zammad stores in the file system by default (except for web socket and cache which are already configured to Redis / Memcached in the containers). 

Avatars use the storage backend in Zammad, which is Database by default. It might be that local caches are created for files served to the client, but that is volatile data that can be re-generated. Do you have any specific directory in mind that I could check?

There is no date yet, but we try to aim for May/June, so rather soon.

**Comment by monotek** [comment]
zammad-docker could be set to archived already, adding a note like: "not supported anymore - use zammad-docker-compose repo".

After the recent docker inc open source fuckup we might want to switch to quay.io too.
I've alread claimed https://quay.io/repository/zammad/zammad a while ago, so we could use that repo in the future, also removing the "docker-compose" part, from the docker repo :)

I'll add some changes to the docker build action later, so that docker images are also pushed to quay.io, before we're goin 6.0, so we can just switch then.

If we wan't to have the old images available, we could use something like: 
* https://github.com/google/go-containerregistry/tree/main/cmd/crane
* https://medium.com/@spurin/copying-container-images-between-container-registries-e7b734abc701



No, i had no special dirs in mind. Just were unsure if there is anything left in he filesystem :)


Timeframe sound managable for me :)

**Comment by mgruner** [comment]
@monotek we were also surpised about Docker recently. Moving to quay sounds like a good plan. Would you be so kind to add my user "mrtngrnr" to the zammad organization there?

I guess if the 'old' images stay available on docker hub at least for a certain time, it should be sufficient.

**Comment by waja** [comment]
How about looking to into also publishing to Github? https://blog.alexellis.io/docker-is-deleting-open-source-images/#:~:text=Start%20publishing%20images%20to%20GitHub

**Comment by mgruner** [comment]
@waja do you have information about possible storage/traffic limits there? I only found https://github.com/features/packages#pricing which indicates a 500 MB storage limit for free accounts (which would of course not be an option). If this is safe, GitHub is preferable for us because we already use it.

**Comment by waja** [comment]
No I don't. But packages are not the same as GHCR.
What I do is publishing to Docker Hub and GHCR by one Github Action. This can be also implemented for much more registries. It's far from perfect, but you can get inspiration by https://github.com/waja/docker-calcardbackup/blob/development/.github/workflows/docker.image.yml#L179 maybe.

**Comment by mgruner** [comment]
Found something: https://docs.github.com/en/billing/managing-billing-for-github-packages/about-billing-for-github-packages#about-billing-for-github-packages

> GitHub Packages usage is free for public packages.

I guess this applies since https://ghcr.io redirects to https://github.com/features/packages.

**Comment by mgruner** [comment]
FYI, `zammad-docker` was archived as suggested above.

**Comment by monotek** [comment]
We have now docker images on:

https://github.com/zammad/zammad/pkgs/container/zammad
https://hub.docker.com/r/zammad/zammad/tags
https://hub.docker.com/r/zammad/zammad-docker-compose/tags
https://quay.io/repository/zammad/zammad?tab=tags

@mgruner 
I'm on vacation next 2 weeks.
How does the 6.0 release schedule lokks like now? 
More towards may or june?

**Comment by waja** [comment]
> Current builds of our docker image are going now to:
> 
> https://github.com/zammad/zammad/pkgs/container/zammad

this seems broken

**Comment by monotek** [comment]
what exactly?
lgtm.

**Comment by waja** [comment]
> what exactly?
> 
> lgtm.

The URL has a 404. :/

**Comment by monotek** [comment]
Hmm. Works for me 🤷‍♂️
Not sure if GitHub issue or some permission thing.

Does this work?

```
docker pull ghcr.io/zammad/zammad:5.4.1-29
```

**Comment by waja** [comment]
> Does this work?
> 
> ```
> docker pull ghcr.io/zammad/zammad:5.4.1-29
> ```

```
✦ ❯ docker pull ghcr.io/zammad/zammad:5.4.1-29

Error response from daemon: Head "https://ghcr.io/v2/zammad/zammad/manifests/5.4.1-29": denied: denied
```

**Comment by monotek** [comment]
Do you have done a "docker login" before, using your username and a private token, with "read:packages" permission?

**Comment by waja** [comment]
why should I do this? is ghcr.io/zammad/zammad private?

**Comment by monotek** [comment]
Imho quay.io and ghcr.io require a login, or not?
I'll check after my vacation.

**Comment by waja** [comment]
> Imho quay.io and ghcr.io require a login, or not?
> 
> I'll check after my vacation.

At least GHCR does not require login for public registries/project. None of mine does. ;)

**Comment by aniston** [comment]
sorry to jump in with this offtopic question, but linux/arm64 builds were not possible till date for Zammad 5.x (seems that there is a Rails issue with building for arm64) with Zammad 6.0 will there be any chance of an arch=arm64 build ?
- also is there a Dockerfile available to try and build the docker images myself (i'm using [Hetzner ](https://www.hetzner.com/cloud)VPS with ARM Ampere)

**Comment by MrGeneration** [comment]
> sorry to jump in with this offtopic question, but linux/arm64 builds were not possible till date for Zammad 5.x (seems that there is a Rails issue with building for arm64) with Zammad 6.0 will there be any chance of an arch=arm64 build ?

Please open your own issues instead of hijacking others, thank you.

**Comment by aniston** [comment]
> Please open your own issues instead of hijacking others, thank you.

sorry to have asked here. i guess i was just too eager!
 my apologies for this, i have deleted the comment.

**Comment by monotek** [comment]
> > Imho quay.io and ghcr.io require a login, or not?
> > I'll check after my vacation.
> 
> At least GHCR does not require login for public registries/project. None of mine does. ;)

@mgruner can you check github docker repo permissions please?

**Comment by mgruner** [comment]
@monotek where can I do that? If it's on organization level, I probably don't have the rights for it.

**Comment by monotek** [comment]
I guess we have to check: https://github.com/users/zammad/packages/container/zammad/settings

**Comment by mgruner** [comment]
Thanks for the hint @monotek. The package is changed to visibility "public" now.

**Comment by waja** [comment]
https://github.com/zammad/zammad/pkgs/container/zammad/ looks good now

**Comment by monotek** [comment]
will be fixed in: https://github.com/zammad/zammad-docker-compose/pull/347
