### ISSUE TITLE
I am facing this issue again. Was this resolved? https://github.com/zammad/zammad-docker-compose/issues/117#issue-495753031

### ISSUE THREAD

**Issue by mr2chethan** [zammad/zammad-docker-compose#336]
This must be same as https://github.com/zammad/zammad-docker-compose/issues/117

Docker init container is logging this error:
sed: -e expression #4, char 42: unknown option to `s'
My postgres password contains #

How can this be fixed?

Error in https://github.com/zammad/zammad-docker-compose/blob/master/containers/zammad/docker-entrypoint.sh#L47

Ideally it should allow arbitrary passwords -> good note would be to inform what chars can be used so the sed command still works

Infos:
Docker version: ?
Docker-compose version: ?
Operating system (Docker host): ECS
(not related to docker, but the docker-entrypoint file)

Expected behavior:
Accept "#" as special char for passwords
Actual behavior:
sed: -e expression #2, char 39: unknown option to s'`
setup a different password for postgre and use "#" within it

**Comment by MrGeneration** [comment]
Duplicate of #117
