### ISSUE TITLE
Zammad init container is throwing error: sed: -e expression #4, char 42: unknown option to `s'  while trying to run Zammad docker compose without elastic search, memcached, redis, nginx, websocket and trying to connect to external postgresql through SSH tunnel port forwarding to RDS of EKS of AWS.

### ISSUE THREAD

**Issue by mr0chethan** [zammad/zammad-docker-compose#337]
# Infos

* Docker version: 20.10.22
* Docker-compose version: v2.15.1
* Operating system (Docker host): Mac M1 Ventura 13.1

# Expected behavior

*  Zammad docker compose should run without elastic search, memcached, redis, nginx, websocket and should be able to connect to external postgresql.

# Actual behavior
*  Zammad init container is throwing error: sed: -e expression # 4, char 42: unknown option to `s'

# Steps to reproduce the behavior

*Do SSH tunnel for port forwarding to remote host RDS of EKS of AWS.
*Remove Zammad backup, elastic search, memcached, redis, nginx, websocket  and postgresql services from docker-compose.yml
*Map port of host to rails server
*give POSTGRESQL_HOST=host.docker.internal and other Postgres related data in the .env

`---
version: '3'

services:

  zammad-init:
    command: ["zammad-init"]
    environment:
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
      - POSTGRESQL_DB=${POSTGRESQL_DB}
      - POSTGRESQL_DB_CREATE=${POSTGRESQL_DB_CREATE}
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASS=${POSTGRESQL_PASS}
      - ELASTICSEARCH_ENABLED=false
    image: ${IMAGE_REPO}:${VERSION}
    platform:  linux/amd64
    restart: always
    volumes:
      - zammad-data:/opt/zammad

  zammad-railsserver:
    command: ["zammad-railsserver"]
    ports:
      - "3000:3000"
    environment:
      - ZAMMAD_RAILSSERVER_HOST=localhost
      - ZAMMAD_RAILSSERVER_PORT=3000
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
      - POSTGRESQL_DB=${POSTGRESQL_DB}
      - POSTGRESQL_DB_CREATE=${POSTGRESQL_DB_CREATE}
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASS=${POSTGRESQL_PASS}
    image: ${IMAGE_REPO}:${VERSION}
    platform:  linux/amd64
    restart: ${RESTART}
    volumes:
      - zammad-data:/opt/zammad

volumes:
  zammad-data:
    driver: local`

**Comment by mr2chethan** [comment]
Looks like this issue was because sed couldn't parse some special character in my password. After changing my password, this this issue is resolved. This must be same as #336 and #117
