### ISSUE TITLE
New elasticsearch container has no volume

### ISSUE THREAD

**Issue by t3easy** [zammad/zammad-docker-compose#34]
The old elasticsearch image has a volume to persists it's DB:
https://github.com/docker-library/elasticsearch/blob/4369e593bab8b19ea5dc06d70cc2039c3460af46/5/Dockerfile#L60
The new hasn't:
https://github.com/elastic/elasticsearch-docker/blob/master/templates/Dockerfile.j2

This leads to data loss during recreates the containers.

**Comment by monotek** [comment]
Not completely true as the index is recreated on every (re)start anyway.
