### ISSUE TITLE
invalid date during Backup and multiple backup files created

### ISSUE THREAD

**Issue by lcx** [zammad/zammad-docker-compose#349]
This is not a bug, but hope it might help other out who like me didn't notice the change from `BACKUP_SLEEP` to `BACKUP_TIME` even though it's clearly stated in the commit and also my diff between the files showed this line and for some reason I ignored it. 
if you see in the backup container logs 

`date: invalid date '2023-06-13 '` 

then you need to update the `.env` to include the new `BACKUP_TIME` which is described [here](https://github.com/zammad/zammad-docker-compose/commit/281b5f317f37a41d3e1827d9e266379a3886d442#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3L13)
Only happened since I needed to do some network changes in the compose file due to weird MTU requirements.

**Comment by mgruner** [comment]
Thanks for the hint @lcx
