### ISSUE TITLE
How to update zammad 5.4 to 6 ? 

### ISSUE THREAD

**Issue by sas2402** [zammad/zammad-docker-compose#356]
* Docker version:  20.10.21
* Docker-compose version:  1.25.0
* Operating system (Docker host): Ubuntu 20.04.6 LTS 

How to update zammad 5.4 to 6 ? 

Where can I see instructions? Thank you.

**Comment by fliebe92** [comment]
Hi there! Recently, there was a small change that could solve the reported behavior here: https://github.com/zammad/zammad/commit/6dc6b0fae5089a7a81b1a5f107f972b9ca279247

**Comment by pgassmann** [comment]
The current docker-compose.yml is broken. Postgresql client config is missing.
See: https://github.com/zammad/zammad-docker-compose/pull/357

Also upgrade to version 6 requires manual migration of the data. see https://github.com/zammad/zammad-docker-compose/issues/348#issuecomment-1609202582

**Comment by mgruner** [comment]
Solved by [7f31a9a](https://github.com/zammad/zammad-docker-compose/commit/7f31a9acfc19c970bdf1b1014946d862fe19f5fe).
