### ISSUE TITLE
Backup is constantly running

### ISSUE THREAD

**Issue by xjimbob** [zammad/zammad-docker-compose#359]
# Infos

* Docker version: 23.0.0
* Docker-compose version: 2.15.1
* Operating system (Docker host): Ubuntu 22.04.2 LTS

# Expected behavior

* The backup should run at the time specified in the docker compose. It is the default BACKUP_TIME=03:00.

# Actual behavior

* The backup is running constantly. These are the logs:

> 20230702225212 - backuping zammad...
> tar: removing leading '/' from member names
> backup finished :)
> sleep: invalid number ''
> 20230702225314 - backuping zammad...
> tar: removing leading '/' from member names
> backup finished :)
> sleep: invalid number ''
> 20230702225416 - backuping zammad...
> tar: removing leading '/' from member names
> backup finished :)
> sleep: invalid number ''
> 20230702225518 - backuping zammad...
> tar: removing leading '/' from member names
> backup finished :)
> sleep: invalid number ''
> 20230702225620 - backuping zammad...
> tar: removing leading '/' from member names
> backup finished :)
> sleep: invalid number ''

I set it back to what I used prior to updating to 6.0 which was BACKUP_SLEEP=86400 and it is not constantly updating now. Is there a difference between using either or?

# Steps to reproduce the behavior

* Update to 6.0?

**Comment by kamilkobak** [comment]
add:
```
  zammad-backup:
    environment:
      - BACKUP_SLEEP=86400
```

in docker-compose.yml
