### ISSUE TITLE
Zammad Backup - Failed to get D-Bus connection

### ISSUE THREAD

**Issue by MNobis** [zammad/zammad-docker-compose#37]
### Infos:

* Docker version: 17.05.0-ce
* Docker-compose version: 1.14.0
* Operating system (Docker host): Ubuntu 16.04

### Expected behavior:

* I want to make a backup with the zammad-backup container and restore ist again.

### Actual behavior:

From inside the container I call the zammad_restore.sh script.

root@8356517f7b8b:/home/zammad/contrib/backup# ./zammad_restore.sh
 Zammad restored started - Tue Aug  8 10:28:31 UTC 2017!
The restore will delete your current config and database!
Be sure to have a backup available!

Enter 'yes' if you want to proceed!
Restore?: yes
Enter file date to restore:
20170803134310
[...]
20170807132335
File date: 20170807132335
Enter db date to restore:
20170803134310
[...]
20170807132335
DB date: 20170807132335
 Stopping Zammad
**Failed to get D-Bus connection: Unknown error -1**
 Restoring Files
 Restoring PostgrSQL DB
No passwd entry for user 'postgres'
 Starting Zammad
**Failed to get D-Bus connection: Unknown error -1**
Zammad restored successfully - Tue Aug  8 10:28:42 UTC 2017!

As you could see, I am not able to restore a Backup due to the D-Bus connection Error.

Is this a problem in the restore script itself or did the way to restore changed with the new container? 
I could not find any documentation besides the one at https://docs.zammad.org/en/latest/appendix-backup-and-restore.html 

kind regards

**Comment by monotek** [comment]
The restore script is node made to be run from the container. Check the dockerfiles to see how the backup is created.

**Comment by MNobis** [comment]
So, what is the intended way to restore a backup.
There is no documentation and the way the backup was created it can not be restored.

**Comment by monotek** [comment]
Do it by hand:
* stop Zammad container
* copy zammad files to Zammad data volume
* Copy SQL file to postgres volume
* Enter postgres container
* Restore the database
* Restart Zammad container
