### ISSUE TITLE
zammad-init keeps restarting with DB connection error

### ISSUE THREAD

**Issue by distributev** [zammad/zammad-docker-compose#375]
I searched the previous issues and I know that there were some fixes to correctly pass the DB/Memcached/Redis env variables to containers. 

Basically I use the latest version of docker-compose.yml and I also filled the .env with correct values.

After I apply the latest changes, zammad-init keeps restarting with the error 

Caused by:
PG::ConnectionBad: FATAL:  password authentication failed for user 

I have passed the following env variables to zammad-init

 environment:
      - MEMCACHE_SERVERS=${MEMCACHE_SERVERS}
      - POSTGRESQL_DB=${POSTGRES_DB}
      - POSTGRESQL_HOST=${POSTGRES_HOST}
      - POSTGRESQL_USER=${POSTGRES_USER}
      - POSTGRESQL_PASS=${POSTGRES_PASS}
      - POSTGRESQL_PORT=${POSTGRES_PORT}
      - REDIS_URL=${REDIS_URL}

Zammad postgre-sql has the following env variables passed

 environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}

**Comment by mgruner** [comment]
@distributev thanks for your report. I just verified that with the default files of zammad-docker-compose, it works correctly, even with a custom PG username and password.
Can you give us more information about your setup, to bring us into a position to reproduce the problem?

For support requests, please head over to https://community.zammad.org/

**Comment by kale1d0code** [comment]
it may be related to a problem I had.
at some stage zammad switched to using a url connection for the database.

you may want to try urlencoding your password environment variable

**Comment by mgruner** [comment]
This is not enough information for us to reproduce the issue, sorry.
