### ISSUE TITLE
update from 6.0.0 to 6.1.0 loses database (asks to setup new system)

### ISSUE THREAD

**Issue by kale1d0code** [zammad/zammad-docker-compose#377]
# Infos
I've finished updating our zammad instance from 6.0.0 to 6.1.0
after the init step has finished and navigating to the login screen I am presented with the options to setup a new helpdesk instead of continuing to use the data from 6.0.0

* Docker version: 24.0.6
* Docker-compose version: 24.0.6
* Operating system (Docker host): Centos

# Expected behavior
System to show login screen or log straight into the agent view
*

# Actual behavior
System is asking me to set it up for the first time
*

# Steps to reproduce the behavior
update from 6.0.0 to 6.1.0
*

the only other difference I can think of is I've moved from the dockerhub.io images to the ghcr.io ones

**Comment by kale1d0code** [comment]
I swapped out my compose file for the latest version on this repo.
I didn't realise I didn't put the custom database name that was being used before.

everything works as expected.
closing this now.

**Comment by mgruner** [comment]
Nice, thanks for the update.
