### ISSUE TITLE
Search not working 

### ISSUE THREAD

**Issue by bols1992** [zammad/zammad-docker-compose#378]
# Infos

Search not working in Zammad,

* Docker version:  v24.0.6
* Docker-compose version: v2.21.0
* Operating system (Docker host): Ubuntu

# Actual behavior

Output of the docker-zammad-scheduler

[2023-09-18T21:04:13.578836#1-64780] ERROR -- : Unable to process post request to elasticsearch URL 'http://zammad-elasticsearch:9200/zammad_production_ticket/_doc/6?pipeline=zammad7f31e253-052a-472c-a7d4-0f74e48b9f75'. Check the response and payload for detailed information:

Response:
#<UserAgent::Result:0x00007ff6c0debf98 @success=false, @body="{\"error\":{\"root_cause\":[{\"type\":\"illegal_argument_exception\",\"reason\":\"pipeline with id [zammad7f31e253-052a-472c-a7d4-0f74e48b9f75] does not exist\"}],\"type\":\"illegal_argument_exception\",\"reason\":\"pipeline with id [zammad7f31e253-052a-472c-a7d4-0f74e48b9f75] does not exist\"},\"status\":400}", @data=nil, @code="400", @content_type=nil, @error="Client Error: #<Net::HTTPBadRequest 400 Bad Request readbody=true>!", @header={"x-elastic-product"=>"Elasticsearch", "content-type"=>"application/json", "content-length"=>"289"}>

# Steps to reproduce the behavior

**Comment by MrGeneration** [comment]
Please provide your compose configuration.
Especially overrides and such.

**Comment by waja** [comment]
How about the output of `docker compose -f <files> config`? ;)

**Comment by bols1992** [comment]
Hi,

i checked the complete docker-compose file and it was my mistake that I didn't have the zammad-var volume in the docker file or that I deleted it

After I added this the search worked

**Comment by michel-thomas** [comment]
Hello @bols1992 

I ran in the same problem with my old 5.4.1 Zammad version. Could you be more precise about which var were missing in your docker-compose ? If you still remember…

Thanks
