### ISSUE TITLE
Zammad-NGINX can not write config file due to read-only

### ISSUE THREAD

**Issue by strifel** [zammad/zammad-docker-compose#381]
# Infos

* Docker version: 24.0.6
* Docker-compose version: 2.11.1
* Operating system (Docker host): Ubuntu  22.04

# Expected behavior

* The zammad-nginx container writes a working nginx config

# Actual behavior

* `/docker-entrypoint.sh: line 119: /etc/nginx/sites-enabled/default: Read-only file system`

# Steps to reproduce the behavior

* Use docker-compose file from this repository

# Further information
https://github.com/zammad/zammad-docker-compose/blob/07936ea7e0a46ddc34089684c045e4325e0a5d34/docker-compose.yml#L96
sets the `/etc/nginx/sites-enabled` path as read-only.

https://github.com/zammad/zammad/blob/74d5303cbf67c4507ccd0b78ac543f9fac533961/contrib/docker/docker-entrypoint.sh#L119
Writes the nginx config in

# Further questions

Is there any reason why the `init` container has access to the nginx config as well? This threw me off quite a bit during the search for the problem.

Is there any reason why the nginx container has it mounted?
This seems to have been added in https://github.com/zammad/zammad-docker-compose/commit/ffa1268a2aab5b459b255c63e004b011117b3c0f without further explanation

**Comment by mgruner** [comment]
Thanks for your report @strifel. It does not fail in the same way for me, but I agree that something is wrong with the current volume handling.
