### ISSUE TITLE
zammad-backup fails with permission error on docker-compose up -d

### ISSUE THREAD

**Issue by seljuck** [zammad/zammad-docker-compose#382]
# Infos

* Docker version:  24.0.6
* Docker-compose version: 1.29.2
* Operating system (Docker host): Ubuntu 20.04
* docker-compose.yml version: 11.1

# Expected behavior

* docker-compose up -d should startup all containers and run

# Actual behavior

* zammad-backup fails with ERROR: for zammad-docker-compose_zammad-backup_1  Cannot start service zammad-backup: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/local/bin/backup.sh": permission denied: unknown

# Steps to reproduce the behavior

* run docker-compose up -d

**Comment by mgruner** [comment]
Hello @seljuck, thanks for your report. 

Can you help me to reproduce this, please? It does work as expected here on Docker/MacOS.

Do you use the standard docker compose files / container images? Is there the expected mount of `/usr/local/bin/backup.sh` for the `zammad-backup` container? Can you share your `.env` as well, please (without credentials, of course)?

**Comment by seljuck** [comment]
I am using the standard compose files. But I did not use git to grab them. I just copied them. Also, I modified docker-compose.override.yml to include our nginx reverse proxy network.

Here's the zammad-backup section in docker-compose.yml

  zammad-backup:
    command: ["zammad-backup"]
    depends_on:
      - zammad-railsserver
      - zammad-postgresql
    entrypoint: /usr/local/bin/backup.sh
    environment:
      <<: *zammad-environment
      BACKUP_TIME: "03:00"
      HOLD_DAYS: "10"
      TZ: Europe/Berlin
    image: postgres:${POSTGRES_VERSION}
    restart: ${RESTART}
    volumes:
      - zammad-backup:/var/tmp/zammad
      - zammad-storage:/opt/zammad/storage:ro
      - zammad-var:/opt/zammad/var:ro
      - ./scripts/backup.sh:/usr/local/bin/backup.sh:ro


Here is my .env file

ELASTICSEARCH_VERSION=8.8.0
IMAGE_REPO=ghcr.io/zammad/zammad
MEMCACHE_SERVERS=zammad-memcached:11211
MEMCACHE_VERSION=1.6.20-alpine
POSTGRES_DB=zammad_production
POSTGRES_PASS=password
POSTGRES_USER=zammad
POSTGRES_HOST=zammad-postgresql
POSTGRES_PORT=5432
POSTGRES_VERSION=15.3-alpine
REDIS_URL=redis://zammad-redis:6379
REDIS_VERSION=7.0.5-alpine
RESTART=always
VERSION=6.1.0

**Comment by mgruner** [comment]
Just as a quick workaround, you can add this in a local override file to disable the backup container:

```yaml
  zammad-backup:
    profiles:
      - disable-service  
```

**Comment by mgruner** [comment]
I just tried starting the default Zammad stack via docker compose on a fresh Ubuntu 20.04 cloud server, using the latest docker packages from the [official apt repository](https://docs.docker.com/engine/install/ubuntu/), and it worked just fine.

```
Docker version 24.0.7, build afdd53b
containerd containerd.io 1.6.24 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
runc version 1.1.9
commit: v1.1.9-0-gccaecfc
spec: 1.0.2-dev
go: go1.20.8
libseccomp: 2.5.1
```

Right now this does not look like a defect in Zammad's stack, therefore I'm going to close this entry. Please feel free to provide more information that makes it reproducible for us.

**Comment by seljuck** [comment]
Thanks for your help @mgruner. I've solved the problem.

Because I copied the files, the scripts/backup.sh file did not have the execute permission. Once I did chmod +x backup.sh and started up the containers again, everything worked just fine.

**Comment by seljuck** [comment]
One other thought. The Zammad Docker Install documentation says you can just copy the files. This issue might want to be mentioned.

https://docs.zammad.org/en/latest/install/docker-compose.html

![image](https://github.com/zammad/zammad-docker-compose/assets/25122885/5a76675f-b09f-43ba-b1b1-9e7c56f970ca)

**Comment by mgruner** [comment]
Thanks for the follow-up. I will address this in the documentation.
