### ISSUE TITLE
How to restore the zammad backup V.6.1 Docker-Compose

### ISSUE THREAD

**Issue by sumonchai** [zammad/zammad-docker-compose#385]
# Infos

* Docker version: 20.10.23
* Docker-compose version:  2.9.0-6413-g38f6acd
* Operating system (Docker host): synology docker

# Expected behavior

* Restore backup

# Actual behavior

* [How to restore the zammad backup?](https://github.com/zammad/zammad-docker-compose/issues/68#top)
 Not work 

# Steps to reproduce the behavior

*[How to restore the zammad backup?](https://github.com/zammad/zammad-docker-compose/issues/68#top)

**Comment by mgruner** [comment]
Please take support requests to https://community.zammad.org/. Thank you!
