### ISSUE TITLE
fatal error when git checkout cd424e98689b8dc49878a37b9aab67192c36fd24

### ISSUE THREAD

**Issue by swoop124** [zammad/zammad-docker-compose#387]
# Infos
yesterday i starded to update my zammad instance from 5.1.x but i ran into a problem and restored it all. Today i wanted to try it again but when i entered this command: `git checkout cd424e98689b8dc49878a37b9aab67192c36fd24` there was an error.
`fatal: reference is not a tree:  cd424e98689b8dc49878a37b9aab67192c36fd24`

* Docker version: 24.0.7
* Docker-compose version: 2.23.0
* Operating system (Docker host): debian 10.13

# Expected behavior

the abouve command should download the repository to which i can update my Zammad instance to 5.2.23 to update it afterwards step by step to 6.1

# Actual behavior

`fatal: reference is not a tree:  cd424e98689b8dc49878a37b9aab67192c36fd24`

# Steps to reproduce the behavior

1. open terminal to docker host
2. change into zammad-compose directory
3. enter command: `git checkout cd424e98689b8dc49878a37b9aab67192c36fd24 `

**Comment by mgruner** [comment]
Please turn to the [Zammad community](https://community.zammad.org/) for support requests.

Not sure what happened there, but this does not look like a bug in the Zammad stack.

**Comment by swoop124** [comment]
yes, you are right, it is a git Problem.
someone has removed `cd424e98689b8dc49878a37b9aab67192c36fd24` so how can i update my instance?

**Comment by mgruner** [comment]
You could try sychronizing with upstream again. Maybe `git fetch origin`?
