### ISSUE TITLE
Zammad wont move storage from DB to File

### ISSUE THREAD

**Issue by migasQ** [zammad/zammad-docker-compose#389]
# Infos

* Docker version: 20.10.21
* Docker-compose version: 1.27.0
* Operating system (Docker host): Ubuntu 20 LTS

# Expected behavior

* Moving files from DB to File takes place when running `Store::File.move('DB', 'File')`

# Actual behavior

* New tickets are saved on file system after changing the admin settings but existing attachments are not moved

# Steps to reproduce the behavior

- After https://github.com/zammad/zammad-docker-compose/releases/tag/v11.2.0 I changed storage from DB to File in the settings
- I am using a file mount /mnt/data/zammad-storage and therefore needed to set `chown 1000:1000 -R *` for that folder because I saw some access error in the frontend when trying to add an attachment, after running the command attachments are added just fine
- I ran then

```bash
root@xxx:~/zammad# docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec zammad-railsserver rails c
I, [2023-12-07T17:58:59.201150 #70]  INFO -- : ActionCable is using the redis instance at redis://zammad-redis:6379.
I, [2023-12-07T17:58:59.218559#70-6000]  INFO -- : Using memcached as Rails cache store.
I, [2023-12-07T17:58:59.219381#70-6000]  INFO -- : Using the Redis back end for Zammad's web socket session store.
Loading production environment (Rails 7.0.8)
[1] pry(main)> Store::File.move('DB', 'File')
=> true
[2] pry(main)> exit
```

- What I found odd is that `=> True` was shown directly whithout any waiting
- However nothing is changed, the storage folder is empty but in the frontend I can still access all attachements (from DB I guess)
- In the railsserver container I cannot see any error log entries, everything looks good 
- Is the move command broken? Does it create any log entries somewhere? Maybe it has something to do with https://admin-docs.zammad.org/en/latest/settings/system/storage.html --> *You noticed slow updates of Zammad?*

**Comment by mgruner** [comment]
@migasQ I believe it is related to using `docker exec` rather than `docker run`. This leads to missing ENV variables, which in turn leads to `nulldb` being used as database driver. Please use `docker run` instead and it should work.

**Comment by mgruner** [comment]
https://docs.zammad.org/en/latest/install/docker-compose.html -  How to run rails/rake commands in containers

**Comment by migasQ** [comment]
Thanks for your prompt response! That was indeed the issue. I did a merge request for a docu extension to run an interactive rails shell with ENV set because I don't like running commands blindly without autocomplete, etc. The merge request is here: https://github.com/zammad/zammad-documentation/pull/404
