### ISSUE TITLE
Zammad container will never start

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [zammad/zammad-docker-compose#4]
What is the main task for https://github.com/zammad/zammad-docker-compose/blob/master/docker-compose.yml#L26 container?
It doesn't have the CMD entry https://github.com/zammad/zammad-docker-compose/blob/master/containers/zammad/Dockerfile
So it can't start properly and just continuously rebooting.

**Comment by monotek** [comment]
It's a data only container.
I don't see that the container is restarting. It just exits with exit code 0.

**Comment by Ilya-Kuchaev** [comment]
I'm using Rancher to host the services. So I had to add the following label to container
`io.rancher.container.start_once=true`
