### ISSUE TITLE
Unable to connect to websocket with caddy as ingress

### ISSUE THREAD

**Issue by PaulGoldschmidt** [zammad/zammad-docker-compose#400]
Hey,

I have now tried to debug the following issue for two full days but not have been able to find a solution: I installed Zammad without a problem on my server, the incoming traffic is routed with caddy to the docker zammad nginx container, which should handle the rest™ of the traffic mangement. The website loads without a problem, but no connection to the websocket server can be established. The websocket container itself does not log anything after startup, the last message is "`INFO -- : Using the Redis back end for Zammad's web socket session store.`. The zammad nginx container logs for each connection attempt `upstream prematurely closed connection while reading response header from upstream, client: 172.27.0.1, server: _, request: "GET /ws HTTP/1.1", upstream: "http://172.27.0.7:6042/ws"` followed by `GET /ws HTTP/1.1" 502 150 "-"`. Any idea on what could be causing this issue or how to debug this? I definetly hit the boundary of what I know with this issue, which is quite frustrating because everything else works without a problem.
I would also be down to write some documentation if my setup works.

Any help is highly appreciated, tysm!

All the best,
Paul

# Infos

* Docker version: 25.0.2
* Docker-compose version: 1.29.2
* Operating system (Docker host): Ubuntu 22.04.3 LTS

# Expected behavior

* Websocket Connection being established sucessfully

# Actual behavior

<img width="677" alt="error" src="https://github.com/zammad/zammad-docker-compose/assets/12871113/00f46bc9-b66f-4e4a-a595-1ec93dff92ee">

# Steps to reproduce the behavior

* Standard zammad installation via docker compose with caddy setup as ingress point and reverse proxy.

# Current Caddy reverse proxy setup

```
fqdn {
    encode gzip
    header Strict-Transport-Security "max-age=31536000;"

    reverse_proxy http://127.0.0.1:4353 {
        # Caddy automatically upgrades connections to HTTP/2 where possible.
        # Set header directives equivalent to the Nginx configuration.
        header_up Host {host}
        header_up X-Real-IP {remote}
        header_up X-Forwarded-For {remote}
        header_up X-Forwarded-Port {server_port}
        header_up X-Forwarded-Proto {scheme}
        header_up Connection {>Connection}
        header_up Upgrade {>Upgrade}
    }

        @ws {
                header Connection *Upgrade*
                header Upgrade websocket
        }
   # WebSocket configuration
    reverse_proxy /ws http://127.0.0.1:4353 {
           header_up Upgrade {http.upgrade}
    header_up Connection "Upgrade"
    header_up CLIENT_IP {remote_host}
    header_up X-Forwarded-For {http.request.remote}
    }
   header @staticFiles Cache-Control "max-age=31536000, public"
}
```

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
