### ISSUE TITLE
feat request: Support REDIS_PASSWORD and ELASTIC_PASSWORD env variables in zammad-init

### ISSUE THREAD

**Issue by DOCS-kdu3** [zammad/zammad-docker-compose#403]
# Infos

* Podman Version 4.6.1
* Podman-compose version: 1.0.6
* Operating system (Docker host): Red Hat Enterprise 8.9

# Expected behavior

* Docker compose file supports both Elasticsearch and Redis passwords to utilize with running instances of each software.

# Actual behavior

Elasticsearch
```
zammad-zammad-init-1         | #<UserAgent::Result:0x00007fa1793863... @success=false, @body="{\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"missing authentication credentials for REST request [/]\",\"header\":{\"WWW-Authenticate\":[\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\",\"ApiKey\"]}}],\"type\":\"security_exception\",\"reason\":\"missing authentication credentials for REST request [/]\",\"header\":{\"WWW-Authenticate\":[\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\",\"ApiKey\"]}},\"status\":401}", @data=nil, @code="401", @content_type=nil, @error="Client Error: #<Net::HTTPUnauthorized 401 Unauthorized readbody=true>!", @header={"www-authenticate"=>"Basic realm=\"security\" charset=\"UTF-8\", ApiKey", "content-type"=>"application/json;charset=utf-8", "content-length"=>"403"}>
```

Redis
```
zammad-zammad-init-1         | initialising / updating database...
zammad-zammad-init-1         | rake aborted!
zammad-zammad-init-1         | Redis::CommandError: NOAUTH Authentication required.
```
# Steps to reproduce the behavior

* Configure the docker-compose file and env variables to use a password protected instance of Elasticsearch and/or Redis.

**Comment by DOCS-kdu3** [comment]
Redis issue resolved REDIS_URL can include password redis://:PASSWORD@foo.com:PORT

Presently having trouble with [ELASTICSEARCH_PASS](https://github.com/zammad/zammad/blob/d26d8d56fc879cdde0af629246979d4f53fd57dc/contrib/docker/docker-entrypoint.sh#L89-L91).

**Comment by kale1d0code** [comment]
Can this be documented?

new instances of zammad don't spin up because elasticsearch now runs on https (not http) and expects a username and password
