### ISSUE TITLE
Init container finishes but other containers continue to wait for it to finish

### ISSUE THREAD

**Issue by kale1d0code** [zammad/zammad-docker-compose#406]
# Infos

* Docker version: 25.0.2
* Docker-compose version: unsure
* Operating system (Docker host): AlmaLinux

# Expected behavior

init service finishes.
nginx service starts and helpdesk to be accessible via web interface

# Actual behavior
nginx service continues to wait for init container after it has finished

# Steps to reproduce the behavior
upgrade from zammad 6.2.0 to 6.3.0

**Comment by kale1d0code** [comment]
I've looked into this somemore.
I was under the impression that the startup script uses a "ready file"
this has been replaced with a wait until loop for checking the status of migrations on rake (this should report successful however the nginx container cannot find the database configuration from the path config/database.yml).

I've also looked at the docker-compose.yml files and there is a new volume mount "storage" and the "var" mount isn't in the example anymore.

Is there any documentation for upgrading between 6.2 and 6.3 and the changes between hosting both?

**Comment by mgruner** [comment]
> I've looked into this somemore. I was under the impression that the startup script uses a "ready file" this has been replaced with a wait until loop for checking the status of migrations on rake (this should report successful however the nginx container cannot find the database configuration from the path config/database.yml).

Yes, the waiting mechanism was changed. The NGINX container needs the environment variables to identify the database connection.

> I've also looked at the docker-compose.yml files and there is a new volume mount "storage" and the "var" mount isn't in the example anymore.

Zammad 6.3 only removed the var volume mount.

> Is there any documentation for upgrading between 6.2 and 6.3 and the changes between hosting both?

I'm not aware of an upgrading documentation for the docker compose stack up to this point. If I understood it correctly, the yml files in this repository are actually meant to be used directly and extended by custom configuration files. For using only your own code, you will have to follow the development process of this repository closely and adapt changes accordingly.
