### ISSUE TITLE
Upgrade from 5.x to 6.x. What is the proper way to jump from 5.x to 6.x?

### ISSUE THREAD

**Issue by tarreislam** [zammad/zammad-docker-compose#407]
# Infos

* Docker version: 1.25
* Docker-compose version: 1.27
* Operating system (Docker host): ubuntu 20

# Expected behavior

* Upgrading directly by checking out last tag from 1 year old master to make everything magically work

# Actual behavior

* Postgres DB error causing upgrade to fail.

# Steps to reproduce the behavior

1.  Install with ~1 year old master
2. Checkout latest v10 tag and rebuild

**Comment by mgruner** [comment]
Please post your detailed configuration and error logs.
