### ISSUE TITLE
Postgresql password not working from .env - FATAL:  password authentication failed for user "zammad"

### ISSUE THREAD

**Issue by internallabworks** [zammad/zammad-docker-compose#414]
# Infos

* Docker version: 26.0.1
* Docker-compose version: 2.26.1
* Operating system (Docker host): Ubuntu 22.04

# Expected behavior

* docker compose up -d -> should create a running environment.

# Actual behavior

*  Looking at the logs while it tries to run init, I find this:
 FATAL:  password authentication failed for user "zammad"
 
I've tried changing the username and password in .env and I get the same error, just with the new username.

# Steps to reproduce the behavior

* git pull from the repo, then run docker compose up -d

**Comment by trstn70** [comment]
Docker 25.0.3 on Debian 11
repo tag v11.3.1 zammad version 6.3.1

I see the same behavior. the env Vars
POSTGRES_PASS
and
POSTGRES_USER
seem not to work. I configured a different User for the database and get the same error for the User "zammad". That seems hardcoded.

**Comment by mgruner** [comment]
It works well for me when changing the value `POSTGRES_USER=otheruser` before starting the stack for the first time, so I am not able to reproduce this with a fresh system and the latest zammad-docker-compose version. 

Note that this must be done before bringing up the cluster the first time. Afterwards it's too late and you have to make changes in the database yourself.
