### ISSUE TITLE
Fresh install SearchIndexAssocJob stuck

### ISSUE THREAD

**Issue by tarreislam** [zammad/zammad-docker-compose#420]
# Infos

* Docker version:22
* Docker-compose version:22
* Operating system (Docker host): ubuntu 22

# Expected behavior

* healthy system

# Actual behavior

```
{
"healthy": false,
"message": "Stuck data privacy task (ID 2) detected. Last update: 2024-05-14 10:17:08 UTC;emails that could not be processed: 18;Failed to run background job #1 'SearchIndexAssociationsJob' 1 time(s) with 17 attempt(s).",
"issues": [
"Stuck data privacy task (ID 2) detected. Last update: 2024-05-14 10:17:08 UTC",
"emails that could not be processed: 18",
"Failed to run background job #1 'SearchIndexAssociationsJob' 1 time(s) with 17 attempt(s)."
],
"actions": []
}
```

# Steps to reproduce the behavior

1. Install fresh 6.3.1 via docker-compose
2. Add imap mail
3. Wait a couple of days/weeks
4. Bad health and earchindex failed

**Comment by mgruner** [comment]
Can you please provide relevant error logs of the scheduler and elasticsearch containers?

Did you correctly configure elasticsearch as described in https://docs.zammad.org/en/latest/install/docker-compose.html#step-2-setting-vm-max-map-count-for-elasticsearch?

**Comment by mgruner** [comment]
Thanks for the update. I'll close this issue now.
