### ISSUE TITLE
docker  container build add vim or vi

### ISSUE THREAD

**Issue by yuhongwei380** [zammad/zammad-docker-compose#421]
# Infos

* Docker version: Docker version 26.1.3, build b72abbb
* Docker-compose version:docker-compose version 1.29.2, build 5becea4c
* Operating system (Docker host):

# Expected behavior

*

# Actual behavior

*

# Steps to reproduce the behavior

*
sometimes when go to the container , want to use the vim to editor . maybe docker container build can add vim ?

**Comment by waja** [comment]
> sometimes when go to the container , want to use the vim to editor . maybe docker container build can add vim

Sounds very unusual. I would recommend to enter the running container and install it with the package manager so you can use it until the container is removed.
For regular use cases an editor is not needed in the image.

**Comment by yuhongwei380** [comment]
> > sometimes when go to the container , want to use the vim to editor . maybe docker container build can add vim
> 
> Sounds very unusual. I would recommend to enter the running container and install it with the package manager so you can use it until the container is removed. For regular use cases an editor is not needed in the image.

ok, Thanks for reply
