### ISSUE TITLE
Empty attachments after download

### ISSUE THREAD

**Issue by GoliathLabs** [zammad/zammad-docker-compose#423]
# Infos

* Docker version: Docker Engine - Community 26.1.4
* Docker-compose version: v2.27.1
* Operating system (Docker host): Debian GNU/Linux 12 (bookworm)"

# Expected behavior

* Attachment downloads should represent the actual file and contain its contents.

# Actual behavior

* Downloading attachments results in a 0KB file on disk. But only sometimes. PDFs are prone to this. So is DOCX. PNGs usually work fine. It's nothing to do with the computer. Interestingly, on an Android via the mobile version, the files render just fine and are as expected. Forwarding the message with the attachment to a normal mailbox also makes the attachments usable.
* 
# Steps to reproduce the behavior

* Update to 6.3.1. Use your Windows 11 (21H2) with Windows Defender. No custom firewall rules or antivirus software. Unrelated to browser (used Firefox & Edge)

**Comment by MrGeneration** [comment]
Closing as duplicate. Please do not create several requests in several places. It won't speed up anything.
