### ISSUE TITLE
railsserver container not starting

### ISSUE THREAD

**Issue by waja** [zammad/zammad-docker-compose#43]
### Infos:

* Docker version: 17.06.2-ce
* Docker-compose version: 1.15.0
* Operating system (Docker host): Debian 8.9

### Expected behavior:

Starting the Rails container.

### Actual behavior:

zammad-railsserver_1    | Bundler::RubyVersionMismatch: Your Ruby version is 2.4.1, but your Gemfile specified 2.3.1
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:486:in `validate_ruby!'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:461:in `validate_runtime!'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler.rb:95:in `setup'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/setup.rb:19:in `<top (required)>'
zammad-railsserver_1    |   /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
zammad-railsserver_1    |   /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'

### Steps to reproduce the behavior:

* ```docker-compose pull && docker-compose up```

Looks like this issue is related to 89473cc6729354fec95d78d1930448c9a410633d

**Comment by monotek** [comment]
Should be fixed with: https://github.com/zammad/zammad-docker-compose/commit/b904f63148b8540e93db857325f701bf1c66291f

Just wait for the build to finish: https://travis-ci.org/zammad/zammad-docker-compose/builds/275188604
