### ISSUE TITLE
Querying of data seems not to work in GUI and rails after update to 6.3

### ISSUE THREAD

**Issue by Jan-NiklasB** [zammad/zammad-docker-compose#431]
# Infos

* Docker version: 27.2.1
* Docker-compose version: 1.27.4
* Operating system (Docker host): Ubuntu 22.04 LTS

# Expected behavior

* Like in previous versions, you type for example the first letters of an name or org into a field and the possibilities available are shown as list

# Actual behavior

* Nothing happens, and when creating a trigger and setting the criteria to owner is specific user and enter my name manually it gives an error (Invalid condition for the object chosen)
* Also as mentioned in Issue #412 rails also doesn't works as expected, I guess there's something wrong with the database config in this version

# Steps to reproduce the behavior

* Update from 5.4.1 installing every mayor and minor version up to latest using the compose files and .env files given in this repo
* Try as described above

**Comment by mgruner** [comment]
Please post technical questions about upgrading issues in https://community.zammad.org/. I can confirm that Zammad 6.3 does work properly when deployed via docker compose.
