### ISSUE TITLE
Questions for Upgrade （6.3 to 6.4 ）

### ISSUE THREAD

**Issue by yuhongwei380** [zammad/zammad-docker-compose#435]
# Infos

* Docker version:26.1.3, build b72abbb
* Docker-compose version:1.29.2, build 5becea4c
* Operating system (Docker host): ubuntu20.04 LTS

# Expected behavior

* Change the docker-compose.yml  , then upgrade  ?

# Actual behavior

*

# Steps to reproduce the behavior

Some questions :
1.how to update , 6.3 to 6.4 , have docs ?
2.i noticed the new version contains some new version of software, if i update ,the old data will exist ?

**Comment by MrGeneration** [comment]
Zammad 6.4 is not yet released.
You can find the update documentation here:
https://docs.zammad.org/en/latest/install/update.html

For further technical questions, please consult the community at https://community.zammad.org
