### ISSUE TITLE
zammad-backup not working with postgres 17

### ISSUE THREAD

**Issue by krombel** [zammad/zammad-docker-compose#440]
After upgrading to the latest release backups are not working anymore.

These are the logs of the `zammad-backup` container:

```log
zammad-backup-1  | 20241115163509 - backing up zammad...
zammad-backup-1  | tar: Removing leading `/' from member names
zammad-backup-1  | pg_dump: error: aborting because of server version mismatch
zammad-backup-1  | pg_dump: detail: server version: 17.1; pg_dump version: 15.8 (Debian 15.8-0+deb12u1)
zammad-backup-1  | backup finished :)
zammad-backup-1  | sleeping 37490 seconds until the next backup run...
```

It seems, this issue is coming from the ruby base image:
https://github.com/zammad/zammad/blob/6.4.0/Dockerfile#L20
where then the `postgres-client` package is installed
https://github.com/zammad/zammad/blob/6.4.0/contrib/docker/setup.sh#L7

This is currently based on bookworm - which does not have `postgres-client` for postgres 17 yet.
https://packages.debian.org/search?keywords=postgresql-client

**Comment by mgruner** [comment]
Confirmed, fix is in the works: https://github.com/zammad/zammad/pull/5416

**Comment by skyscooby** [comment]
Honestly you guys really need to be more careful with version bumps in this repository... It seems like you are just moving all components forward willy-nilly as if they were just build dependencies in a software project. Without any thought to operational considerations that users will face when they pull and apply your updates to their stacks....  

Major bumps on data components like postgres shouldn't just be thrown in there unless you are going to use a customized postgres container that will handle major version bumps seamlessly. The official Postgres containers you reference in your compose definitions will NOT automatically handle upgrading users existing postgres data files from the old major version to the new one.  

This is also a convoluted process inside a container as well as the normal process involves having both the old version and new version of the binaries installed on the same server. In any regard you should at minimum release documentation when you update this repository as to what users will need to do to maintain their data when upgrading..

Testing this in CI means first standing up the previous commit's stack.. then git pull.. then docker compose up.. and confirming the transition happened non-destructively.. Is this a scenario you are actively testing today?

**Comment by skyscooby** [comment]
You may want to consider something like this: https://github.com/pgautoupgrade/docker-pgautoupgrade

**Comment by mgruner** [comment]
@skyscooby our [upgrading instructions for docker](https://docs.zammad.org/en/latest/install/update.html) advise to check the [release notes for zammad-docker-compose](https://github.com/zammad/zammad-docker-compose/releases). I assume you didn't read these?

I have to admit that we need to improve our workflows and CI coverage, but it's not true that operational concerns are discarded.
