### ISSUE TITLE
Zammad Version 4

### ISSUE THREAD

**Issue by hsh-it** [zammad/zammad-docker-compose#444]
I was trying this .env config
```yml
ELASTICSEARCH_VERSION=8.16.1
# IMAGE_REPO=ghcr.io/zammad/zammad
# MEMCACHE_SERVERS=zammad-memcached:11211
# MEMCACHE_VERSION=1.6.32-alpine
# NGINX_PORT=8080
# NGINX_EXPOSE_PORT=8080
# POSTGRES_DB=zammad_production
# POSTGRES_PASS=zammad
# POSTGRES_USER=zammad
# POSTGRES_HOST=zammad-postgresql
# POSTGRES_PORT=5432
# POSTGRES_VERSION=17.2-alpine
# POSTGRESQL_OPTIONS=?pool=50
# REDIS_URL=redis://zammad-redis:6379
# REDIS_VERSION=7.4.1-alpine
# RESTART=always
# Use a fixed version. You are responsible to update this to newer patch level versions yourself.
# VERSION=6.4.0-34
# You can also use floating versions that will give you automatic updates:
# VERSION=6.2     # all patchlevel updates
# VERSION=6       # including minor updates
# VERSION=latest  # all updates of stable versions, including major
# VERSION=develop # bleeding-edge development version
# Zammad Version
VERSION=4.0

# Elasticsearch Version
ELASTICSEARCH_VERSION=7.9.2

# PostgreSQL Konfiguration
POSTGRES_DB=zammad
POSTGRES_VERSION=9.6-alpine

# Allgemeine Einstellungen
RESTART=always
```

because my nativ zammad installation is:
**Zammad 4.0**

postgres:
postgres --version
**postgres (PostgreSQL) 9.2.24**

elasticsearch:
{
  "name" : "zammad.hsh-berlin.com",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "YHPG021US9OtrbK2JV82bQ",
  "version" : {
    **"number" : "7.9.2",**
    "build_flavor" : "default",
    "build_type" : "rpm",
    "build_hash" : "d34da0ea4a966c4e49417f2da2f244e3e97b4e6e",
    "build_date" : "2020-09-23T00:45:33.626720Z",
    "build_snapshot" : false,
    "lucene_version" : "8.6.2",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

i need to import this inti a new zamamd docker instalaltion

is there any way to do it ?

**Comment by mgruner** [comment]
I don't think this will work, there have been many changes in the docker stack for recent versions. Please first update your existing Zammad installation to the recent version 6.4, and then migrate it to docker.

**Comment by MrGeneration** [comment]
Sorry, but our Github repositories are not for technical questions / assistance.
If you require help, please consult our community: https://community.zammad.org

**Comment by mgruner** [comment]
If you would like to purchase professional assistance, please feel free to [reach out](https://zammad.com/en/services/professional-services). We have colleagues who are experienced with such complex migrations.
