### ISSUE TITLE
The backup script cannot find the config/database.yml file

### ISSUE THREAD

**Issue by Collay** [zammad/zammad-docker-compose#448]
### Environment:

- Docker version: 27.3.1

- Docker-compose version: v2.19.0

- Operating system (Docker host): Debian GNU/Linux 12 (bookworm)

- Zammad 6.4.1

### Expected behavior

- Calling the backup script from the container and creating a backup.

### Actual behavior

- The script reports that it cannot find the database.yml file, but I'm guessing actual [path](https://github.com/zammad/zammad/blob/stable/config/database/database.yml):

```shell
~/zammad-docker-compose# docker-compose exec zammad-backup /opt/zammad/contrib/backup/zammad_backup.sh

# Zammad backup started - Wed Dec 11 08:32:19 CET 2024!

/opt/zammad/config/database.yml is missing. is Zammad configured yet?
``` 

### Steps to reproduce the behavior

- Setup the current version and run: 
```shell
docker-compose exec zammad-backup /opt/zammad/contrib/backup/zammad_backup.sh
```

**Comment by mgruner** [comment]
To invoke the backup entrypoint, you'd need to run:

```
docker compose exec zammad-backup /docker-entrypoint.sh zammad-backup
```

But this will not just create one backup, but go into an endless loop, creating backups from time to time. To run individual commands, use:

```
docker compose exec zammad-backup /docker-entrypoint.sh /path/to/your/command
```

See also https://docs.zammad.org/en/latest/install/docker-compose.html#how-to-run-commands-in-the-stack
