### ISSUE TITLE
Don't use multiple images

### ISSUE THREAD

**Issue by hhoechtl** [zammad/zammad-docker-compose#45]
### Expected behavior:

Only one image is needed to run a docker-compose environment with containers for single purposes.

As the only difference in the image builds is the entrypoint script you could just merge the entrypoint scripts into one and use `command` to start the various containers. E.g. https://gist.github.com/hhoechtl/5ec90da9dafb8fdddd403bd7711711c2

This way the services will always have the same and correct version. E.g. if the image build for an image had failed e.g. websockets which would then lead to a mixture of zammad versions in the containers involved in the docker-compose environment.

### Actual behavior:

There are various images for the services needed to run a docker-compose environment which means you must synchronize many images with your local registry in order to start an environment with the correct version.

**Comment by monotek** [comment]
Good point. I'll add it to my to do list.
