### ISSUE TITLE
Use zammad version as image tags

### ISSUE THREAD

**Issue by hhoechtl** [zammad/zammad-docker-compose#46]
### Expected behavior:

I want to run a Zammad docker-compose environment with a defined stable version of zammad e.g. "2.1.1".

### Actual behavior:

There's no way of achieving this with docker image tags as they are not versioned according to the Zammad releases. There are version tags like `-79` but I can't find any explanation which version that would match. As an administrator I'd like to decide which exact version to use and when I would like to upgrade just increase the version tag of the image, test it and update my environment.

**Comment by monotek** [comment]
Currently we use Travis CI build numbers to add versioning, which was kind of a quick hack, to get versioning at all. 

The correct version number would be nicer. Need to check how to automate it.

**Comment by monotek** [comment]
Fixed. First version: https://hub.docker.com/r/zammad/zammad/tags/
