### ISSUE TITLE
zammad restore

### ISSUE THREAD

**Issue by smindorf** [zammad/zammad-docker-compose#47]
### Infos:

* Docker version: 17.06.2-ce
* Docker-compose version: 1.11.2
* Operating system (Docker host): Ubuntu 16.04.3 LTS

### Expected behavior:

* restore should work as designed

### Actual behavior:

* restore not possible

### Steps to reproduce the behavior:

* get backup of other instance zammad ( v. 2.0.0 )
* start zammad (v 2.0.0) `docker-compose up -d`
* copy backupfiles into container `docker cp 20170920104238_zammad_files.tar.gz zammaddockercompose_zammad-railsserver_1:/tmp` and `docker cp 20170920104238_zammad_db.psql.gz zammaddockercompose_zammad-railsserver_1:/tmp`
* execute container `docker exec -ti zammaddockercompose_zammad-railsserver_1 /bin/bash`

In Container:
* `mkdir /var/tmp/zammad_backup`
* `chown -R zammad: /var/tmp/zammad_backup/`
* `cd /home/zammad/contrib/backup/`
* `cp config.dist config`
* `./zammad_restore.sh`

```
root@ca57279d885d:/home/zammad/contrib/backup# ./zammad_restore.sh 

# Zammad restored started - Mon Sep 25 12:25:18 UTC 2017!

The restore will delete your current config and database! 
Be sure to have a backup available! 

Enter 'yes' if you want to proceed!
Restore?: yes
Enter file date to restore: 
20170920104238
File date: 20170920104238
Enter db date to restore: 
20170920104238
DB date: 20170920104238
# Stopping Zammad
Failed to get D-Bus connection: Unknown error -1
# Restoring Files
# Restoring PostgrSQL DB
No passwd entry for user 'postgres'
# Starting Zammad
Failed to get D-Bus connection: Unknown error -1

# Zammad restored successfully - Mon Sep 25 12:25:29 UTC 2017!

root@ca57279d885d:/home/zammad/contrib/backup#
```
Also I tired to run the setup first and then I try to restore withou success.

Regards,
Sören

**Comment by monotek** [comment]
The restore script does not work in docker-compose.
You have to restore by hand.
