### ISSUE TITLE
Backup container using Debian based image

### ISSUE THREAD

**Issue by waja** [zammad/zammad-docker-compose#49]
zammad-backup is using an image based on the Debian image and installing postgresql into it.

Is there a reason not using the zammad-postgresql image I'm overseeing? It also has the pg_dump command and using this will save resources in many places (diskspace, travis-ci, time and data pulling the images ...).

Thanks for doing such a great work, Jan.

**Comment by monotek** [comment]
I tried it in the first place but using the backup containers entrypoint the postgresql server was starting.

**Comment by waja** [comment]
This can be overridden by the compose file: https://docs.docker.com/compose/compose-file/#entrypoint

**Comment by monotek** [comment]
But this should be already been done from the dockerfile in the docker build step as its done for the other images too.

**Comment by waja** [comment]
I'll try to have a look into this later ...

**Comment by waja** [comment]
> But this should be already been done from the dockerfile in the docker build step as its done for the other images too.

Anyway ... docker-compose allows to [override the entrypoint specified in the Dockerfile](https://docs.docker.com/compose/compose-file/#entrypoint), so you can copy the ```docker-entrypoint.sh``` from the backup image to the postgresql image via Dockerfile on buildtime (and set the ENV for the backup). Leave the rest like it is, this shouldn't change anything how the image acts as database container.
For backup purpose you can then override the entrypoint from the postgresql image via compose file to create the backup.

Indeed, this is untested but this is what I would do trying to solve this.

**Comment by monotek** [comment]
Pull requests welcome ;-)

**Comment by waja** [comment]
give #50 a try.
