### ISSUE TITLE
services.zammad.labels.io.rancher.container.start_once contains true

### ISSUE THREAD

**Issue by snow2k9** [zammad/zammad-docker-compose#5]
Hey there,
I'm getting following error..
> ERROR: The Compose file './docker-compose.yml' is invalid because:
services.zammad.labels.io.rancher.container.start_once contains true, which is an invalid type, it should be a string, number, or a null

I don't use Rancher, I just cloned the repo and used `docker-compose up`
Setting `services.zammad.labels.io.rancher.container.start_once` to `"true"` or to `null` fixed this..
Using Arch/Manjaro

`docker-compose version 1.9.0, build 25853874`
`docker-py version: 1.10.6`
`docker version 1.12.6`
`Go version:   go1.7.4`

**Comment by monotek** [comment]
https://github.com/zammad/zammad/issues/665

**Comment by monotek** [comment]
fixed with https://github.com/zammad/zammad-docker-compose/pull/6
