### ISSUE TITLE
Zammad in docker (how to update)

### ISSUE THREAD

**Issue by sandrodz** [zammad/zammad-docker-compose#54]
Is there a dedicated instructions on how to update zammad in docker container?

Will pulling container files from github and down/up be sufficient?

**Comment by waja** [comment]
> Will pulling container files from github and down/up be sufficient?

Öhm ... yes. Maybe you will try to try the steps in the documentation.

**Comment by sandrodz** [comment]
missed that in docs.

<img width="654" alt="screen shot 2017-10-13 at 11 27 12 am" src="https://user-images.githubusercontent.com/8479569/31534800-852cff74-b009-11e7-9741-02c42763d85f.png">
