### ISSUE TITLE
Environment variables to connect to existing postgres and elasticsearch

### ISSUE THREAD

**Issue by mrcasablr** [zammad/zammad-docker-compose#56]
We would like to use existing Postgres database and Elasticsearch cluster.  Was wondering if I could export the connection and authentication details as docker variables and be able to connect to them?

Any other ways to make this work?

**Comment by monotek** [comment]
Variables could work but I never tried.
Pull request welcome ;-)

**Comment by monotek** [comment]
How would you solve that the postgresql and elasticsearch containers are running anyway?

**Comment by monotek** [comment]
Beside that you also would need to be able to use username and password for both servers.

**Comment by mrcasablr** [comment]
I was suggesting use of docker environment variables - 
POSTGRES_HOST
POSTGRES_DB
POSTGRES_USER
POSTGRES_PASS
... and similar for elasticsearch and nginx 

However, I have not looked into how the underlying zammad services start these services so that we can pass the variables

**Comment by monotek** [comment]
Variables are now possible. see: https://github.com/zammad/zammad-docker-compose/blob/master/containers/zammad/docker-entrypoint.sh
