### ISSUE TITLE
Bad gateway after update

### ISSUE THREAD

**Issue by sandrodz** [zammad/zammad-docker-compose#61]
### Infos:

* Docker version: 17.12.0-ce, build c97c6d6
* Docker-compose version: 1.16.1, build 6d1ac21
* Operating system (Docker host): centos7

### What I did:

I had a working Zammad installation, I did 

a. docker-compose stop
a. git pull
b. docker-composer pull
c. docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

But when I visit page it says 502 bad gateway. I've http-proxy (jwilder) in front.

Looking at container logs, it seems nginx is stuck
<img width="1280" alt="screen shot 2018-01-07 at 12 45 16 pm" src="https://user-images.githubusercontent.com/8479569/34649132-4bfd73d0-f3a9-11e7-8d3c-2bea60ab6af1.png">
<img width="1156" alt="screen shot 2018-01-07 at 12 45 35 pm" src="https://user-images.githubusercontent.com/8479569/34649133-4c1ffe46-f3a9-11e7-97f4-c57659ad7b0c.png">
<img width="1033" alt="screen shot 2018-01-07 at 12 45 55 pm" src="https://user-images.githubusercontent.com/8479569/34649134-4c3f6d76-f3a9-11e7-8593-a45c7e7cd360.png">
<img width="971" alt="screen shot 2018-01-07 at 12 46 07 pm" src="https://user-images.githubusercontent.com/8479569/34649135-4c5ff2b2-f3a9-11e7-8606-80c21d165bd1.png">

**Comment by monotek** [comment]
I don't use the proxy setup but it looks wrong to me to delete the networks part form the example.

Maybe @t3easy can help?

**Comment by sandrodz** [comment]
@monotek when I set it up previously there was no example. I just copied my working override from previous version after update.

In theory having networks  under zammad-nginx is redundant since we declare the network down below, it is applied to all containers declared within the services.

**Comment by monotek** [comment]
I don't think the problem zammad related.
Without proxy setup it works as expected.

**Comment by sandrodz** [comment]
I don't think that either, it is docker config issue, nginx is not starting for some reason.

**Comment by t3easy** [comment]
The network definition is not redundant on the service side if you don’t wanna have all your service reachable from the proxy container. Therefore a separate network between the proxy and the nginx worker.

First, can you reach the nginx worker from the proxy?

**Comment by sandrodz** [comment]
@t3easy hey, yes I can ping the container
<img width="1040" alt="screen shot 2018-01-07 at 4 18 46 pm" src="https://user-images.githubusercontent.com/8479569/34650758-7ac066ba-f3c6-11e7-8e10-0013a0c0fc9a.png">

Problem is that nginx, from logs seems to never start!

**Comment by sandrodz** [comment]
This is error log of nginx-proxy:

```2018/01/07 15:20:14 [error] 198#198: *35672 no live upstreams while connecting to upstream, client: 82.56.62.227, server: zammad.kubikthemes.com, request: "GET / HTTP/2.0", upstream: "http://zammad.kubikthemes.com/", host: "zammad.kubikthemes.com"```

**Comment by sandrodz** [comment]
I take that back, it seems nginx is running fine inside container. I can even curl the homepage of zammad Helpdesk from within the container:
<img width="1023" alt="screen shot 2018-01-07 at 4 25 13 pm" src="https://user-images.githubusercontent.com/8479569/34650821-6235191e-f3c7-11e7-8ee1-82d190a640b0.png">

**Comment by sandrodz** [comment]
Hang on a sec, nginx container is not exposing the port. How would nginx-proxy know where to redirect?
<img width="774" alt="screen shot 2018-01-07 at 4 32 44 pm" src="https://user-images.githubusercontent.com/8479569/34650888-73f36678-f3c8-11e7-9dfd-c9aca6bba649.png">

**Comment by sandrodz** [comment]
This is config generated by nginx-proxy (jwilder)

<img width="1280" alt="screen shot 2018-01-07 at 4 38 56 pm" src="https://user-images.githubusercontent.com/8479569/34650926-51d377ee-f3c9-11e7-8a63-81e9d9c086a3.png">

**Comment by t3easy** [comment]
Seems like @monotek changed the nginx image to the zammad image which doesn’t expose port 80... you can put the expose in the override config.

**Comment by monotek** [comment]
As you would need shared storage to access Zammad files from Railserver, Websocker, Scheduler & Nginx in Kubernetes Nginx was moved in the Zammad image.

If needed we can put the expose to the override config too.

**Comment by t3easy** [comment]
Why not use multistage build and copy over the build zammad files tho the official nginx image?

**Comment by sandrodz** [comment]
In any case, expose should be in the example.
<img width="1280" alt="screen shot 2018-01-07 at 5 26 29 pm" src="https://user-images.githubusercontent.com/8479569/34651394-1bc40d2e-f3d0-11e7-9dba-f4ac26f9dde9.png">

**Comment by monotek** [comment]
@t3easy beacuse files change while running zammad.

**Comment by t3easy** [comment]
Ok, I would add the expose to the main docker-compose.yml because it doesn’t hurt, even if it’s mapped. I’ll send a PR tomorrow.
