### ISSUE TITLE
Rancher Nginx container stuck at initializing after restart

### ISSUE THREAD

**Issue by MaximilianKindshofer** [zammad/zammad-docker-compose#64]
### Infos:

* Docker version:
17.05.0-ce
* Docker-compose version:
Rancher
* Operating system (Docker host):
Rancher

### Expected behavior:

* Zammad Nginx is starting even if the container has to restart

### Actual behavior:

* Zammad Nginx waits for other Services to start

### Steps to reproduce the behavior:

* Restart Nginx Container in Rancher

Thanks for your work btw

**Comment by CyberPunk2042** [comment]
What is your zammad-compose version?

**Comment by MaximilianKindshofer** [comment]
I was using the latest Rancher Version

**Comment by CyberPunk2042** [comment]
In my experience with zammad 2.2 you can't restart containers separately it would be better to stop and start all again

**Comment by augustoferronato** [comment]
I have the same problem here
Docker version: 17.12.1-ce
Rancher 1.6.14
OS: Ubuntu 16.04.4 LTS

The zammad-nginx have the output:

> waiting for all zammad services to start...
> waiting for all zammad services to start...
> waiting for all zammad services to start...
> waiting for all zammad services to start...
> waiting for all zammad services to start...
> waiting for all zammad services to start...
> waiting for all zammad services to start...
> waiting for all zammad services to start...

I try to restart all, stop in the same place.

**Comment by CyberPunk2042** [comment]
Hi
And now you have to start INIT as it started only once and wait dor es to rebuild index

**Comment by augustoferronato** [comment]
Sorry, i doesn't understand, i restart the container init and the nginx still the same way. 

Thanks

**Comment by CyberPunk2042** [comment]
Hi!
Stop all containers
![2](https://user-images.githubusercontent.com/36038814/38453471-2a105a74-3a5f-11e8-9163-d54e8fbdcf17.PNG)
Start all containers and wait
![3](https://user-images.githubusercontent.com/36038814/38453495-4fcc70ae-3a5f-11e8-8ce0-78d8489f43ac.PNG)
All containers started except nginx and zammad-init
![4](https://user-images.githubusercontent.com/36038814/38453509-90c3d28c-3a5f-11e8-8817-e8184d86f925.PNG)

Logs of nginx
![5](https://user-images.githubusercontent.com/36038814/38453515-a78fd74a-3a5f-11e8-8129-237d9b7ff4ac.PNG)
Rails-server and web-socket also waiting
![6](https://user-images.githubusercontent.com/36038814/38453531-d07a9398-3a5f-11e8-87ef-6498a52b54a3.PNG)

Now click on zammad-init
![7](https://user-images.githubusercontent.com/36038814/38453543-f61ce8f8-3a5f-11e8-82b7-03775efef066.PNG)
Click on start
![8](https://user-images.githubusercontent.com/36038814/38453549-0a3c92b6-3a60-11e8-8cc2-894951e2194a.PNG)
Wait for zammad-inti to rebuild es index you can check in the log what's it doing
![9](https://user-images.githubusercontent.com/36038814/38453564-3f898064-3a60-11e8-85ca-18b7279fee96.PNG)

After the rebuild of es index, it will stop (started once) and now nginx starts
![10](https://user-images.githubusercontent.com/36038814/38453584-931f2378-3a60-11e8-91f9-adf6c3e4e3a8.PNG)

#If you don't want to rebuild es index you can use this command
# create install ready file
su -c "echo 'zammad-init' > ${ZAMMAD_READY_FILE}" ${ZAMMAD_USER}

**Comment by augustoferronato** [comment]
great, now it's working.

Thank so much.

**Comment by CyberPunk2042** [comment]
What do you have?

**Comment by gveltri** [comment]
Is there any way that this requirement can be disabled? The above command doesn't work for me.

**Comment by wodCZ** [comment]
This happens randomly on already running instance. Probably it's caused by healthcheck on nginx container. Disable healtcheck for nginx service in rancher to avoid nginx re-creates.

**Comment by bpvarsity** [comment]
@CyberPunk2042 The fix you provided doesn't seem to be working. Any other way to get Nginx to start?

**Comment by TriBallscom** [comment]
Happened also when starting the first time. Keeps looping.
