### ISSUE TITLE
Please preserve log/productions.log when restarting

### ISSUE THREAD

**Issue by waja** [zammad/zammad-docker-compose#67]
### Infos:

* Docker version: 17.12.1-ce
* Docker-compose version: 1.19.0
* Operating system (Docker host): Debian 9.4

### Expected behavior:

* to keep `log/productions.log` in docker volume when restarting the stack

### Actual behavior:

* `log/productions.log` is empty after (re)starting the compose stack

### Steps to reproduce the behavior:

* (re)starting the compose stack

Rotating can be done by the `backup.sh` script?

Maybe keeping `tmp/unprocessable_mail` would be also a good idea. Deleting it on purpose by local admins might help when you need to debug those mails and need to restart the stack.

**Comment by monotek** [comment]
I plan to push the logs to stdout in the future so it just goes to the docker log....

**Comment by monotek** [comment]
done with: https://github.com/zammad/zammad-docker-compose/commit/d2cb86bd4b33a3c2ff2d498da2b76ed7ca87d8b5

**Comment by waja** [comment]
> I plan to push the logs to stdout in the future so it just goes to the docker log....

On busy sites it may be complicated to find relevant entries in the docker log because of the request logs also ending up in the docker log.

**Comment by monotek** [comment]
Use "grep" or Kibana for filters ;-) 
Logging to files inside a container was the wrong pattern anyway.
stdout ftw ;-)
