### ISSUE TITLE
How to restore the zammad backup?

### ISSUE THREAD

**Issue by macnibblet** [zammad/zammad-docker-compose#68]
I cannot find any documentation on how to restore a backup made

**Comment by monotek** [comment]
Because there is none... 

Just copy files and import DB manually in the containers.

**Comment by macnibblet** [comment]
I have spent a few hours trying to restore from a none docker-compose backup without any luck. Any chance you could walk me through it?

**Comment by lbausch** [comment]
@macnibblet 
Make sure you have your files and your SQL dump ready.

Files should go into `/var/lib/docker/volumes/zammaddockercompose_zammad-data/_data`. You can check if this is the correct path by running `docker inspect zammaddockercompose_zammad-railsserver_1` and see the "Mounts" section which might look like this:
```
"Mounts": [
            {
                "Type": "volume",
                "Name": "zammaddockercompose_zammad-data",
                "Source": "/var/lib/docker/volumes/zammaddockercompose_zammad-data/_data",
                "Destination": "/opt/zammad",
                "Driver": "local",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            }
        ],
```

Copy your files there.

For SQL dump: Make sure to stop all containers except the postgresql container by running `docker stop <container name>`.
To access the SQL dump inside the container you need to check which mounts the container has:
`docker inspect zammaddockercompose_zammad-postgresql_1` (you containers might be named differently).
In my case the volume path mounted in the container is `/var/lib/docker/volumes/zammaddockercompose_postgresql-data/_data`. Copy your backup there.

Next launch a shell inside the postgresql container: `docker exec -it zammaddockercompose_zammad-init_1 bash`. Switch to the postgres user by running `su - postgres`. Change the directory to `/var/lib/postgresql/data` and you should see your backup there. If it is a `.gz` file extract it using `gunzip`.
To get a clean restore you need to drop the existing database by running `dropbdb zammad_production`. Recreate it with `createdb zammad_production`. Finally, import the dump with `psql zammad_production < dump.sql`.
Once you're done exit the container, stop it and use `docker-compose` to start all Zammad containers.

Disclaimer: I'm by no means an Postgres guru so YMMV. :)

**Comment by macnibblet** [comment]
@lbausch This worked almost flawlessly! The only problems is that the files keep getting written over each time I start it and we had replaced the OAuth.rb with a custom solution for hub from JetBrains. But I moved the account login to google OAuth instead. Thanks!

This should definitely be added to a guide somewhere or turned into a bash script

**Comment by waja** [comment]
I did it this way:

- Needed volumes in the Postgresql container:

```
  zammad-postgresql:
    volumes:
      - zammad-data:/opt/zammad
      - zammad-backup:/var/tmp/zammad:ro
```
- Stopping services

```
# docker-compose stop zammad-nginx zammad-websocket zammad-railsserver zammad-memcached zammad-elasticsearch zammad-scheduler
```
- Drop database content

```
# docker-compose exec zammad-postgresql su -c 'dropdb zammad_production' - postgres
```
- Start Scheduler again (to recreate empty db)

```
# docker-compose start zammad-scheduler
```
- Recreate empty database

```
# docker-compose exec zammad-scheduler bundle exec rake db:create
```
- (Preparing) Restore

```
# docker-compose exec zammad-postgresql /bin/sh
$ cp /opt/zammad/contrib/backup/config.dist /opt/zammad/contrib/backup/config && \
  sed -i s/zammad_backup/zammad/g /opt/zammad/contrib/backup/config && \
  ln -s /usr/local/bin/psql /usr/bin/ && \
  /opt/zammad/contrib/backup/zammad_restore.sh
```
- Restart whole compose stack

```
# docker-compose stop; docker-compose start && docker-compose logs -f
```

**Comment by monotek** [comment]
Currently we're not planning to script this in any way. 
Feel free to add a pull request if you have a working solution.
Closing for now.

**Comment by apiening** [comment]
> ```
> # docker-compose exec zammad-postgresql su -c 'dropdb zammad_production' - postgres
> ```

I get the the following error when I try to execute this command:

```
dropdb: could not connect to database template1: FATAL:  role "postgres" does not exist
```

Any idea why this is?

**Comment by MrGeneration** [comment]
Please don't recycle long solved issues for such things.
Either open a new issue on this repo or (better) use the community at https://community.zammad.org .

**Comment by linucksrox** [comment]
Thanks @apiening! I'm currently checking out https://github.com/DoTheEvo/selfhosted-apps-docker/tree/master/zammad#backup-and-restore but if that doesn't work for me then I'll try your solution.

**Comment by mmojadad** [comment]
@waja
Hi
First thank for your good guides.
Question : I am using Ubuntu 20.04
Issue is as following
--------------------
/zammad-docker-compose/zammad-docker-compose# docker-compose exec zammad-postgresql /bin/sh $ cp /opt/zammad/contrib/backup/config.dist /opt/zammad/contrib/backup/config && \ sed -i s/zammad_backup/zammad/g /opt/zammad/contrib/backup/config && \ n -s /usr/local/bin/psql /usr/bin/ && \ /opt/zammad/contrib/backup/zammad_restore.sh
/bin/sh: can't open '$': No such file or directory

**Comment by kmille** [comment]
This worked for me:

## db restore

```bash 
docker compose down --volumes # this deletes all data!                                                                                                                                                                                         
docker compose up zammad-postgresql                                                                                                                                                                                                            
gunzip < /opt/zammad-old/data/backup/20250703081342_zammad_db.psql.gz | docker compose exec -T zammad-postgresql psql -U zammad -d zammad_production # restore backup                                                                          
# verify restore                                                                                                                                                                                                                               
docker compose exec zammad-postgresql psql -U zammad -d zammad_production -c '\dt' # verify: show tables                                                                                                                                       
docker compose exec zammad-postgresql psql -U zammad -d zammad_production -c 'Select count(*) from tickets'                                                                                                                                    
docker compose exec zammad-postgresql psql -U zammad -d zammad_production -c 'Select * from tickets limit 1'                                                                                                                                   
# stop the zammad-postgresql container                                                                                                                                                                                                         
#run the whole setup:                                                                                                                                                                                                                          
docker compose up
```

I could not login at this point (invalid csrf token). Fix for me at this point in docker-compose.override.yml  (`NGINX_SERVER_SCHEME=https` is crucial):
```yaml
services:
  zammad-nginx:
    networks:
      - default
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.zammad.rule: Host(`tickets2.domain.org`)
    environment:
      - NGINX_SERVER_SCHEME=https

```
Don't forget to check Zammad's monitoring (`/#system/monitoring`). I didn't restored the "files", as it was empty in my installation.

Some other useful commands:
```                                                                                                                                                                                                                                               
docker compose exec --user postgres zammad-postgresql psql -U zammad --list # there should be a db: zammad_production (db is specified in docker-compose.yml/.env file)                                                                        
docker compose exec --user postgres zammad-postgresql psql -U zammad -d zammad_production # get db shell                                                                                                                                       
docker compose exec --user postgres zammad-postgresql psql -U zammad -d postgres -c 'drop database zammad_production;' # drop db                                                                                                               
```

Rebuild search index:
docker compose exec zammad-railsserver /docker-entrypoint.sh bundle exec rake zammad:searchindex:rebuild

Clear redis cache:
docker compose exec zammad-railsserver /docker-entrypoint.sh bundle exec rails r "Rails.cache.clear"
