### ISSUE TITLE
Ability to override postgresql database. 

### ISSUE THREAD

**Issue by jbzdak** [zammad/zammad-docker-compose#69]
It would be nice if I had a way to change database zammad-docker-compose connects to. I mean postgresql database (not postgresql host). 

### Expected behavior:

* I have enviornment variable ``POSTGRESQL_DB`` that I can set in env file to override default database name. 

### Actual behavior:

* Docker compose always uses "zammad_production"

**Comment by monotek** [comment]
done in: https://github.com/zammad/zammad-docker-compose/commit/0b80e0d34b94f0f1e5b7f52a39db4d7e213b5bbe

**Comment by jbzdak** [comment]
Thanks for fixing this!
