### ISSUE TITLE
Ability to launch zammad without ``CREATEDB`` priveledge. 

### ISSUE THREAD

**Issue by jbzdak** [zammad/zammad-docker-compose#70]
I'd like to deploy zammad, that uses postgresql user without ``CREATEDB`` in this scenario database is already created by other means. 

Problem is that entrypint executes ``db:seed`` only when it needs to create zammad database.

**Comment by monotek** [comment]
So you already have a zammad db which is populated with data?

Using the postgresql env vars from the entrypoint should work:
https://github.com/zammad/zammad-docker-compose/blob/master/containers/zammad/docker-entrypoint.sh

**Comment by jbzdak** [comment]
My scenario is: "to deploy zammad with minimal manual steps". In this case I have existing database, without seed data (and without any tables), database was created using other means than: ``db:create``. 

Right now I need to manually  ssh to zammad container and run ``db:seed``. After I run ``db:seed``, everything works like a charm :)

**Comment by monotek** [comment]
done in: https://github.com/zammad/zammad-docker-compose/commit/0e7c68b7415afe580c360e6691c6e4f05c03bbe6
