### ISSUE TITLE
docker-compose not updated to the 2.5 version

### ISSUE THREAD

**Issue by Oleszkiewicz** [zammad/zammad-docker-compose#77]
### Infos:

* Docker version: 17.06.0-ce
* Docker-compose version: 1.21.2, build a133471
* Operating system (Docker host): Photon OS 2.0

### Expected behavior:

The command sequence :

docker-compose stop
git pull
docker-compose pull
docker-compose up

should update Zammad

### Actual behavior:

*git pull

root@photon-machine [ ~/zammad-docker-compose ]# git pull
Already up to date.

### Steps to reproduce the behavior:

*run commands

**Comment by waja** [comment]
This is expected

* there is no 2.5 tag at https://hub.docker.com/r/zammad/zammad-docker-compose/tags/, so there is no image with 2.5 (yet)
* you need to update `VERSION=` in you `.env` file anyway (maybe this should be better documented)

**Comment by Oleszkiewicz** [comment]
OK, is it expected to actually lag behind the RPM version? When should I expect the images with 2.5 to appear in the repo? (Or should I switch to RPM version for deployment)

**Comment by monotek** [comment]
Currently we have some build errors. Need to investigate first.

**Comment by monotek** [comment]
The builds are fixed now: https://travis-ci.org/zammad/zammad-docker-compose/builds/391210110
We heave at least a new version with latest tag now: https://hub.docker.com/r/zammad/zammad-docker-compose/tags/
As soons as a new commit goes to stable we also get a tagged 2.5.0 version.

**Comment by Oleszkiewicz** [comment]
Already upgraded - everything works perfectly.
