### ISSUE TITLE
sysctl -w vm.max_map_count=262144

### ISSUE THREAD

**Issue by omexXx** [zammad/zammad-docker-compose#8]
Hi,

I use docker in plesk to install but i receive this error:
sysctl -w vm.max_map_count=262144 can not be set in container, there is File in read only?

I have set up in host system sysctl -w vm.max_map_count=262144 but don't work?

**Comment by monotek** [comment]
Whats the output of: 

docker-compose logs

**Comment by omexXx** [comment]
Hi,

So here we are:
- docker-compose is not installed on plesk onyx as standart, and i dont install it because it can break the system but we don't need it at all (different images, can be installed zammad/zammad)

![install](https://cloud.githubusercontent.com/assets/26206772/23621965/0abe4e92-029d-11e7-88cc-f6100c0b5056.jpg)

`Running zammad/zammad-docker-compose
{"message":"manifest for zammad/zammad-docker-compose:latest not found"}`

![error_install](https://cloud.githubusercontent.com/assets/26206772/23621968/0f49c9f0-029d-11e7-9fcf-c5a560265a0e.jpg)

![select_alternative](https://cloud.githubusercontent.com/assets/26206772/23621970/1391672a-029d-11e7-871a-6709d33b14ae.jpg)

![container_settings](https://cloud.githubusercontent.com/assets/26206772/23621981/1c546740-029d-11e7-9686-742e0c7fff28.jpg)

Only see nginx default page
![only_nginx](https://cloud.githubusercontent.com/assets/26206772/23621984/2150aa38-029d-11e7-8f0f-bbde4319f9f7.jpg)

Logs (always more of the same errors):
`Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
waiting for postgres to be ready...
waiting for postgres to be ready...
waiting for postgres to be ready...
waiting for postgres to be ready...
waiting for postgres to be ready...
waiting for postgres to be ready...
waiting for postgres to be ready...
waiting for postgres to be ready...
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

Starting PostgreSQL 9.4 database server: main.
Starting Elasticsearch Server:.
Starting Postfix Mail Transport Agent: postfix.
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: setting key "vm.max_map_count": Read-only file system
`

So resume it don't work on plesk :(

**Comment by monotek** [comment]
You're using zammad/docker not zammad/docker-compose.

As zammad/docker is meant for testing only no persistent volumes are used so you'll lose all your data if the container is stopped.

Anyway, i'll guess your problem here is that you have to change the servername directive in the nginx vhost, as the the final note says: "If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!"

Unfortunately i can't tell how this works in plesk.

**Comment by omexXx** [comment]
Yes but the zammad/docker-compose can't be installed see error:
`Running zammad/zammad-docker-compose {"message":"manifest for zammad/zammad-docker-compose:latest not found"}`

Also i have tried to modify the nginx directive as a proxy, but there i see also only nginx.

**Comment by monotek** [comment]
There is no latest tag for zammad/zammad-docker-compose. 

See: https://hub.docker.com/r/zammad/zammad-docker-compose/tags/

Are you're sure Plesk is compatible to docker-compose?

**Comment by omexXx** [comment]
Slowly i think its not compatible :D
