### ISSUE TITLE
Kubernetes - why single deployment?

### ISSUE THREAD

**Issue by JannikZed** [zammad/zammad-docker-compose#81]
I'm currently testing zammad with kubernetes and try to find the best way of deploying it in our cluster. I already added max values for system resources, as this is very important for k8 scheduling features. I also realized, that it's pretty "unpractical" to have zammad nginx, websocket, scheduler & railsserver in one single pod.. this makes it pretty uncomfortable to work with & to scale it. For example, we have some problems with the railsserver currently, as it is failing again and again. It's hard to debug the reason why, as kubernetes is just showing some problems with the liveness probe of the nginx service. 
Furthermore, you can't scale the railsserver independently from the scheduler for example.
So what is the reason behind this design decision? 

Kind regards

**Comment by monotek** [comment]
The reason is that the storage needs to be shared. You would need to have some sort of network storage to run the containers in single pods.

**Comment by JannikZed** [comment]
alright. Thank you. I don't really understand the reason behind it, as we have with postgres and elasticsearch already two shared database sytems, that can do this job, but anyhow ..

**Comment by monotek** [comment]
Closing as question is answered.

There is some progress to make Zammad stateless but it will take some time to get there...

Maybe you want to follow: https://github.com/zammad/zammad/issues/1601

**Comment by monotek** [comment]
we have a helm chart now: https://github.com/zammad/helm
