### ISSUE TITLE
Current version (2.5.0-51) broken

### ISSUE THREAD

**Issue by SneakyMax** [zammad/zammad-docker-compose#83]
### Infos:

* Docker version: 18.06.0-ce
* Docker-compose version: N/A (Kubernetes)
* Operating system (Docker host): CentOS 7

### Expected behavior:

* Working zammad install

### Actual behavior:

* Backup container fails, and scheduler container fails.

Backup:
```
/usr/local/bin/docker-entrypoint.sh: line 172: exec: zammad-backup-db: not found
```

Scheduler:
```
starting scheduler...
bundler: failed to load command: script/scheduler.rb (script/scheduler.rb)
Bundler::GemNotFound: Could not find crass-1.0.3 in any of the sources
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/spec_set.rb:91:in `block in materialize'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/spec_set.rb:85:in `map!'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/spec_set.rb:85:in `materialize'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/definition.rb:171:in `specs'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/definition.rb:238:in `specs_for'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/definition.rb:227:in `requested_specs'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:108:in `block in definition_method'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:20:in `setup'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler.rb:107:in `setup'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/setup.rb:20:in `<top (required)>'
  /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
```

### Steps to reproduce the behavior:

* Run the docker compose suite, `zammad/zammad-docker-compose:zammad-2.5.0-51`

Returning to `zammad-2.5.0-43` fixed the problem. I don't know when the problem was introduced so I just went back a while.

Would it be possible to not automatically publish the images if they don't run?

Also, the kubernetes files having `imagePullPolicy: always` screwed me here because as soon as something restarted, I got the new version. Maybe the kubernetes files could be pinned to a specific version (and updated with commits to this project?)

**Comment by mdeboer** [comment]
> don't know, but I seem to run in the same issue on kubernetes: `/opt/zammad/app/models/setting.rb:37:in set': Can't find config setting 'es_url' (RuntimeError)`

See #85

**Comment by monotek** [comment]
closing as current version is 2.8.0-1
