### ISSUE TITLE
Can't find config setting 'es_url' (RuntimeError)

### ISSUE THREAD

**Issue by JannikZed** [zammad/zammad-docker-compose#85]
When trying to start the kubernetes setup I receive the following error on the init-container:

```
initialising / updating database...
10.8.2018 12:48:20 changing settings...
10.8.2018 12:48:27 /opt/zammad/app/models/setting.rb:37:in `set': Can't find config setting 'es_url' (RuntimeError)
10.8.2018 12:48:27 	from /usr/local/bundle/gems/railties-5.1.5/lib/rails/commands/runner/runner_command.rb:37:in `perform'
10.8.2018 12:48:27 	from /usr/local/bundle/gems/railties-5.1.5/lib/rails/commands/runner/runner_command.rb:37:in `eval'
10.8.2018 12:48:27 	from /usr/local/bundle/gems/railties-5.1.5/lib/rails/commands/runner/runner_command.rb:37:in `perform'
10.8.2018 12:48:27 	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
10.8.2018 12:48:27 	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
10.8.2018 12:48:27 	from /usr/local/bundle/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
10.8.2018 12:48:27 	from /usr/local/bundle/gems/railties-5.1.5/lib/rails/command/base.rb:63:in `perform'
10.8.2018 12:48:27 	from /usr/local/bundle/gems/railties-5.1.5/lib/rails/command.rb:44:in `invoke'
10.8.2018 12:48:27 	from /usr/local/bundle/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
10.8.2018 12:48:27 	from bin/rails:4:in `require'
10.8.2018 12:48:27 	from bin/rails:4:in `<main>'
```

Did anybody run into this issue before? Actually, everything went fine before, but after a complete recreation test, I only receive this strange issue that makes no sense to me..
Any good idea is highly appreciated

**Comment by JannikZed** [comment]
No matter what I try, I don't get it up .. any zammad guys here for a little support?

**Comment by monotek** [comment]
Sorry, no time at the moment...

**Comment by nenad007** [comment]
I have the same Issue with the RPM Install on Centos 7. 

Was you able to find a solution?

**Comment by martini** [comment]
I'm no docker expert. But the error message means that the entry `'es_url'` is not existing in the `settings` table. So it seems that the database is not initialised.

**Comment by JannikZed** [comment]
@martini do you have an idea on how to solve this? I'm actually trying to set-up a complete fresh version of zammad - so no data existing yet. The zammad init-container is normally setting up elaticsearch & postgres, but in our case it's just failing.. the code looks perfectly fine to me - es_url is set using the environment variable `ELASTICSEARCH_HOST`.. nevertheless just failing :(

**Comment by nenad007** [comment]
I even can not set es_url:
 zammad run rails r 'Setting.set("es_url", "http://localhost:9200")'
/opt/zammad/app/models/setting.rb:37:in `set': Can't find config setting 'es_url' (RuntimeError)

zammad run rails r 'p Setting.get("es_url")'
nil

**Comment by lukeisontheroad** [comment]
I had the same issue. It was, because I wanted to use an existing database instead of the provided docker postgres. Eventually I was able to work around the issue by:

1. Create all the containers (including the postgres)
2. Attach to the postgres container and export the structure (before the configuration process)
3. Import the structure to the existing database
4. Override the database connection & delete the postgres container
5. Go through the initial setup steps

I assume it's because of reduced database user permissions, unfortunately I never found a useful error message anywhere.

**Comment by rouing** [comment]
This is still an issue...

**Comment by gionn** [comment]
I've workaround this error by stopping zammad-postgresql, cleaning the volume (an host bind mount in my case) and start it again.

Don't know what happened the first time but now it's working.

**Comment by mdeboer** [comment]
I ran into the same issue and had a go at fixing it. Works for me!

To get up and running, wait for it to be merged and built or clone the repo from my PR and build the zammad image yourself.

**Comment by jv-barsuk** [comment]
I managed to fix the issue following the description here: https://community.zammad.org/t/elasticsearch-error-after-importing-a-backup-zammad-6-0-0/11854/14

I copied the relevant part:
First, you connect to the Rails server container:

Connects you to the Rails server container
`docker exec -u 0 -it zammad-railsserver bash`

As the container does not contain an editor, you install one. I recommend nano:

Updates package lists for upgrades and new installations
`apt update  `
Installs the text editor nano
`apt install nano  `
Opens the database configuration file with nano
`nano config/database.yml`

The following values should be entered or added under production:

```
production:  
  adapter: postgresql  
  database: zammad_production  
  pool: 50  
  timeout: 5000  
  encoding: utf8  
  username: zammad  
  password: zammad  
  host: zammad-postgresql  
  port: 5432
```

Save your changes and disconnect with exit.

Now you can set the correct link for Elasticsearch:

Sets the Elasticsearch link in the Zammad settings
`docker compose exec -it zammad-railsserver rails r "Setting.set('es_url', 'http://zammad-elasticsearch:9200')"`

Now you can execute the actual command that is still needed:

Initiates the process of rebuilding the search index
`docker compose exec -it zammad-railsserver rake zammad:searchindex:rebuild`

Remember that these commands are executed in a certain context. It might be necessary to adapt them to your specific environment. Always make sure to create backups of your data and keep them safe before making significant changes to your infrastructure.
