### ISSUE TITLE
reverse proxy example fails to start (version mismatch)

### ISSUE THREAD

**Issue by jampy** [zammad/zammad-docker-compose#88]
### Infos:

* Docker version: 18.09.0
* Docker-compose version: 1.23.1
* Operating system (Docker host): Debian 9

### Expected behavior:

* docker-compose up succeeds

### Actual behavior:

* `ERROR: Version mismatch: file ./docker-compose.yml specifies version 2.0 but extension file ./docker-compose.prod.yml uses version 3.3`

### Steps to reproduce the behavior:

* installed Zammad exactly as described in https://docs.zammad.org/en/latest/install-docker-compose.html
* ran `docker-compose up`, verified that the installation responds correctly on port 80
* set up `zammad-docker-compose/docker-compose.prod.yml` as described in https://github.com/zammad/zammad-docker-compose by just changing the `VIRTUAL_HOST`
* running `docker-compose -f docker-compose.yml -f docker-compose.prod.yml up` the error above appears

**Comment by masonr** [comment]
Ran into this as well. Fixed it by changing the version specified at the top of `docker-compose.yml` from '2' to '3.3' to match the `docker-compose.prod.yml` file. Compose was able to create and start the containers after this change.
