### ISSUE TITLE
Version 2.8.0 / 2.9.0

### ISSUE THREAD

**Issue by morph027** [zammad/zammad-docker-compose#89]
I can't find recent versions like 2.7.0or 2.8.0 on Docker Hub...

Is there something wrong with the build system? Repo is showing the latest debs...

**Comment by monotek** [comment]
2.8.0-1 is currently building: https://travis-ci.org/zammad/zammad-docker-compose/builds/464704703

2.9.0 is unstable an wont be build for ducker compose until its merge to the stable repo.

**Comment by morph027** [comment]
Great, thanks for the info! :+1:
