### ISSUE TITLE
Question: Change port?

### ISSUE THREAD

**Issue by omexXx** [zammad/zammad-docker-compose#9]
Hello,

I try to install this in a container, how can i change the port (for outside)?

**Comment by martini** [comment]
Please more details like: 

1) What Zammad version did you use?

2) What is you goal?

3) What is your discovered problem?

4) What did you expect?

**Comment by monotek** [comment]
You have to change the ports in docker-compose.yml before you run "docker-compose up".
If "docker-compose up" was already used you have to "docker-compsoe down" (and lose all your data).

**Comment by monotek** [comment]
Closing, because you solved it in: https://github.com/zammad/zammad-docker-compose/issues/10
