### ISSUE TITLE
SSL for Docker Zammad

### ISSUE THREAD

**Issue by nvdo49** [zammad/zammad-docker-compose#91]
How can we setup SSL for the docker-compose version of Zammad?

**Comment by monotek** [comment]
Depends on your setup. 
Normaly you would have some proxy in front of zammads nginx to handle ssl termination.

**Comment by nvdo49** [comment]
> Depends on your setup.
> Normaly you would have some proxy in front of zammads nginx to handle ssl termination.

My current issue with the Docker setup is that https://zammad-nginx doesn't work (http://zammad-nginx works).

I have a reverse proxy (also Nginx) on an AWS box in front of the Zammad box. I have configured SSL reverse proxy on that AWS nginx to point to https://zammad-nginx, which is not useful yet because https://zammad-nginx doesn't work yet.

**Comment by monotek** [comment]
Maybe you like to switch to our Kubernetes deployment?

Just use our Helm chart from: https://hub.helm.sh/charts?q=zammad

There its possible to activate SSL encryption by modifying the ingress rule. See:
https://github.com/zammad/helm/blob/master/zammad/values.yaml#L14

SSL setup in docker compose is out of our support scope.

Closing...

**Comment by MrGeneration** [comment]
@danperrout you may want to point out extra good that this is an alternative and not the official way. Also, your email setup in the readme is not related to the topic and may miss lead users. It's not required at all. Just saying (apart from it being noted in Zammad documentation)

**Comment by danperrout** [comment]
> @danperrout you may want to point out extra good that this is an alternative and not the official way. Also, your email setup in the readme is not related to the topic and may miss lead users. It's not required at all. Just saying (apart from it being noted in Zammad documentation)

Sure, I'll point that out in the Readme file.

As the smtp mail configuration, it took me so long to find it that I want to include it (as optional on the title I must say) to new comers, as my organization provide smtp access only and we really enjoy the Zammad notification feature.
