### ISSUE TITLE
Missing config for zammad-nginx 

### ISSUE THREAD

**Issue by gpkvt** [zammad/zammad-docker-compose#95]
### Infos:

* Docker version: not relevant
* Docker-compose version: not relevant
* Operating system (Docker host): not relevant

### Expected behavior:

* After `docker-compose up` the connection to `localhost:80` should show zammad web interface

### Actual behavior:

* nginx default page is shown

### Steps to reproduce the behavior:

* git clone https://github.com/zammad/zammad-docker-compose.git
* cd zammad-docker-compose
* docker-compose up
* curl http://localhost:80

After replacing `/etc/nginx/sites-enabled/default` with https://github.com/zammad/zammad/blob/develop/contrib/nginx/zammad.conf in `zammad-nginx` while replacing `127.0.0.1` in `upstream` with the proper container name, everything works as expected.

**Comment by davidm2312** [comment]
In addition, I needed to expose the ports for zammad-railsserver and zammad-websocket containers.

I added the following to the docker-compose.override.yml file:

```
  zammad-railsserver:
    ports:
      - "3000:3000"

  zammad-websocket:
    ports:
      - "6042:6042"
```

**Comment by monotek** [comment]
nginx config should be fixed with: https://github.com/zammad/zammad-docker-compose/commit/f64bdf16aac42b605e05ad9c8e40eac10da64c8a#diff-f8d139fe502ebb73058d8f32c2426e68R113
