### ISSUE TITLE
Docker image for 151371c after revert

### ISSUE THREAD

**Issue by mdoerfel** [zammad/zammad-docker-compose#97]
Hi,

I was just starting to file an issue when I recognized that you reverted commits c221f39 and 4af4fae. So to make it short - when do you expect that the previous docker images (or rebuilt ones) corresponding to commit 151371c can be pulled?

The current docker image shows as
'zammad/zammad-docker-compose      zammad                 4147d4245f6d        3 hours ago'
and was created "2019-02-15T12:01:17.560557514Z".

Thanks,
Matthias.

**Comment by monotek** [comment]
They are still available. 
Use 2.8.0-34 tag instead of latest..

**Comment by mdoerfel** [comment]
Just for later reference: The tag must be set in .env as follows
`VERSION=-2.8.0-34`
