### ISSUE TITLE
Migrate old Database to new one

### ISSUE THREAD

**Issue by ReisKanzlerTao** [zammad/zammad-docker-compose#99]
Hello guys,

I have to integrate the old data with the tickets and customers into a new system.
The old Zammad System (2.3.x) was installed via Docker and the new one on Debian via DEB (2.9.x).
Both systems are installed on Debian 9 and PostgreSQL

Thanks for the help !

Best regards
Tao

**Comment by waja** [comment]
As starting point have a look into https://docs.zammad.org/en/latest/appendix-backup-and-restore.html, the first hit for http://lmgtfy.com/?iie=1&q=zammad+export+database.

**Comment by ReisKanzlerTao** [comment]
Well, the path /opt/zammad/contrib/backup doesnt exist under the zammad installation.
Thats the reason why asked for help.

**Comment by ReisKanzlerTao** [comment]
> 
> 
> As starting point have a look into https://docs.zammad.org/en/latest/appendix-backup-and-restore.html, the first hit for http://lmgtfy.com/?iie=1&q=zammad+export+database.

The path isnt the same path under docker. But I found the backup.sh  
~/zammad-docker-compose/containers/zammad-postgresql
I tried to run the backup.sh file as root but unfortunately it tells me that I don't have permission.
Where does Zammad save the backup ? 

So what could I try next ?

**Comment by MrGeneration** [comment]
The location of the backup highly depends on if you changed the compose file.
Default location is `/var/tmp/zammad`. The files being found there should already be enough for restoring on your system.

Docker backups roughly every 24 hours and after starting the compose.
You might want to temporary disable your E-Mail-Channels to ensure no data is being changed during backup.

That should help you to do the magic. ;)

**Comment by ReisKanzlerTao** [comment]
> 
> 
> The location of the backup highly depends on if you changed the compose file.
> Default location is `/var/tmp/zammad`. The files being found there should already be enough for restoring on your system.
> 
> Docker backups roughly every 24 hours and after starting the compose.
> You might want to temporary disable your E-Mail-Channels to ensure no data is being changed during backup.
> 
> That should help you to do the magic. ;)

There is a cryptic file there "systemd-private-db.....
Is this the backup file ?

**Comment by MrGeneration** [comment]
As I said, your compose file should know best (you're searching for Zammad-Backup and it's volume).
The files are `.gz`-files and contain `zammad` within the filename.

The location for the backup-files depends on the configuration of your backup-config within `/opt/zammad/contrib/backup`. By the way: Restoring is covered by https://docs.zammad.org/en/latest/appendix-backup-and-restore.html completely as this is not a docker.

![image](https://user-images.githubusercontent.com/6549061/53521665-07854700-3ad9-11e9-9a11-092696e1e826.png)

Helping you further is quite difficult in my opinion.

**Comment by ReisKanzlerTao** [comment]
Am I completely retarded? 
I cant find theses files under the docker system.
I tried it with **find / -iname "zammad"** and **"gz"** but it cant find it.
Under /var/tmp isnt any folder named zammad.
There is just one file named systemd-private-db699.............-timesyncd.service-On0OYF

**Comment by MrGeneration** [comment]
Go to your docker-compose directory and do the following:

`docker-compose -p zammad down`
`docker-compose -p zammad up`

This should give you log output, close after starting you should see log entries of zammad_backup writing a backup.

If this og entry does not appear within 5 minutes, something might be broken or not working as expected.

**Comment by waja** [comment]
> The location of the backup highly depends on if you changed the compose file.
Default location is `/var/tmp/zammad`. The files being found there should already be enough for restoring on your system.

If you use the `docker-compose.yml` of this project, have a look into https://github.com/zammad/zammad-docker-compose/blob/master/docker-compose.yml#L15. You can find the backups in the `zammad-backup` volume. With this file, follow the docu at https://docs.zammad.org/en/latest/appendix-backup-and-restore.html.

**Comment by ReisKanzlerTao** [comment]
> 
> 
> > The location of the backup highly depends on if you changed the compose file.
> > Default location is `/var/tmp/zammad`. The files being found there should already be enough for restoring on your system.
> 
> If you use the `docker-compose.yml` of this project, have a look into https://github.com/zammad/zammad-docker-compose/blob/master/docker-compose.yml#L15. You can find the backups in the `zammad-backup` volume. With this file, follow the docu at https://docs.zammad.org/en/latest/appendix-backup-and-restore.html.

What do you mean with "if I´m using". Is there any other options ? 
I looked under both paths and there was nothing or the path didnt exist.
- zammad-backup:/var/tmp/zammad
- zammad-data:/opt/zammad

> 
> 
> Go to your docker-compose directory and do the following:
> 
> `docker-compose -p zammad down`
> `docker-compose -p zammad up`
> 
> This should give you log output, close after starting you should see log entries of zammad_backup writing a backup.
> 
> If this og entry does not appear within 5 minutes, something might be broken or not working as expected.

I´m gonna try this now.

**Comment by ReisKanzlerTao** [comment]
Is it possible to extract just the tickets and customers ?
I dont need the whole system.

**Comment by sandrodz** [comment]
Backup is simple:

```sudo docker exec zammadkubikthemescom_zammad-backup_1 /usr/local/bin/backup.sh zammad-backup-once```

to see generated backup files:

```sudo ls -lh /var/lib/docker/volumes/zammadkubikthemescom_zammad-backup/_data```

Obviously modify `zammadkubikthemescom_zammad-backup_1` to match your container name.

**Comment by ReisKanzlerTao** [comment]
> 
> 
> Backup is simple:
> 
> `sudo docker exec zammadkubikthemescom_zammad-backup_1 /usr/local/bin/backup.sh zammad-backup-once`
> 
> to see generated backup files:
> 
> `sudo ls -lh /var/lib/docker/volumes/zammadkubikthemescom_zammad-backup/_data`
> 
> Obviously modify `zammadkubikthemescom_zammad-backup_1` to match your container name.

Thank you !!! 
So there are 2 files for every day: zammad_files.tar.gz and zammad_db.psql.gz
Those files can be restored by moving the old backups into the new server under 
/opt/zammad/contrib/backup and the script ./zammad_restore.sh 
Am I right ?

**Comment by waja** [comment]
Sorry @ReisKanzlerTao, but please consult the documentation or ask for payed support somewhere (else)! This is an issue tracker and not a support forum.

**Comment by sandrodz** [comment]
For restore read docs: https://docs.zammad.org/en/latest/appendix-backup-and-restore.html

**Comment by ReisKanzlerTao** [comment]
> 
> 
> Sorry @ReisKanzlerTao, but please consult the documentation or ask for payed support somewhere (else)! This is an issue tracker and not a support forum.

Allright. 
Anyways, thank you for youre help guys !
